# File: bcmdrivers/opensource/net/bcmsmux/Makefile
#
# Makefile for the BCM63xx bcmsmux driver.
#

obj-y := smux.o

EXTRA_CFLAGS += -I$(INC_BRCMDRIVER_PUB_PATH)/$(BRCM_BOARD) -I$(INC_BRCMSHARED_PUB_PATH)/$(BRCM_BOARD) -I$(INC_BRCMBOARDPARMS_PATH)/$(BRCM_BOARD)

clean:
	rm -f core *.o *.a *.s

