/* A lexical scanner generated by flex*/

/* Scanner skeleton version:
 * $Header: /cvs/cable/Cow/userspace/gpl/apps/radvd/scanner.c,v 1.3 2015/08/20 02:27:27 dana_tseng Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* Some routines like yy_flex_realloc() are emitted as static but are
   not called by all lexers. This generates warnings in some compilers,
   notably GCC. Arrange to suppress these. */
#ifdef __GNUC__
#define YY_MAY_BE_UNUSED __attribute__((unused))
#else
#define YY_MAY_BE_UNUSED
#endif

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t )) YY_MAY_BE_UNUSED;
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 53
#define YY_END_OF_BUFFER 54
static yyconst short int yy_accept[514] =
    {   0,
        0,    0,   54,   52,    3,    2,   52,   52,   51,   41,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   50,
       50,   50,   50,   50,   50,   50,   50,   50,    3,    0,
        1,   42,    0,   41,    0,    0,   40,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   50,    0,   50,   50,
       50,   50,   50,   50,   45,   50,   50,   43,   41,    0,
        0,   40,    0,    0,    0,    0,    0,    0,    0,    0,
       50,   50,   50,   50,   50,   50,   47,   50,   46,   50,
       50,   41,    0,    0,    0,   40,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   50,   50,   49,   50,
       50,   50,   50,   50,   41,    0,    0,   40,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    7,    0,   50,   50,   50,   50,   50,    6,
        0,    0,    0,   40,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   50,
       50,   50,   48,    5,    0,    0,   40,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   50,   50,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   44,   50,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   21,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    4,    0,    0,    0,    0,
        0,    0,    0,    0,   14,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   29,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   36,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   22,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   25,
        9,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   17,    0,    0,    0,    0,   27,   12,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   40,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       16,    0,    0,    0,    0,    0,    0,    0,    8,    0,
        0,    0,    0,   40,    0,    0,    0,   26,   28,    0,
        0,    0,   37,    0,   15,   34,    0,    0,   23,    0,
        0,    0,    0,    0,    0,   40,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   30,   32,    0,   10,    0,
       11,   40,    0,   18,    0,    0,   13,    0,   35,   33,

       20,    0,   38,    0,    0,    0,    0,   31,    0,   19,
       39,   24,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    6,    7,    8,    8,    8,
        8,    9,    8,   10,    8,    8,    8,   11,   12,    1,
        1,    1,    1,    1,   13,   14,   15,   16,   17,   18,
        1,   19,   20,    1,    1,   21,   22,   23,   24,   25,
        1,   26,   27,   28,   29,   30,    1,    1,    1,    1,
        1,    1,    1,    1,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   41,   48,   49,   50,   51,   52,   53,   54,
       55,   41,   56,    1,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    3,    3,    3,
        4,    1,    5,    5,    5,    5,    5,    5,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        6,    3,    3,    3,    3,    3,    3,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    1,    1
    } ;

static yyconst short int yy_base[555] =
    {   0,
        0,    0,  884,  885,  881,  885,  879,   50,  885,   55,
      870,   56,   62,   63,  834,  841,   38,  862,  832,   89,
       65,   69,   66,   73,   76,  139,  104,  102,  874,  872,
      885,   80,  108,  145,  863,   75,  885,  151,  152,  829,
      827,  817,  825,  846,  828,  151,  196,  156,   90,  162,
      171,  163,  164,  180,  172,  179,  183,  171,  187,  181,
      856,    0,  222,  830,  829,  818,  837,   67,  835,  827,
      210,  245,  214,  234,  196,  258,  245,  259,  260,  261,
      277,  281,  849,  848,  847,  846,  805,  804,  818,  807,
      807,  811,  254,  251,  802,  259,  238,  817,  838,  834,

      798,  795,  808,  793,  815,  809,  291,  298,  304,  305,
      306,  307,  308,  315,  314,  829,  828,  827,    0,  787,
      788,  798,  790,  783,  787,  786,  797,  808,  789,  791,
      803,  207,  774,  779,  772,  779,  771,  782,  783,  770,
      774,  768,  885,  766,  320,  326,  327,  328,  329,  330,
      803,  802,  801,  800,  764,  790,  776,  771,  770,  763,
      772,  777,  762,  765,  763,  772,  764,  749,  746,  760,
      746,  753,  746,  755,  770,  776,  756,  774,  736,  334,
      341,  349,  350,  351,  774,  773,  772,  737,  735,  729,
      766,  730,  755,  738,  725,  729,  725,  736,  744,  731,

      737,  732,  754,  732,  730,  755,  718,  725,  726,  705,
      724,  734,  357,  359,  746,  745,  744,  708,  706,  709,
      713,  698,  721,  712,  699,  704,  730,  696,  350,  711,
      697,  328,  706,  704,  718,  718,  687,  714,  683,  720,
      681,  687,  367,  371,  720,  719,  685,  707,  677,  690,
      693,  695,  688,  695,  885,  675,  672,  679,  671,  669,
      683,  666,  674,  665,  699,  659,  689,  669,  663,  359,
      667,  686,  669,  684,  660,  379,  691,  690,  689,  653,
      658,  367,  652,  653,  885,  677,  643,  648,  656,  654,
      654,  653,  645,  659,  649,  649,  649,  647,  661,  644,

      630,  639,  630,  628,  631,  625,  629,  618,  661,  660,
      619,  625,  628,  619,  616,  641,  621,  616,  625,  626,
      624,  614,  621,  621,  616,  619,  617,  618,  604,  638,
      614,  613,  611,  611,  597,  595,  591,  593,  885,  631,
      630,  629,  590,  598,  600,  600,  129,  588,  602,  586,
      592,  610,  580,  885,  593,  600,  583,  576,  589,  576,
      573,  587,  571,  572,  583,  581,  577,  580,  579,  578,
      602,  601,  885,  561,  574,  572,  565,  562,  556,  567,
      558,  565,  562,  561,  552,  559,  562,  557,  548,  885,
      885,  560,  554,  556,  542,  555,  545,  541,  552,  539,

      575,  574,  573,  885,  533,  546,  549,  543,  885,  885,
      531,  560,  540,  532,  539,  530,  525,  528,  535,  522,
      525,  536,  527,  518,  527,  512,  518,  510,  550,  549,
      519,  510,  519,  510,  505,  511,  517,  516,  506,  514,
      885,  513,  503,  511,  510,  511,  500,  407,  885,  394,
      385,  378,  398,  397,  395,  361,  368,  885,  885,  385,
      370,  351,  885,  366,  885,  885,  365,  349,  885,  361,
      360,  350,  351,  376,  344,  375,  368,  333,  322,  316,
      308,  285,  268,  267,  244,  885,  885,  251,  885,  227,
      885,  257,  239,  885,  193,  194,  885,  144,  885,  885,

      885,  136,  885,  160,  110,   76,   56,  885,   74,  885,
      885,  885,  885,  412,  417,  421,  426,  429,  433,  436,
      439,  442,  445,  448,  451,  454,  457,  460,  463,  466,
      469,  472,  475,  478,  481,  484,  487,  490,  493,  496,
      499,  502,  505,  508,  511,  514,  517,  520,  523,  526,
      529,  532,  535,  538
    } ;

static yyconst short int yy_def[555] =
    {   0,
      513,    1,  513,  513,  513,  513,  514,  513,  513,  515,
      513,  515,  515,  515,  513,  513,  513,  513,  513,  513,
      516,  516,  516,  516,  516,  516,  516,  516,  513,  514,
      513,  513,  513,  517,  518,  517,  513,  517,  517,  513,
      513,  513,  513,  513,  513,  513,   20,  518,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  513,  519,  519,
      520,  521,  513,  513,  513,  513,  513,  513,  513,  513,
      513,   20,  520,  516,  516,  516,  516,  516,  516,  516,
      516,  513,  513,  522,  523,  524,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,

      513,  513,  513,  513,  513,  513,  516,  522,  516,  516,
      516,  516,  516,  516,  513,  525,  526,  527,  521,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  525,  516,  516,  516,  516,  516,
      513,  528,  529,  530,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      516,  516,  516,  516,  531,  532,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,

      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  516,  516,  513,  533,  534,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  516,  516,  535,  536,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  516,  513,  537,  538,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,

      513,  513,  513,  513,  513,  513,  513,  513,  539,  540,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      541,  542,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      543,  544,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,

      513,  545,  546,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  547,  548,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  549,  550,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  551,  552,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  553,  513,  513,  513,  513,  513,  513,  513,

      513,  513,  513,  554,  513,  513,  513,  513,  513,  513,
      513,  513,    0,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513
    } ;

static yyconst short int yy_nxt[943] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,   10,   10,
       11,    9,   12,   13,   14,   14,   14,   14,   15,   16,
        4,   17,    4,    4,    4,   18,    4,    4,   19,    4,
        4,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       21,   21,   24,   25,   21,   26,   27,   28,   21,   21,
       21,   21,   21,   21,   21,    9,    9,   32,   32,   32,
       33,  513,   34,   34,   34,   35,   35,  513,  513,   42,
       46,   46,   35,   35,   46,   46,   46,   43,   46,   46,
      513,   46,  103,   46,  455,   35,   46,   32,   32,   32,
       38,  512,  104,   39,   46,   46,   47,   47,   47,   48,

       46,   36,   36,   36,   36,   36,   36,   46,   50,   46,
       51,   53,   46,  511,   46,   58,   58,   58,   52,   49,
       47,   47,   47,   47,   47,   47,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   46,  510,  377,   57,  378,   46,
       33,   56,   59,   59,   59,   35,  513,  513,   71,   71,
       71,   35,   35,   73,   73,   73,   62,   46,   46,   46,
      455,  508,   46,   46,   46,   54,   46,   46,   58,   58,
       58,   46,   46,   55,   46,   46,  513,  507,   46,   46,
       46,   35,   33,   46,   82,   82,   82,   35,   78,   74,

       64,   46,   63,   72,   72,   72,   46,   75,   60,   60,
       60,   60,   60,   60,   80,   77,   79,   71,   71,   71,
       76,  108,  108,  108,   85,  506,  505,   72,   72,   72,
       72,   72,   72,   81,   87,  110,   88,   89,  167,   46,
       90,   91,   92,   93,   46,   94,   95,   96,   97,  455,
       46,   98,  107,  107,  107,   46,  168,   83,   83,   83,
       83,   83,   83,   46,   46,   46,   46,  455,   46,   46,
       46,   46,  109,  134,  131,  503,  107,  107,  107,  107,
      107,  107,   46,  135,  502,  126,   33,   46,  115,  115,
      115,   35,  501,  111,  132,  128,   46,  113,  112,  127,

      129,   48,  500,  499,  133,  145,  145,  145,   85,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   33,
       46,  115,  115,  115,  498,   46,  114,  180,  180,  180,
       85,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   71,   71,   71,   85,  497,   46,  149,  263,  146,
      150,   46,  264,  147,   46,   46,   46,  148,  496,   46,
       46,   46,   46,  182,   46,  181,  495,   46,  494,   46,
      258,  183,   46,  259,  260,  265,   46,   46,  455,  302,
      214,   46,  184,  303,   46,  455,  491,  313,  490,   46,
      213,  314,  244,  489,  488,  487,  486,  485,  484,  483,

      482,  481,  480,  479,  478,   62,  276,  455,  403,  475,
      474,  243,   30,   30,   30,   30,   30,   30,   36,   36,
       36,   36,   49,   49,   49,  473,   49,   60,   60,   60,
       60,   61,   61,   61,   83,   83,   83,   83,   84,   84,
       84,   86,  472,   86,  116,  116,  116,  117,  117,  117,
      118,  118,  118,  151,  151,  151,  152,  152,  152,  154,
      154,  154,  185,  185,  185,  186,  186,  186,  187,  187,
      187,  215,  215,  215,  216,  216,  216,  245,  245,  245,
      246,  246,  246,  277,  277,  277,  278,  278,  278,  309,
      309,  309,  310,  310,  310,  340,  340,  340,  341,  341,

      341,  371,  371,  371,  372,  372,  372,  401,  401,  401,
      402,  402,  402,  429,  429,  429,  430,  430,  430,  453,
      453,  453,  454,  454,  454,  476,  476,  476,  477,  477,
      477,  492,  492,  492,  493,  493,  493,  504,  504,  504,
      509,  509,  509,  471,  470,  469,  468,  467,  466,  465,
      464,  463,  462,  461,  460,  459,  458,  457,  456,  455,
      403,  452,  451,  450,  449,  448,  447,  446,  445,  444,
      443,  442,  441,  440,  439,  438,  437,  436,  435,  434,
      433,  432,  431,   62,  403,  342,  428,  427,  426,  425,
      424,  423,  422,  421,  420,  419,  418,  417,  416,  415,

      414,  413,  412,  411,  410,  409,  408,  407,  406,  405,
      404,  403,  342,  400,  399,  398,  397,  396,  395,  394,
      393,  392,  391,  390,  389,  388,  387,  386,  385,  384,
      383,  382,  381,  380,  379,  376,  375,  374,  373,   62,
      342,  279,  370,  369,  368,  367,  366,  365,  364,  363,
      362,  361,  360,  359,  358,  357,  356,  355,  354,  353,
      352,  351,  350,  349,  348,  347,  346,  345,  344,  343,
      342,  279,  339,  338,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  315,  312,  311,   62,

      279,  217,  308,  307,  306,  305,  304,  301,  300,  299,
      298,  297,  296,  295,  294,  293,  292,  291,  290,  289,
      288,  287,  286,  285,  284,  283,  282,  281,  280,  279,
      217,  275,  274,  273,  272,  271,  270,  269,  268,  267,
      266,  262,  261,  257,  256,  255,  254,  253,  252,  251,
      250,  249,  248,  247,   62,  217,  153,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  226,  225,  224,  223,  222,  221,  220,
      219,  218,  119,  217,  153,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,

      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,
      119,   62,  153,   85,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  166,  165,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  155,  119,  153,   85,
      144,  143,  142,  141,  140,  139,  138,  137,  136,  130,
      125,  124,  123,  122,  121,  120,  119,   62,   85,   35,
      106,  105,  102,  101,  100,   99,   85,   70,   69,   68,
       67,   66,   65,   62,   31,   29,   45,   44,   41,   40,
       37,   31,   29,  513,    3,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,

      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513
    } ;

static yyconst short int yy_chk[943] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    8,    8,    8,
       10,   12,   10,   10,   10,   10,   12,   13,   14,   17,
       21,   23,   13,   14,   22,   21,   23,   17,   24,   22,
       36,   25,   68,   24,  509,   36,   25,   32,   32,   32,
       12,  507,   68,   13,   20,   49,   20,   20,   20,   20,

       49,   20,   20,   20,   20,   20,   20,   28,   22,   27,
       23,   25,   28,  506,   27,   33,   33,   33,   24,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   26,  505,  347,   28,  347,   26,
       34,   27,   34,   34,   34,   34,   38,   39,   46,   46,
       46,   38,   39,   48,   48,   48,   48,   50,   52,   53,
      504,  502,   50,   52,   53,   26,   51,   55,   58,   58,
       58,   51,   55,   26,   56,   54,   60,  498,   57,   56,
       54,   60,   59,   57,   59,   59,   59,   59,   53,   50,

       39,   75,   38,   47,   47,   47,   75,   51,   47,   47,
       47,   47,   47,   47,   56,   52,   54,   71,   71,   71,
       51,   73,   73,   73,   73,  496,  495,   47,   47,   47,
       47,   47,   47,   57,   63,   75,   63,   63,  132,   74,
       63,   63,   63,   63,   74,   63,   63,   63,   63,  493,
       77,   63,   72,   72,   72,   77,  132,   72,   72,   72,
       72,   72,   72,   76,   78,   79,   80,  492,   76,   78,
       79,   80,   74,   97,   96,  490,   72,   72,   72,   72,
       72,   72,   81,   97,  488,   93,   82,   81,   82,   82,
       82,   82,  485,   76,   96,   94,  107,   80,   78,   93,

       94,  107,  484,  483,   96,  108,  108,  108,  108,  109,
      110,  111,  112,  113,  109,  110,  111,  112,  113,  115,
      114,  115,  115,  115,  482,  114,   81,  145,  145,  145,
      145,  146,  147,  148,  149,  150,  146,  147,  148,  149,
      150,  180,  180,  180,  180,  481,  181,  113,  232,  110,
      114,  181,  232,  111,  182,  183,  184,  112,  480,  182,
      183,  184,  213,  147,  214,  146,  479,  213,  478,  214,
      229,  148,  243,  229,  229,  232,  244,  243,  477,  270,
      182,  244,  149,  270,  276,  476,  475,  282,  474,  276,
      181,  282,  214,  473,  472,  471,  470,  468,  467,  464,

      462,  461,  460,  457,  456,  455,  244,  454,  453,  452,
      451,  213,  514,  514,  514,  514,  514,  514,  515,  515,
      515,  515,  516,  516,  516,  450,  516,  517,  517,  517,
      517,  518,  518,  518,  519,  519,  519,  519,  520,  520,
      520,  521,  448,  521,  522,  522,  522,  523,  523,  523,
      524,  524,  524,  525,  525,  525,  526,  526,  526,  527,
      527,  527,  528,  528,  528,  529,  529,  529,  530,  530,
      530,  531,  531,  531,  532,  532,  532,  533,  533,  533,
      534,  534,  534,  535,  535,  535,  536,  536,  536,  537,
      537,  537,  538,  538,  538,  539,  539,  539,  540,  540,

      540,  541,  541,  541,  542,  542,  542,  543,  543,  543,
      544,  544,  544,  545,  545,  545,  546,  546,  546,  547,
      547,  547,  548,  548,  548,  549,  549,  549,  550,  550,
      550,  551,  551,  551,  552,  552,  552,  553,  553,  553,
      554,  554,  554,  447,  446,  445,  444,  443,  442,  440,
      439,  438,  437,  436,  435,  434,  433,  432,  431,  430,
      429,  428,  427,  426,  425,  424,  423,  422,  421,  420,
      419,  418,  417,  416,  415,  414,  413,  412,  411,  408,
      407,  406,  405,  403,  402,  401,  400,  399,  398,  397,
      396,  395,  394,  393,  392,  389,  388,  387,  386,  385,

      384,  383,  382,  381,  380,  379,  378,  377,  376,  375,
      374,  372,  371,  370,  369,  368,  367,  366,  365,  364,
      363,  362,  361,  360,  359,  358,  357,  356,  355,  353,
      352,  351,  350,  349,  348,  346,  345,  344,  343,  342,
      341,  340,  338,  337,  336,  335,  334,  333,  332,  331,
      330,  329,  328,  327,  326,  325,  324,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  314,  313,  312,  311,
      310,  309,  308,  307,  306,  305,  304,  303,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  284,  283,  281,  280,  279,

      278,  277,  275,  274,  273,  272,  271,  269,  268,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  257,
      256,  254,  253,  252,  251,  250,  249,  248,  247,  246,
      245,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      233,  231,  230,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  215,  212,  211,  210,
      209,  208,  207,  206,  205,  204,  203,  202,  201,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  179,  178,  177,  176,  175,
      174,  173,  172,  171,  170,  169,  168,  167,  166,  165,

      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  144,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  133,  131,  130,  129,  128,  127,
      126,  125,  124,  123,  122,  121,  120,  118,  117,  116,
      106,  105,  104,  103,  102,  101,  100,   99,   98,   95,
       92,   91,   90,   89,   88,   87,   86,   85,   84,   83,
       70,   69,   67,   66,   65,   64,   61,   45,   44,   43,
       42,   41,   40,   35,   30,   29,   19,   18,   16,   15,
       11,    7,    5,    3,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,

      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define INITIAL 0
/*
 *   $Id: scanner.c,v 1.3 2015/08/20 02:27:27 dana_tseng Exp $
 *
 *   Authors:
 *    Pedro Roque		<roque@di.fc.ul.pt>
 *    Lars Fenneberg		<lf@elemental.net>	 
 *
 *   This software is Copyright 1996-2000 by the above mentioned author(s), 
 *   All Rights Reserved.
 *
 *   The license which is distributed with this software in the file COPYRIGHT
 *   applies to this software. If your distribution is missing this file, you
 *   may request it from <pekkas@netcore.fi>.
 *
 */
#line 17 "scanner.l"
#include <config.h>
#include <includes.h>
#include <radvd.h>
#include <gram.h>

extern char *conf_file;

int num_lines = 1;
#line 783 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 38 "scanner.l"


#line 937 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 514 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 885 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 40 "scanner.l"
{/* ignore comments */}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 41 "scanner.l"
{num_lines++;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 42 "scanner.l"
{}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "scanner.l"
{ return T_INTERFACE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 45 "scanner.l"
{ return T_PREFIX; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 46 "scanner.l"
{ return T_ROUTE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 47 "scanner.l"
{ return T_RDNSS; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "scanner.l"
{ return T_IgnoreIfMissing; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 50 "scanner.l"
{ return T_AdvSendAdvert; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 51 "scanner.l"
{ return T_MaxRtrAdvInterval; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 52 "scanner.l"
{ return T_MinRtrAdvInterval; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 53 "scanner.l"
{ return T_AdvManagedFlag; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "scanner.l"
{ return T_AdvOtherConfigFlag; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "scanner.l"
{ return T_AdvLinkMTU; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "scanner.l"
{ return T_AdvReachableTime; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "scanner.l"
{ return T_AdvRetransTimer; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 58 "scanner.l"
{ return T_AdvCurHopLimit; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "scanner.l"
{ return T_AdvDefaultLifetime; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "scanner.l"
{ return T_AdvDefaultPreference; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "scanner.l"
{ return T_AdvSourceLLAddress; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 63 "scanner.l"
{ return T_AdvOnLink; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 64 "scanner.l"
{ return T_AdvAutonomous; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "scanner.l"
{ return T_AdvValidLifetime; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "scanner.l"
{ return T_AdvPreferredLifetime; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 68 "scanner.l"
{ return T_AdvRouterAddr; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 69 "scanner.l"
{ return T_AdvHomeAgentFlag; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 70 "scanner.l"
{ return T_AdvIntervalOpt; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 71 "scanner.l"
{ return T_AdvHomeAgentInfo; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 72 "scanner.l"
{ return T_UnicastOnly; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 74 "scanner.l"
{ return T_Base6to4Interface; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 76 "scanner.l"
{ return T_HomeAgentPreference; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 77 "scanner.l"
{ return T_HomeAgentLifetime; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 79 "scanner.l"
{ return T_AdvRoutePreference; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 80 "scanner.l"
{ return T_AdvRouteLifetime; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 82 "scanner.l"
{ return T_AdvRDNSSPreference; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 83 "scanner.l"
{ return T_AdvRDNSSOpenFlag; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 84 "scanner.l"
{ return T_AdvRDNSSLifetime; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 86 "scanner.l"
{ return T_MinDelayBetweenRAs; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 88 "scanner.l"
{ return T_AdvMobRtrSupportFlag; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 90 "scanner.l"
{
			static struct in6_addr addr;
			int i;
				
			i = inet_pton(AF_INET6, yytext, &addr);

			dlog(LOG_DEBUG, 4, "inet_pton returned %d", i);

			/* BSD API draft and NRL's code don't aggree on
			 * this. the draft specifies a return value of 1 on 
			 * success, NRL's code returns the address length in 
			 * bytes on success (16 for an IPv6 address)
			 */
			if (i < 1) {
				flog(LOG_ERR, "invalid address in %s, line %d", conf_file,
					num_lines);
				return T_BAD_TOKEN;
			}

			yylval.addr = &addr;
			return IPV6ADDR;
		}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 113 "scanner.l"
{
			unsigned long lnum;
			char *endp;
			lnum = strtoul(yytext, &endp, 10);
			if (*yytext == '\0' || *endp != '\0')
				return T_BAD_TOKEN;
			if (lnum > 0xFFFFFFFFUL)
				return T_BAD_TOKEN;	/* XXX */
			yylval.num = lnum;
			return NUMBER;
		}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 125 "scanner.l"
{ yylval.snum = atoi(yytext); return SIGNEDNUMBER; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 127 "scanner.l"
{ yylval.dec = atof(yytext); return DECIMAL; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 129 "scanner.l"
{ return INFINITY; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 131 "scanner.l"
{ yylval.bool = 1; return SWITCH; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 133 "scanner.l"
{ yylval.bool = 0; return SWITCH; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 135 "scanner.l"
{ yylval.snum = -1; return SIGNEDNUMBER; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 137 "scanner.l"
{ yylval.snum = 0; return SIGNEDNUMBER; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 139 "scanner.l"
{ yylval.snum = 1; return SIGNEDNUMBER; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 141 "scanner.l"
{
			static char name[IFNAMSIZ];
				
			strncpy(name, yytext, IFNAMSIZ-1);
			name[IFNAMSIZ-1] = '\0';
			yylval.str = name;
			return STRING;
		}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 150 "scanner.l"
{ return *yytext; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 152 "scanner.l"
{ return T_BAD_TOKEN; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 153 "scanner.l"
ECHO;
	YY_BREAK
#line 1326 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 514 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 514 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 513);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 153 "scanner.l"

