#***********************************************************************
#
#  Copyright (c) 2006  Broadcom Corporation
#  All Rights Reserved
#
#  <:license-private
#
#***********************************************************************/

EXE = imgbin2hex
SRC = imgbin2hex.c

all : $(EXE)

clean:
	rm -f $(EXE)

$(EXE):
	gcc -o $@ $(SRC)
