#!/bin/sh
echo 
echo aprbridge setup
echo ---------------
#Add our bridge
brctl addbr aprBridge
#
#Set our interfaces IPs to nothing
ifconfig ethsw0 0.0.0.0
ifconfig ethsw0 up
ifconfig ethsw1 0.0.0.0
ifconfig ethsw1 up
ifconfig ethsw2 0.0.0.0
ifconfig ethsw2 up
ifconfig ethsw3 0.0.0.0
ifconfig ethsw3 up

ifconfig wlan0 0.0.0.0
ifconfig wlan0 up
ifconfig wlan1 0.0.0.0
ifconfig wlan1 up

ifconfig guest0 0.0.0.0
ifconfig guest0 up
ifconfig guest1 0.0.0.0
ifconfig guest1 up
ifconfig guest2 0.0.0.0
ifconfig guest3 up
ifconfig guest3 0.0.0.0
ifconfig guest3 up

ifconfig guest_2_0 0.0.0.0
ifconfig guest_2_0 up
ifconfig guest_2_1 0.0.0.0
ifconfig guest_2_1 up
ifconfig guest_2_2 0.0.0.0
ifconfig guest_2_2 up
ifconfig guest_2_3 0.0.0.0
ifconfig guest_2_3 up

ifconfig cmlan_ipstack0 0.0.0.0
ifconfig cmlan_ipstack0 up


#Add our interfaces to be bridged
brctl addif aprBridge ethsw0
brctl addif aprBridge ethsw1
brctl addif aprBridge ethsw2
brctl addif aprBridge ethsw3
brctl addif aprBridge wlan0
brctl addif aprBridge wlan1
brctl addif aprBridge guest0
brctl addif aprBridge guest1
brctl addif aprBridge guest2
brctl addif aprBridge guest3

brctl addif aprBridge guest_2_0
brctl addif aprBridge guest_2_1
brctl addif aprBridge guest_2_2
brctl addif aprBridge guest_2_3

brctl addif aprBridge cmlan_ipstack0

#Give our bridge an IP Address
ifconfig aprBridge 192.168.1.2 netmask 255.255.255.0


#Startup our bridge
ifconfig aprBridge up
ifconfig ethsw0 up
ifconfig ethsw1 up
ifconfig ethsw2 up
ifconfig ethsw3 up

ifconfig wlan0 up
ifconfig wlan1 up

ifconfig guest0 up
ifconfig guest1 up
ifconfig guest2 up
ifconfig guest3 up

ifconfig guest_2_0 up
ifconfig guest_2_1 up
ifconfig guest_2_2 up
ifconfig guest_2_3 up

#
#Show our bridge
brctl show
echo 
echo apr bridge setup completed!!
echo 

#/sbin/udhcpc -b -i aprBridge -p /var/run/udhcpc.pid -s /etc/dhcp/dhcpc.script 
#/sbin/udhcpc -b -i eth0 -p /var/run/udhcpc.pid -s /etc/dhcp/dhcpc.script 
 
