obj-$(CONFIG_BRCM_PERF_TEST) +=  perf_test.o perf_test_asm.o

cflags-$(CONFIG_BCM3384)      += -I$(srctree)/arch/mips/include/asm/mach-bcm3384
EXTRA_CFLAGS    += -I$(INC_BRCMBOARDPARMS_PATH)/$(BRCM_BOARD) -I$(SRCBASE)/include -I$(INC_BRCMDRIVER_PUB_PATH)/$(BRCM_BOARD) -I$(INC_BRCMSHARED_PUB_PATH)/$(BRCM_BOARD)
