#! /bin/sh

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
export LD_LIBRARY_PATH=/lib:/usr/local/lib

mount -t proc proc /proc
/bin/mount -a
#/sbin/inetd

# TMOUT=0 means no busybox shell timeout.
# if you want the busybox shell to timeout after some number of seconds of inactivity,
# change the 0 to the number of seconds, e.g. 300.
export TMOUT=0

echo
firsttime=`echo /var/udhcpd/udhcpd.lease*`
if [ "$firsttime" = "/var/udhcpd/udhcpd.lease*" ]; then
 logger -s -t rcS "Loading drivers and kernel modules... "
 echo
# no-op
# create directory in /var mounted for TMPFS
 mknod /var/fuse c 10 229
 chmod a+rw /var/fuse
 mkdir -p /var/log /var/run /var/state/dhcp /var/ppp /var/udhcpd /var/zebra /var/siproxd /var/cache /var/tmp /var/samba /var/samba/share /var/samba/homes /var/samba/private /var/samba/locks /var/samba/spool /var/samba/lib /var/fyi/sys /mnt/hd var/spool/cups var/spool/cups/tmp /var/cache/cups/rss /var/run/cups/certs /var/log/cups

cp  /etc/smb.conf /var/samba/lib 2>/dev/null

 echo > /var/udhcpd/udhcpd.leases
 ifconfig lo 127.0.0.1 netmask 255.0.0.0 broadcast 127.255.255.255 up
# /etc/modules_install /lib/modules/extra
# test -e /lib/modules/kernel/net/ipv6/ipv6.ko && insmod /lib/modules/kernel/net/ipv6/ipv6.ko
 test -e /lib/modules/extra/bcm_fpm.ko && insmod /lib/modules/extra/bcm_fpm.ko
 test -e /lib/modules/extra/bcm_iop.ko && insmod /lib/modules/extra/bcm_iop.ko
 test -e /lib/modules/extra/bcm_venet.ko && insmod /lib/modules/extra/bcm_venet.ko
 test -e /lib/modules/extra/bcm_virtnihal.ko && insmod /lib/modules/extra/bcm_virtnihal.ko
 test -e /lib/modules/extra/bcm_usb_host.ko && insmod /lib/modules/extra/bcm_usb_host.ko
 test -e /lib/modules/kernel/drivers/net/mii.ko && insmod /lib/modules/kernel/drivers/net/mii.ko
 test -e /lib/modules/kernel/drivers/usb/net/usbnet.ko && insmod /lib/modules/kernel/drivers/usb/net/usbnet.ko
 test -e /lib/modules/kernel/drivers/usb/net/cdc_ether.ko && insmod /lib/modules/kernel/drivers/usb/net/cdc_ether.ko
 test -e /lib/modules/kernel/drivers/scsi/sd_mod.ko && insmod /lib/modules/kernel/drivers/scsi/sd_mod.ko
 test -e /lib/modules/kernel/drivers/scsi/sg.ko && insmod /lib/modules/kernel/drivers/scsi/sg.ko
 test -e /lib/modules/kernel/drivers/usb/storage/usb-storage.ko && insmod /lib/modules/kernel/drivers/usb/storage/usb-storage.ko
 test -e /lib/modules/extra/dspdd.ko && insmod /lib/modules/extra/dspdd.ko
 test -e /lib/modules/extra/dectshim.ko && insmod /lib/modules/extra/dectshim.ko
 test -e /lib/modules/extra/dect.ko && insmod /lib/modules/extra/dect.ko
fi

# Start the DECT deamon
if [ -f /bin/dectd ]; then
  echo "Starting dectd"
  /bin/dectd&
fi

echo "Starting syslogd"
# Log to /va/log/message with max size 100kb and purge
syslogd -s 100 -b 0

# Mount to apps partition /apps for 3383 processor
grep 3380 /proc/cpuinfo > /dev/null
if [ $? -ne 0 ]; then
    grep noapp /proc/cmdline > /dev/null
    if [ $? -eq 0 ]; then
        logger -s -t rcS "Skipping - Mounting apps partition"
    else
        logger -s -t rcS  "Mounting apps partition"
        mount | grep ubifs > /dev/null
        if [ $? -eq 0 ]; then
            if [ -c /dev/ubi1 ]; then
	        ubinfo -a | grep linuxapps > /dev/null
	        if [ $? -eq 0 ]; then
                    mount -t ubifs ubi1:linuxapps /apps
	        else
	            logger -s -t rcS  "Creating volume linuxapps..."
	            ubimkvol /dev/ubi1 -N linuxapps -m > /dev/null
                    mount -t ubifs ubi1:linuxapps /apps > /dev/null
	        fi
            fi
        else
            mount -t jffs2 /dev/mtdblock4 /apps
        fi
    fi
fi

logger -s -t rcS  "Starting lxginit"
lxginit &

logger -s -t rcS  "Starting udhcpc"
udhcpc -b -t 10 -i eth0 -p /var/run/udhcpc.pid -s /etc/dhcp/dhcpc.script | logger -s -t udhcpc 

logger -s -t rcS  "Starting gwrepair"
/etc/gwrepair 5

grep nouart /proc/cmdline > /dev/null
if [ $? -eq 0 ]; then
    logger -s -t rcS  "Starting portmap"
    portmap
    logger -s -t rcS  "Starting telnetd"
    telnetd &
fi

if [ -f /apps/version.txt ]; then
    setappsver /apps/version.txt
fi
if [ -f /usr/local/etc/init.d/rc.apps ]; then     
    . /usr/local/etc/init.d/rc.apps
fi

grep ttyS0 /proc/cmdline > /dev/null
if [ $? -eq 0 ]; then
    logger -s -t rcS  "Starting getty on ttyS0"
    getty-start 0 ttyS0
fi
