/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Nov 14 03:20:39 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_HW_COUNTER_GB_H__
#define BCHP_HW_COUNTER_GB_H__

/***************************************************************************
 *HW_COUNTER_GB
 ***************************************************************************/
#define BCHP_HW_COUNTER_GB_CNT_0                 0x104b0100 /* Hardware Counter 0 Register */
#define BCHP_HW_COUNTER_GB_CNT_1                 0x104b0104 /* Hardware Counter 1 Register */
#define BCHP_HW_COUNTER_GB_CNT_2                 0x104b0108 /* Hardware Counter 2 Register */
#define BCHP_HW_COUNTER_GB_CNT_3                 0x104b010c /* Hardware Counter 3 Register */
#define BCHP_HW_COUNTER_GB_CNT_4                 0x104b0110 /* Hardware Counter 4 Register */
#define BCHP_HW_COUNTER_GB_CNT_5                 0x104b0114 /* Hardware Counter 5 Register */
#define BCHP_HW_COUNTER_GB_CNT_6                 0x104b0118 /* Hardware Counter 6 Register */
#define BCHP_HW_COUNTER_GB_CNT_7                 0x104b011c /* Hardware Counter 7 Register */
#define BCHP_HW_COUNTER_GB_CNT_8                 0x104b0120 /* Hardware Counter 8 Register */
#define BCHP_HW_COUNTER_GB_CNT_9                 0x104b0124 /* Hardware Counter 9 Register */
#define BCHP_HW_COUNTER_GB_CNT_10                0x104b0128 /* Hardware Counter 10 Register */
#define BCHP_HW_COUNTER_GB_CNT_11                0x104b012c /* Hardware Counter 11 Register */
#define BCHP_HW_COUNTER_GB_CNT_12                0x104b0130 /* Hardware Counter 12 Register */
#define BCHP_HW_COUNTER_GB_CNT_13                0x104b0134 /* Hardware Counter 13 Register */
#define BCHP_HW_COUNTER_GB_CNT_14                0x104b0138 /* Hardware Counter 14 Register */
#define BCHP_HW_COUNTER_GB_CNT_15                0x104b013c /* Hardware Counter 15 Register */
#define BCHP_HW_COUNTER_GB_CNT_16                0x104b0140 /* Hardware Counter 16 Register */
#define BCHP_HW_COUNTER_GB_CNT_17                0x104b0144 /* Hardware Counter 17 Register */
#define BCHP_HW_COUNTER_GB_CNT_18                0x104b0148 /* Hardware Counter 18 Register */
#define BCHP_HW_COUNTER_GB_CNT_19                0x104b014c /* Hardware Counter 19 Register */
#define BCHP_HW_COUNTER_GB_CNT_20                0x104b0150 /* Hardware Counter 20 Register */
#define BCHP_HW_COUNTER_GB_CNT_21                0x104b0154 /* Hardware Counter 21 Register */
#define BCHP_HW_COUNTER_GB_CNT_22                0x104b0158 /* Hardware Counter 22 Register */
#define BCHP_HW_COUNTER_GB_CNT_23                0x104b015c /* Hardware Counter 23 Register */
#define BCHP_HW_COUNTER_GB_CNT_24                0x104b0160 /* Hardware Counter 24 Register */
#define BCHP_HW_COUNTER_GB_CNT_25                0x104b0164 /* Hardware Counter 25 Register */
#define BCHP_HW_COUNTER_GB_CNT_26                0x104b0168 /* Hardware Counter 26 Register */
#define BCHP_HW_COUNTER_GB_CNT_27                0x104b016c /* Hardware Counter 27 Register */
#define BCHP_HW_COUNTER_GB_CNT_28                0x104b0170 /* Hardware Counter 28 Register */
#define BCHP_HW_COUNTER_GB_CNT_29                0x104b0174 /* Hardware Counter 29 Register */
#define BCHP_HW_COUNTER_GB_CNT_30                0x104b0178 /* Hardware Counter 30 Register */
#define BCHP_HW_COUNTER_GB_CNT_31                0x104b017c /* Hardware Counter 31 Register */
#define BCHP_HW_COUNTER_GB_IRQ_MSK               0x104b0180 /* Hardware Counter Irq Mask Register */
#define BCHP_HW_COUNTER_GB_IRQ_STS               0x104b0184 /* Hardware Counter Irq Status Register */

/***************************************************************************
 *CNT_0 - Hardware Counter 0 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_0 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_0_reserved0_MASK                    0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_0_reserved0_SHIFT                   16

/* HW_COUNTER_GB :: CNT_0 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_0_count_MASK                        0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_0_count_SHIFT                       0

/***************************************************************************
 *CNT_1 - Hardware Counter 1 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_1 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_1_reserved0_MASK                    0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_1_reserved0_SHIFT                   16

/* HW_COUNTER_GB :: CNT_1 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_1_count_MASK                        0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_1_count_SHIFT                       0

/***************************************************************************
 *CNT_2 - Hardware Counter 2 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_2 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_2_reserved0_MASK                    0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_2_reserved0_SHIFT                   16

/* HW_COUNTER_GB :: CNT_2 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_2_count_MASK                        0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_2_count_SHIFT                       0

/***************************************************************************
 *CNT_3 - Hardware Counter 3 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_3 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_3_reserved0_MASK                    0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_3_reserved0_SHIFT                   16

/* HW_COUNTER_GB :: CNT_3 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_3_count_MASK                        0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_3_count_SHIFT                       0

/***************************************************************************
 *CNT_4 - Hardware Counter 4 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_4 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_4_reserved0_MASK                    0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_4_reserved0_SHIFT                   16

/* HW_COUNTER_GB :: CNT_4 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_4_count_MASK                        0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_4_count_SHIFT                       0

/***************************************************************************
 *CNT_5 - Hardware Counter 5 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_5 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_5_reserved0_MASK                    0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_5_reserved0_SHIFT                   16

/* HW_COUNTER_GB :: CNT_5 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_5_count_MASK                        0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_5_count_SHIFT                       0

/***************************************************************************
 *CNT_6 - Hardware Counter 6 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_6 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_6_reserved0_MASK                    0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_6_reserved0_SHIFT                   16

/* HW_COUNTER_GB :: CNT_6 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_6_count_MASK                        0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_6_count_SHIFT                       0

/***************************************************************************
 *CNT_7 - Hardware Counter 7 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_7 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_7_reserved0_MASK                    0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_7_reserved0_SHIFT                   16

/* HW_COUNTER_GB :: CNT_7 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_7_count_MASK                        0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_7_count_SHIFT                       0

/***************************************************************************
 *CNT_8 - Hardware Counter 8 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_8 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_8_reserved0_MASK                    0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_8_reserved0_SHIFT                   16

/* HW_COUNTER_GB :: CNT_8 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_8_count_MASK                        0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_8_count_SHIFT                       0

/***************************************************************************
 *CNT_9 - Hardware Counter 9 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_9 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_9_reserved0_MASK                    0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_9_reserved0_SHIFT                   16

/* HW_COUNTER_GB :: CNT_9 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_9_count_MASK                        0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_9_count_SHIFT                       0

/***************************************************************************
 *CNT_10 - Hardware Counter 10 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_10 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_10_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_10_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_10 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_10_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_10_count_SHIFT                      0

/***************************************************************************
 *CNT_11 - Hardware Counter 11 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_11 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_11_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_11_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_11 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_11_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_11_count_SHIFT                      0

/***************************************************************************
 *CNT_12 - Hardware Counter 12 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_12 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_12_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_12_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_12 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_12_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_12_count_SHIFT                      0

/***************************************************************************
 *CNT_13 - Hardware Counter 13 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_13 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_13_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_13_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_13 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_13_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_13_count_SHIFT                      0

/***************************************************************************
 *CNT_14 - Hardware Counter 14 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_14 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_14_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_14_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_14 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_14_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_14_count_SHIFT                      0

/***************************************************************************
 *CNT_15 - Hardware Counter 15 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_15 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_15_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_15_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_15 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_15_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_15_count_SHIFT                      0

/***************************************************************************
 *CNT_16 - Hardware Counter 16 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_16 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_16_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_16_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_16 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_16_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_16_count_SHIFT                      0

/***************************************************************************
 *CNT_17 - Hardware Counter 17 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_17 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_17_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_17_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_17 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_17_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_17_count_SHIFT                      0

/***************************************************************************
 *CNT_18 - Hardware Counter 18 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_18 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_18_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_18_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_18 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_18_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_18_count_SHIFT                      0

/***************************************************************************
 *CNT_19 - Hardware Counter 19 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_19 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_19_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_19_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_19 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_19_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_19_count_SHIFT                      0

/***************************************************************************
 *CNT_20 - Hardware Counter 20 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_20 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_20_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_20_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_20 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_20_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_20_count_SHIFT                      0

/***************************************************************************
 *CNT_21 - Hardware Counter 21 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_21 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_21_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_21_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_21 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_21_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_21_count_SHIFT                      0

/***************************************************************************
 *CNT_22 - Hardware Counter 22 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_22 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_22_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_22_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_22 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_22_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_22_count_SHIFT                      0

/***************************************************************************
 *CNT_23 - Hardware Counter 23 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_23 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_23_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_23_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_23 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_23_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_23_count_SHIFT                      0

/***************************************************************************
 *CNT_24 - Hardware Counter 24 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_24 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_24_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_24_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_24 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_24_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_24_count_SHIFT                      0

/***************************************************************************
 *CNT_25 - Hardware Counter 25 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_25 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_25_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_25_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_25 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_25_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_25_count_SHIFT                      0

/***************************************************************************
 *CNT_26 - Hardware Counter 26 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_26 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_26_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_26_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_26 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_26_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_26_count_SHIFT                      0

/***************************************************************************
 *CNT_27 - Hardware Counter 27 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_27 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_27_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_27_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_27 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_27_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_27_count_SHIFT                      0

/***************************************************************************
 *CNT_28 - Hardware Counter 28 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_28 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_28_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_28_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_28 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_28_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_28_count_SHIFT                      0

/***************************************************************************
 *CNT_29 - Hardware Counter 29 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_29 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_29_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_29_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_29 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_29_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_29_count_SHIFT                      0

/***************************************************************************
 *CNT_30 - Hardware Counter 30 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_30 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_30_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_30_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_30 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_30_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_30_count_SHIFT                      0

/***************************************************************************
 *CNT_31 - Hardware Counter 31 Register
 ***************************************************************************/
/* HW_COUNTER_GB :: CNT_31 :: reserved0 [31:16] */
#define BCHP_HW_COUNTER_GB_CNT_31_reserved0_MASK                   0xffff0000
#define BCHP_HW_COUNTER_GB_CNT_31_reserved0_SHIFT                  16

/* HW_COUNTER_GB :: CNT_31 :: count [15:00] */
#define BCHP_HW_COUNTER_GB_CNT_31_count_MASK                       0x0000ffff
#define BCHP_HW_COUNTER_GB_CNT_31_count_SHIFT                      0

/***************************************************************************
 *IRQ_MSK - Hardware Counter Irq Mask Register
 ***************************************************************************/
/* HW_COUNTER_GB :: IRQ_MSK :: CNTR31_IRQ_MSK [31:31] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR31_IRQ_MSK_MASK             0x80000000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR31_IRQ_MSK_SHIFT            31
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR31_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR30_IRQ_MSK [30:30] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR30_IRQ_MSK_MASK             0x40000000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR30_IRQ_MSK_SHIFT            30
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR30_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR29_IRQ_MSK [29:29] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR29_IRQ_MSK_MASK             0x20000000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR29_IRQ_MSK_SHIFT            29
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR29_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR28_IRQ_MSK [28:28] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR28_IRQ_MSK_MASK             0x10000000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR28_IRQ_MSK_SHIFT            28
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR28_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR27_IRQ_MSK [27:27] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR27_IRQ_MSK_MASK             0x08000000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR27_IRQ_MSK_SHIFT            27
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR27_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR26_IRQ_MSK [26:26] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR26_IRQ_MSK_MASK             0x04000000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR26_IRQ_MSK_SHIFT            26
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR26_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR25_IRQ_MSK [25:25] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR25_IRQ_MSK_MASK             0x02000000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR25_IRQ_MSK_SHIFT            25
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR25_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR24_IRQ_MSK [24:24] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR24_IRQ_MSK_MASK             0x01000000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR24_IRQ_MSK_SHIFT            24
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR24_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR23_IRQ_MSK [23:23] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR23_IRQ_MSK_MASK             0x00800000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR23_IRQ_MSK_SHIFT            23
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR23_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR22_IRQ_MSK [22:22] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR22_IRQ_MSK_MASK             0x00400000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR22_IRQ_MSK_SHIFT            22
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR22_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR21_IRQ_MSK [21:21] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR21_IRQ_MSK_MASK             0x00200000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR21_IRQ_MSK_SHIFT            21
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR21_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR20_IRQ_MSK [20:20] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR20_IRQ_MSK_MASK             0x00100000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR20_IRQ_MSK_SHIFT            20
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR20_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR19_IRQ_MSK [19:19] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR19_IRQ_MSK_MASK             0x00080000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR19_IRQ_MSK_SHIFT            19
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR19_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR18_IRQ_MSK [18:18] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR18_IRQ_MSK_MASK             0x00040000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR18_IRQ_MSK_SHIFT            18
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR18_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR17_IRQ_MSK [17:17] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR17_IRQ_MSK_MASK             0x00020000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR17_IRQ_MSK_SHIFT            17
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR17_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR16_IRQ_MSK [16:16] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR16_IRQ_MSK_MASK             0x00010000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR16_IRQ_MSK_SHIFT            16
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR16_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR15_IRQ_MSK [15:15] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR15_IRQ_MSK_MASK             0x00008000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR15_IRQ_MSK_SHIFT            15
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR15_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR14_IRQ_MSK [14:14] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR14_IRQ_MSK_MASK             0x00004000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR14_IRQ_MSK_SHIFT            14
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR14_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR13_IRQ_MSK [13:13] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR13_IRQ_MSK_MASK             0x00002000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR13_IRQ_MSK_SHIFT            13
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR13_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR12_IRQ_MSK [12:12] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR12_IRQ_MSK_MASK             0x00001000
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR12_IRQ_MSK_SHIFT            12
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR12_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR11_IRQ_MSK [11:11] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR11_IRQ_MSK_MASK             0x00000800
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR11_IRQ_MSK_SHIFT            11
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR11_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR10_IRQ_MSK [10:10] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR10_IRQ_MSK_MASK             0x00000400
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR10_IRQ_MSK_SHIFT            10
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR10_IRQ_MSK_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR9_IRQ_MSK [09:09] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR9_IRQ_MSK_MASK              0x00000200
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR9_IRQ_MSK_SHIFT             9
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR9_IRQ_MSK_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR8_IRQ_MSK [08:08] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR8_IRQ_MSK_MASK              0x00000100
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR8_IRQ_MSK_SHIFT             8
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR8_IRQ_MSK_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR7_IRQ_MSK [07:07] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR7_IRQ_MSK_MASK              0x00000080
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR7_IRQ_MSK_SHIFT             7
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR7_IRQ_MSK_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR6_IRQ_MSK [06:06] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR6_IRQ_MSK_MASK              0x00000040
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR6_IRQ_MSK_SHIFT             6
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR6_IRQ_MSK_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR5_IRQ_MSK [05:05] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR5_IRQ_MSK_MASK              0x00000020
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR5_IRQ_MSK_SHIFT             5
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR5_IRQ_MSK_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR4_IRQ_MSK [04:04] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR4_IRQ_MSK_MASK              0x00000010
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR4_IRQ_MSK_SHIFT             4
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR4_IRQ_MSK_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR3_IRQ_MSK [03:03] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR3_IRQ_MSK_MASK              0x00000008
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR3_IRQ_MSK_SHIFT             3
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR3_IRQ_MSK_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR2_IRQ_MSK [02:02] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR2_IRQ_MSK_MASK              0x00000004
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR2_IRQ_MSK_SHIFT             2
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR2_IRQ_MSK_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR1_IRQ_MSK [01:01] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR1_IRQ_MSK_MASK              0x00000002
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR1_IRQ_MSK_SHIFT             1
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR1_IRQ_MSK_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_MSK :: CNTR0_IRQ_MSK [00:00] */
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR0_IRQ_MSK_MASK              0x00000001
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR0_IRQ_MSK_SHIFT             0
#define BCHP_HW_COUNTER_GB_IRQ_MSK_CNTR0_IRQ_MSK_DEFAULT           0x00000000

/***************************************************************************
 *IRQ_STS - Hardware Counter Irq Status Register
 ***************************************************************************/
/* HW_COUNTER_GB :: IRQ_STS :: CNTR31_IRQ_STS [31:31] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR31_IRQ_STS_MASK             0x80000000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR31_IRQ_STS_SHIFT            31
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR31_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR30_IRQ_STS [30:30] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR30_IRQ_STS_MASK             0x40000000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR30_IRQ_STS_SHIFT            30
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR30_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR29_IRQ_STS [29:29] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR29_IRQ_STS_MASK             0x20000000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR29_IRQ_STS_SHIFT            29
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR29_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR28_IRQ_STS [28:28] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR28_IRQ_STS_MASK             0x10000000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR28_IRQ_STS_SHIFT            28
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR28_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR27_IRQ_STS [27:27] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR27_IRQ_STS_MASK             0x08000000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR27_IRQ_STS_SHIFT            27
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR27_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR26_IRQ_STS [26:26] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR26_IRQ_STS_MASK             0x04000000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR26_IRQ_STS_SHIFT            26
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR26_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR25_IRQ_STS [25:25] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR25_IRQ_STS_MASK             0x02000000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR25_IRQ_STS_SHIFT            25
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR25_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR24_IRQ_STS [24:24] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR24_IRQ_STS_MASK             0x01000000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR24_IRQ_STS_SHIFT            24
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR24_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR23_IRQ_STS [23:23] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR23_IRQ_STS_MASK             0x00800000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR23_IRQ_STS_SHIFT            23
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR23_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR22_IRQ_STS [22:22] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR22_IRQ_STS_MASK             0x00400000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR22_IRQ_STS_SHIFT            22
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR22_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR21_IRQ_STS [21:21] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR21_IRQ_STS_MASK             0x00200000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR21_IRQ_STS_SHIFT            21
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR21_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR20_IRQ_STS [20:20] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR20_IRQ_STS_MASK             0x00100000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR20_IRQ_STS_SHIFT            20
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR20_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR19_IRQ_STS [19:19] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR19_IRQ_STS_MASK             0x00080000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR19_IRQ_STS_SHIFT            19
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR19_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR18_IRQ_STS [18:18] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR18_IRQ_STS_MASK             0x00040000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR18_IRQ_STS_SHIFT            18
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR18_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR17_IRQ_STS [17:17] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR17_IRQ_STS_MASK             0x00020000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR17_IRQ_STS_SHIFT            17
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR17_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR16_IRQ_STS [16:16] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR16_IRQ_STS_MASK             0x00010000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR16_IRQ_STS_SHIFT            16
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR16_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR15_IRQ_STS [15:15] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR15_IRQ_STS_MASK             0x00008000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR15_IRQ_STS_SHIFT            15
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR15_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR14_IRQ_STS [14:14] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR14_IRQ_STS_MASK             0x00004000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR14_IRQ_STS_SHIFT            14
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR14_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR13_IRQ_STS [13:13] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR13_IRQ_STS_MASK             0x00002000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR13_IRQ_STS_SHIFT            13
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR13_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR12_IRQ_STS [12:12] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR12_IRQ_STS_MASK             0x00001000
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR12_IRQ_STS_SHIFT            12
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR12_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR11_IRQ_STS [11:11] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR11_IRQ_STS_MASK             0x00000800
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR11_IRQ_STS_SHIFT            11
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR11_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR10_IRQ_STS [10:10] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR10_IRQ_STS_MASK             0x00000400
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR10_IRQ_STS_SHIFT            10
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR10_IRQ_STS_DEFAULT          0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR9_IRQ_STS [09:09] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR9_IRQ_STS_MASK              0x00000200
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR9_IRQ_STS_SHIFT             9
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR9_IRQ_STS_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR8_IRQ_STS [08:08] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR8_IRQ_STS_MASK              0x00000100
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR8_IRQ_STS_SHIFT             8
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR8_IRQ_STS_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR7_IRQ_STS [07:07] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR7_IRQ_STS_MASK              0x00000080
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR7_IRQ_STS_SHIFT             7
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR7_IRQ_STS_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR6_IRQ_STS [06:06] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR6_IRQ_STS_MASK              0x00000040
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR6_IRQ_STS_SHIFT             6
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR6_IRQ_STS_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR5_IRQ_STS [05:05] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR5_IRQ_STS_MASK              0x00000020
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR5_IRQ_STS_SHIFT             5
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR5_IRQ_STS_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR4_IRQ_STS [04:04] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR4_IRQ_STS_MASK              0x00000010
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR4_IRQ_STS_SHIFT             4
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR4_IRQ_STS_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR3_IRQ_STS [03:03] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR3_IRQ_STS_MASK              0x00000008
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR3_IRQ_STS_SHIFT             3
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR3_IRQ_STS_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR2_IRQ_STS [02:02] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR2_IRQ_STS_MASK              0x00000004
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR2_IRQ_STS_SHIFT             2
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR2_IRQ_STS_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR1_IRQ_STS [01:01] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR1_IRQ_STS_MASK              0x00000002
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR1_IRQ_STS_SHIFT             1
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR1_IRQ_STS_DEFAULT           0x00000000

/* HW_COUNTER_GB :: IRQ_STS :: CNTR0_IRQ_STS [00:00] */
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR0_IRQ_STS_MASK              0x00000001
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR0_IRQ_STS_SHIFT             0
#define BCHP_HW_COUNTER_GB_IRQ_STS_CNTR0_IRQ_STS_DEFAULT           0x00000000

#endif /* #ifndef BCHP_HW_COUNTER_GB_H__ */

/* End of File */
