/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Nov 14 03:20:39 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_WATCHDOG_GB_H__
#define BCHP_WATCHDOG_GB_H__

/***************************************************************************
 *WATCHDOG_GB
 ***************************************************************************/
#define BCHP_WATCHDOG_GB_WatchDogDefCount_CMIPS  0x104b01c0 /* CMIPS Watchdog Default Count Value Register */
#define BCHP_WATCHDOG_GB_WatchDogCtl_CMIPS       0x104b01c4 /* CMIPS Watchdog Control Register */
#define BCHP_WATCHDOG_GB_WDResetCount_CMIPS      0x104b01c8 /* CMIPS Watchdog Reset Length Register */
#define BCHP_WATCHDOG_GB_WatchDogDefCount_ZMIPS  0x104b01cc /* ZMIPS Watchdog Default Count Value Register */
#define BCHP_WATCHDOG_GB_WatchDogCtl_ZMIPS       0x104b01d0 /* ZMIPS Watchdog Control Register */
#define BCHP_WATCHDOG_GB_WDResetCount_ZMIPS      0x104b01d4 /* ZMIPS Watchdog Reset Length Register */
#define BCHP_WATCHDOG_GB_WatchDogDefCount_PMC    0x104b01d8 /* PMC Watchdog Default Count Value Register */
#define BCHP_WATCHDOG_GB_WatchDogCtl_PMC         0x104b01dc /* PMC Watchdog Control Register */
#define BCHP_WATCHDOG_GB_WDResetCount_PMC        0x104b01e0 /* PMC Watchdog Reset Length Register */

/***************************************************************************
 *WatchDogDefCount_CMIPS - CMIPS Watchdog Default Count Value Register
 ***************************************************************************/
/* WATCHDOG_GB :: WatchDogDefCount_CMIPS :: WDTimerCnt [31:00] */
#define BCHP_WATCHDOG_GB_WatchDogDefCount_CMIPS_WDTimerCnt_MASK    0xffffffff
#define BCHP_WATCHDOG_GB_WatchDogDefCount_CMIPS_WDTimerCnt_SHIFT   0
#define BCHP_WATCHDOG_GB_WatchDogDefCount_CMIPS_WDTimerCnt_DEFAULT 0x00000000

/***************************************************************************
 *WatchDogCtl_CMIPS - CMIPS Watchdog Control Register
 ***************************************************************************/
/* WATCHDOG_GB :: WatchDogCtl_CMIPS :: reserved0 [31:16] */
#define BCHP_WATCHDOG_GB_WatchDogCtl_CMIPS_reserved0_MASK          0xffff0000
#define BCHP_WATCHDOG_GB_WatchDogCtl_CMIPS_reserved0_SHIFT         16

/* WATCHDOG_GB :: WatchDogCtl_CMIPS :: Control [15:00] */
#define BCHP_WATCHDOG_GB_WatchDogCtl_CMIPS_Control_MASK            0x0000ffff
#define BCHP_WATCHDOG_GB_WatchDogCtl_CMIPS_Control_SHIFT           0
#define BCHP_WATCHDOG_GB_WatchDogCtl_CMIPS_Control_DEFAULT         0x00000000

/***************************************************************************
 *WDResetCount_CMIPS - CMIPS Watchdog Reset Length Register
 ***************************************************************************/
/* WATCHDOG_GB :: WDResetCount_CMIPS :: reserved0 [31:26] */
#define BCHP_WATCHDOG_GB_WDResetCount_CMIPS_reserved0_MASK         0xfc000000
#define BCHP_WATCHDOG_GB_WDResetCount_CMIPS_reserved0_SHIFT        26

/* WATCHDOG_GB :: WDResetCount_CMIPS :: WDRstLen [25:00] */
#define BCHP_WATCHDOG_GB_WDResetCount_CMIPS_WDRstLen_MASK          0x03ffffff
#define BCHP_WATCHDOG_GB_WDResetCount_CMIPS_WDRstLen_SHIFT         0
#define BCHP_WATCHDOG_GB_WDResetCount_CMIPS_WDRstLen_DEFAULT       0x02ffffff

/***************************************************************************
 *WatchDogDefCount_ZMIPS - ZMIPS Watchdog Default Count Value Register
 ***************************************************************************/
/* WATCHDOG_GB :: WatchDogDefCount_ZMIPS :: WDTimerCnt [31:00] */
#define BCHP_WATCHDOG_GB_WatchDogDefCount_ZMIPS_WDTimerCnt_MASK    0xffffffff
#define BCHP_WATCHDOG_GB_WatchDogDefCount_ZMIPS_WDTimerCnt_SHIFT   0
#define BCHP_WATCHDOG_GB_WatchDogDefCount_ZMIPS_WDTimerCnt_DEFAULT 0x00000000

/***************************************************************************
 *WatchDogCtl_ZMIPS - ZMIPS Watchdog Control Register
 ***************************************************************************/
/* WATCHDOG_GB :: WatchDogCtl_ZMIPS :: reserved0 [31:16] */
#define BCHP_WATCHDOG_GB_WatchDogCtl_ZMIPS_reserved0_MASK          0xffff0000
#define BCHP_WATCHDOG_GB_WatchDogCtl_ZMIPS_reserved0_SHIFT         16

/* WATCHDOG_GB :: WatchDogCtl_ZMIPS :: Control [15:00] */
#define BCHP_WATCHDOG_GB_WatchDogCtl_ZMIPS_Control_MASK            0x0000ffff
#define BCHP_WATCHDOG_GB_WatchDogCtl_ZMIPS_Control_SHIFT           0
#define BCHP_WATCHDOG_GB_WatchDogCtl_ZMIPS_Control_DEFAULT         0x00000000

/***************************************************************************
 *WDResetCount_ZMIPS - ZMIPS Watchdog Reset Length Register
 ***************************************************************************/
/* WATCHDOG_GB :: WDResetCount_ZMIPS :: reserved0 [31:26] */
#define BCHP_WATCHDOG_GB_WDResetCount_ZMIPS_reserved0_MASK         0xfc000000
#define BCHP_WATCHDOG_GB_WDResetCount_ZMIPS_reserved0_SHIFT        26

/* WATCHDOG_GB :: WDResetCount_ZMIPS :: WDRstLen [25:00] */
#define BCHP_WATCHDOG_GB_WDResetCount_ZMIPS_WDRstLen_MASK          0x03ffffff
#define BCHP_WATCHDOG_GB_WDResetCount_ZMIPS_WDRstLen_SHIFT         0
#define BCHP_WATCHDOG_GB_WDResetCount_ZMIPS_WDRstLen_DEFAULT       0x02ffffff

/***************************************************************************
 *WatchDogDefCount_PMC - PMC Watchdog Default Count Value Register
 ***************************************************************************/
/* WATCHDOG_GB :: WatchDogDefCount_PMC :: WDTimerCnt [31:00] */
#define BCHP_WATCHDOG_GB_WatchDogDefCount_PMC_WDTimerCnt_MASK      0xffffffff
#define BCHP_WATCHDOG_GB_WatchDogDefCount_PMC_WDTimerCnt_SHIFT     0
#define BCHP_WATCHDOG_GB_WatchDogDefCount_PMC_WDTimerCnt_DEFAULT   0x00000000

/***************************************************************************
 *WatchDogCtl_PMC - PMC Watchdog Control Register
 ***************************************************************************/
/* WATCHDOG_GB :: WatchDogCtl_PMC :: reserved0 [31:16] */
#define BCHP_WATCHDOG_GB_WatchDogCtl_PMC_reserved0_MASK            0xffff0000
#define BCHP_WATCHDOG_GB_WatchDogCtl_PMC_reserved0_SHIFT           16

/* WATCHDOG_GB :: WatchDogCtl_PMC :: Control [15:00] */
#define BCHP_WATCHDOG_GB_WatchDogCtl_PMC_Control_MASK              0x0000ffff
#define BCHP_WATCHDOG_GB_WatchDogCtl_PMC_Control_SHIFT             0
#define BCHP_WATCHDOG_GB_WatchDogCtl_PMC_Control_DEFAULT           0x00000000

/***************************************************************************
 *WDResetCount_PMC - PMC Watchdog Reset Length Register
 ***************************************************************************/
/* WATCHDOG_GB :: WDResetCount_PMC :: reserved0 [31:26] */
#define BCHP_WATCHDOG_GB_WDResetCount_PMC_reserved0_MASK           0xfc000000
#define BCHP_WATCHDOG_GB_WDResetCount_PMC_reserved0_SHIFT          26

/* WATCHDOG_GB :: WDResetCount_PMC :: WDRstLen [25:00] */
#define BCHP_WATCHDOG_GB_WDResetCount_PMC_WDRstLen_MASK            0x03ffffff
#define BCHP_WATCHDOG_GB_WDResetCount_PMC_WDRstLen_SHIFT           0
#define BCHP_WATCHDOG_GB_WDResetCount_PMC_WDRstLen_DEFAULT         0x02ffffff

#endif /* #ifndef BCHP_WATCHDOG_GB_H__ */

/* End of File */
