/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Nov 14 03:20:37 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_LED_PER_H__
#define BCHP_LED_PER_H__

/***************************************************************************
 *LED_PER - LED Control Registers PER
 ***************************************************************************/
#define BCHP_LED_PER_LED_INIT                    0x14e00f00 /* LED Controller Init Register */
#define BCHP_LED_PER_LED_MODE_0                  0x14e00f04 /* LED Controller Mode 0 Register */
#define BCHP_LED_PER_LED_MODE_1                  0x14e00f08 /* LED Controller Mode 1 Register */
#define BCHP_LED_PER_LED_MODE_2                  0x14e00f0c /* LED Controller Mode 2 Register */
#define BCHP_LED_PER_LED_MODE_3                  0x14e00f10 /* LED Controller Mode 3 Register */
#define BCHP_LED_PER_LED_HWDIS_0                 0x14e00f14 /* LED Controller Hardware Disable 0 Register */
#define BCHP_LED_PER_LED_HWDIS_1                 0x14e00f18 /* LED Controller Hardware Disable 1 Register */
#define BCHP_LED_PER_LED_STROBE_0                0x14e00f1c /* LED Controller Strobe 0 Register */
#define BCHP_LED_PER_LED_STROBE_1                0x14e00f20 /* LED Controller Strobe 1 Register */
#define BCHP_LED_PER_LED_MASK                    0x14e00f24 /* LED Controller HW Activity Mask Register */
#define BCHP_LED_PER_LED_READBACK_0              0x14e00f28 /* LED Controller Read Back 0 Register */
#define BCHP_LED_PER_LED_READBACK_1              0x14e00f2c /* LED Controller Read Back 1 Register */

/***************************************************************************
 *LED_INIT - LED Controller Init Register
 ***************************************************************************/
/* LED_PER :: LED_INIT :: LED_TEST [31:31] */
#define BCHP_LED_PER_LED_INIT_LED_TEST_MASK                        0x80000000
#define BCHP_LED_PER_LED_INIT_LED_TEST_SHIFT                       31
#define BCHP_LED_PER_LED_INIT_LED_TEST_DEFAULT                     0x00000000

/* LED_PER :: LED_INIT :: SHIFT_TEST [30:30] */
#define BCHP_LED_PER_LED_INIT_SHIFT_TEST_MASK                      0x40000000
#define BCHP_LED_PER_LED_INIT_SHIFT_TEST_SHIFT                     30
#define BCHP_LED_PER_LED_INIT_SHIFT_TEST_DEFAULT                   0x00000000

/* LED_PER :: LED_INIT :: reserved0 [29:16] */
#define BCHP_LED_PER_LED_INIT_reserved0_MASK                       0x3fff0000
#define BCHP_LED_PER_LED_INIT_reserved0_SHIFT                      16

/* LED_PER :: LED_INIT :: SERIAL_LED_DATA_PPOL [15:15] */
#define BCHP_LED_PER_LED_INIT_SERIAL_LED_DATA_PPOL_MASK            0x00008000
#define BCHP_LED_PER_LED_INIT_SERIAL_LED_DATA_PPOL_SHIFT           15
#define BCHP_LED_PER_LED_INIT_SERIAL_LED_DATA_PPOL_DEFAULT         0x00000000

/* LED_PER :: LED_INIT :: SERIAL_LED_CLK_NPOL [14:14] */
#define BCHP_LED_PER_LED_INIT_SERIAL_LED_CLK_NPOL_MASK             0x00004000
#define BCHP_LED_PER_LED_INIT_SERIAL_LED_CLK_NPOL_SHIFT            14
#define BCHP_LED_PER_LED_INIT_SERIAL_LED_CLK_NPOL_DEFAULT          0x00000000

/* LED_PER :: LED_INIT :: SERIAL_LED_MUX_SEL [13:13] */
#define BCHP_LED_PER_LED_INIT_SERIAL_LED_MUX_SEL_MASK              0x00002000
#define BCHP_LED_PER_LED_INIT_SERIAL_LED_MUX_SEL_SHIFT             13
#define BCHP_LED_PER_LED_INIT_SERIAL_LED_MUX_SEL_DEFAULT           0x00000000

/* LED_PER :: LED_INIT :: SERIAL_LED_EN [12:12] */
#define BCHP_LED_PER_LED_INIT_SERIAL_LED_EN_MASK                   0x00001000
#define BCHP_LED_PER_LED_INIT_SERIAL_LED_EN_SHIFT                  12
#define BCHP_LED_PER_LED_INIT_SERIAL_LED_EN_DEFAULT                0x00000000

/* LED_PER :: LED_INIT :: FAST_INTV [11:06] */
#define BCHP_LED_PER_LED_INIT_FAST_INTV_MASK                       0x00000fc0
#define BCHP_LED_PER_LED_INIT_FAST_INTV_SHIFT                      6
#define BCHP_LED_PER_LED_INIT_FAST_INTV_DEFAULT                    0x00000000

/* LED_PER :: LED_INIT :: SLOW_INTV [05:00] */
#define BCHP_LED_PER_LED_INIT_SLOW_INTV_MASK                       0x0000003f
#define BCHP_LED_PER_LED_INIT_SLOW_INTV_SHIFT                      0
#define BCHP_LED_PER_LED_INIT_SLOW_INTV_DEFAULT                    0x00000000

/***************************************************************************
 *LED_MODE_0 - LED Controller Mode 0 Register
 ***************************************************************************/
/* LED_PER :: LED_MODE_0 :: reserved0 [31:16] */
#define BCHP_LED_PER_LED_MODE_0_reserved0_MASK                     0xffff0000
#define BCHP_LED_PER_LED_MODE_0_reserved0_SHIFT                    16

/* LED_PER :: LED_MODE_0 :: LED_7_MODE [15:14] */
#define BCHP_LED_PER_LED_MODE_0_LED_7_MODE_MASK                    0x0000c000
#define BCHP_LED_PER_LED_MODE_0_LED_7_MODE_SHIFT                   14
#define BCHP_LED_PER_LED_MODE_0_LED_7_MODE_DEFAULT                 0x00000000
#define BCHP_LED_PER_LED_MODE_0_LED_7_MODE_OFF                     0
#define BCHP_LED_PER_LED_MODE_0_LED_7_MODE_BLINK                   1
#define BCHP_LED_PER_LED_MODE_0_LED_7_MODE_FLASH                   2
#define BCHP_LED_PER_LED_MODE_0_LED_7_MODE_ON                      3

/* LED_PER :: LED_MODE_0 :: LED_6_MODE [13:12] */
#define BCHP_LED_PER_LED_MODE_0_LED_6_MODE_MASK                    0x00003000
#define BCHP_LED_PER_LED_MODE_0_LED_6_MODE_SHIFT                   12
#define BCHP_LED_PER_LED_MODE_0_LED_6_MODE_DEFAULT                 0x00000000
#define BCHP_LED_PER_LED_MODE_0_LED_6_MODE_OFF                     0
#define BCHP_LED_PER_LED_MODE_0_LED_6_MODE_BLINK                   1
#define BCHP_LED_PER_LED_MODE_0_LED_6_MODE_FLASH                   2
#define BCHP_LED_PER_LED_MODE_0_LED_6_MODE_ON                      3

/* LED_PER :: LED_MODE_0 :: LED_5_MODE [11:10] */
#define BCHP_LED_PER_LED_MODE_0_LED_5_MODE_MASK                    0x00000c00
#define BCHP_LED_PER_LED_MODE_0_LED_5_MODE_SHIFT                   10
#define BCHP_LED_PER_LED_MODE_0_LED_5_MODE_DEFAULT                 0x00000000
#define BCHP_LED_PER_LED_MODE_0_LED_5_MODE_OFF                     0
#define BCHP_LED_PER_LED_MODE_0_LED_5_MODE_BLINK                   1
#define BCHP_LED_PER_LED_MODE_0_LED_5_MODE_FLASH                   2
#define BCHP_LED_PER_LED_MODE_0_LED_5_MODE_ON                      3

/* LED_PER :: LED_MODE_0 :: LED_4_MODE [09:08] */
#define BCHP_LED_PER_LED_MODE_0_LED_4_MODE_MASK                    0x00000300
#define BCHP_LED_PER_LED_MODE_0_LED_4_MODE_SHIFT                   8
#define BCHP_LED_PER_LED_MODE_0_LED_4_MODE_DEFAULT                 0x00000000
#define BCHP_LED_PER_LED_MODE_0_LED_4_MODE_OFF                     0
#define BCHP_LED_PER_LED_MODE_0_LED_4_MODE_BLINK                   1
#define BCHP_LED_PER_LED_MODE_0_LED_4_MODE_FLASH                   2
#define BCHP_LED_PER_LED_MODE_0_LED_4_MODE_ON                      3

/* LED_PER :: LED_MODE_0 :: LED_3_MODE [07:06] */
#define BCHP_LED_PER_LED_MODE_0_LED_3_MODE_MASK                    0x000000c0
#define BCHP_LED_PER_LED_MODE_0_LED_3_MODE_SHIFT                   6
#define BCHP_LED_PER_LED_MODE_0_LED_3_MODE_DEFAULT                 0x00000000
#define BCHP_LED_PER_LED_MODE_0_LED_3_MODE_OFF                     0
#define BCHP_LED_PER_LED_MODE_0_LED_3_MODE_BLINK                   1
#define BCHP_LED_PER_LED_MODE_0_LED_3_MODE_FLASH                   2
#define BCHP_LED_PER_LED_MODE_0_LED_3_MODE_ON                      3

/* LED_PER :: LED_MODE_0 :: LED_2_MODE [05:04] */
#define BCHP_LED_PER_LED_MODE_0_LED_2_MODE_MASK                    0x00000030
#define BCHP_LED_PER_LED_MODE_0_LED_2_MODE_SHIFT                   4
#define BCHP_LED_PER_LED_MODE_0_LED_2_MODE_DEFAULT                 0x00000000
#define BCHP_LED_PER_LED_MODE_0_LED_2_MODE_OFF                     0
#define BCHP_LED_PER_LED_MODE_0_LED_2_MODE_BLINK                   1
#define BCHP_LED_PER_LED_MODE_0_LED_2_MODE_FLASH                   2
#define BCHP_LED_PER_LED_MODE_0_LED_2_MODE_ON                      3

/* LED_PER :: LED_MODE_0 :: LED_1_MODE [03:02] */
#define BCHP_LED_PER_LED_MODE_0_LED_1_MODE_MASK                    0x0000000c
#define BCHP_LED_PER_LED_MODE_0_LED_1_MODE_SHIFT                   2
#define BCHP_LED_PER_LED_MODE_0_LED_1_MODE_DEFAULT                 0x00000000
#define BCHP_LED_PER_LED_MODE_0_LED_1_MODE_OFF                     0
#define BCHP_LED_PER_LED_MODE_0_LED_1_MODE_BLINK                   1
#define BCHP_LED_PER_LED_MODE_0_LED_1_MODE_FLASH                   2
#define BCHP_LED_PER_LED_MODE_0_LED_1_MODE_ON                      3

/* LED_PER :: LED_MODE_0 :: LED_0_MODE [01:00] */
#define BCHP_LED_PER_LED_MODE_0_LED_0_MODE_MASK                    0x00000003
#define BCHP_LED_PER_LED_MODE_0_LED_0_MODE_SHIFT                   0
#define BCHP_LED_PER_LED_MODE_0_LED_0_MODE_DEFAULT                 0x00000000
#define BCHP_LED_PER_LED_MODE_0_LED_0_MODE_OFF                     0
#define BCHP_LED_PER_LED_MODE_0_LED_0_MODE_BLINK                   1
#define BCHP_LED_PER_LED_MODE_0_LED_0_MODE_FLASH                   2
#define BCHP_LED_PER_LED_MODE_0_LED_0_MODE_ON                      3

/***************************************************************************
 *LED_MODE_1 - LED Controller Mode 1 Register
 ***************************************************************************/
/* LED_PER :: LED_MODE_1 :: LED_23_MODE [31:30] */
#define BCHP_LED_PER_LED_MODE_1_LED_23_MODE_MASK                   0xc0000000
#define BCHP_LED_PER_LED_MODE_1_LED_23_MODE_SHIFT                  30
#define BCHP_LED_PER_LED_MODE_1_LED_23_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_1_LED_23_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_1_LED_23_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_1_LED_23_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_1_LED_23_MODE_ON                     3

/* LED_PER :: LED_MODE_1 :: LED_22_MODE [29:28] */
#define BCHP_LED_PER_LED_MODE_1_LED_22_MODE_MASK                   0x30000000
#define BCHP_LED_PER_LED_MODE_1_LED_22_MODE_SHIFT                  28
#define BCHP_LED_PER_LED_MODE_1_LED_22_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_1_LED_22_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_1_LED_22_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_1_LED_22_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_1_LED_22_MODE_ON                     3

/* LED_PER :: LED_MODE_1 :: LED_21_MODE [27:26] */
#define BCHP_LED_PER_LED_MODE_1_LED_21_MODE_MASK                   0x0c000000
#define BCHP_LED_PER_LED_MODE_1_LED_21_MODE_SHIFT                  26
#define BCHP_LED_PER_LED_MODE_1_LED_21_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_1_LED_21_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_1_LED_21_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_1_LED_21_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_1_LED_21_MODE_ON                     3

/* LED_PER :: LED_MODE_1 :: LED_20_MODE [25:24] */
#define BCHP_LED_PER_LED_MODE_1_LED_20_MODE_MASK                   0x03000000
#define BCHP_LED_PER_LED_MODE_1_LED_20_MODE_SHIFT                  24
#define BCHP_LED_PER_LED_MODE_1_LED_20_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_1_LED_20_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_1_LED_20_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_1_LED_20_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_1_LED_20_MODE_ON                     3

/* LED_PER :: LED_MODE_1 :: LED_19_MODE [23:22] */
#define BCHP_LED_PER_LED_MODE_1_LED_19_MODE_MASK                   0x00c00000
#define BCHP_LED_PER_LED_MODE_1_LED_19_MODE_SHIFT                  22
#define BCHP_LED_PER_LED_MODE_1_LED_19_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_1_LED_19_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_1_LED_19_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_1_LED_19_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_1_LED_19_MODE_ON                     3

/* LED_PER :: LED_MODE_1 :: LED_18_MODE [21:20] */
#define BCHP_LED_PER_LED_MODE_1_LED_18_MODE_MASK                   0x00300000
#define BCHP_LED_PER_LED_MODE_1_LED_18_MODE_SHIFT                  20
#define BCHP_LED_PER_LED_MODE_1_LED_18_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_1_LED_18_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_1_LED_18_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_1_LED_18_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_1_LED_18_MODE_ON                     3

/* LED_PER :: LED_MODE_1 :: LED_17_MODE [19:18] */
#define BCHP_LED_PER_LED_MODE_1_LED_17_MODE_MASK                   0x000c0000
#define BCHP_LED_PER_LED_MODE_1_LED_17_MODE_SHIFT                  18
#define BCHP_LED_PER_LED_MODE_1_LED_17_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_1_LED_17_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_1_LED_17_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_1_LED_17_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_1_LED_17_MODE_ON                     3

/* LED_PER :: LED_MODE_1 :: LED_16_MODE [17:16] */
#define BCHP_LED_PER_LED_MODE_1_LED_16_MODE_MASK                   0x00030000
#define BCHP_LED_PER_LED_MODE_1_LED_16_MODE_SHIFT                  16
#define BCHP_LED_PER_LED_MODE_1_LED_16_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_1_LED_16_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_1_LED_16_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_1_LED_16_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_1_LED_16_MODE_ON                     3

/* LED_PER :: LED_MODE_1 :: LED_15_MODE [15:14] */
#define BCHP_LED_PER_LED_MODE_1_LED_15_MODE_MASK                   0x0000c000
#define BCHP_LED_PER_LED_MODE_1_LED_15_MODE_SHIFT                  14
#define BCHP_LED_PER_LED_MODE_1_LED_15_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_1_LED_15_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_1_LED_15_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_1_LED_15_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_1_LED_15_MODE_ON                     3

/* LED_PER :: LED_MODE_1 :: LED_14_MODE [13:12] */
#define BCHP_LED_PER_LED_MODE_1_LED_14_MODE_MASK                   0x00003000
#define BCHP_LED_PER_LED_MODE_1_LED_14_MODE_SHIFT                  12
#define BCHP_LED_PER_LED_MODE_1_LED_14_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_1_LED_14_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_1_LED_14_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_1_LED_14_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_1_LED_14_MODE_ON                     3

/* LED_PER :: LED_MODE_1 :: LED_13_MODE [11:10] */
#define BCHP_LED_PER_LED_MODE_1_LED_13_MODE_MASK                   0x00000c00
#define BCHP_LED_PER_LED_MODE_1_LED_13_MODE_SHIFT                  10
#define BCHP_LED_PER_LED_MODE_1_LED_13_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_1_LED_13_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_1_LED_13_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_1_LED_13_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_1_LED_13_MODE_ON                     3

/* LED_PER :: LED_MODE_1 :: LED_12_MODE [09:08] */
#define BCHP_LED_PER_LED_MODE_1_LED_12_MODE_MASK                   0x00000300
#define BCHP_LED_PER_LED_MODE_1_LED_12_MODE_SHIFT                  8
#define BCHP_LED_PER_LED_MODE_1_LED_12_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_1_LED_12_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_1_LED_12_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_1_LED_12_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_1_LED_12_MODE_ON                     3

/* LED_PER :: LED_MODE_1 :: LED_11_MODE [07:06] */
#define BCHP_LED_PER_LED_MODE_1_LED_11_MODE_MASK                   0x000000c0
#define BCHP_LED_PER_LED_MODE_1_LED_11_MODE_SHIFT                  6
#define BCHP_LED_PER_LED_MODE_1_LED_11_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_1_LED_11_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_1_LED_11_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_1_LED_11_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_1_LED_11_MODE_ON                     3

/* LED_PER :: LED_MODE_1 :: LED_10_MODE [05:04] */
#define BCHP_LED_PER_LED_MODE_1_LED_10_MODE_MASK                   0x00000030
#define BCHP_LED_PER_LED_MODE_1_LED_10_MODE_SHIFT                  4
#define BCHP_LED_PER_LED_MODE_1_LED_10_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_1_LED_10_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_1_LED_10_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_1_LED_10_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_1_LED_10_MODE_ON                     3

/* LED_PER :: LED_MODE_1 :: LED_9_MODE [03:02] */
#define BCHP_LED_PER_LED_MODE_1_LED_9_MODE_MASK                    0x0000000c
#define BCHP_LED_PER_LED_MODE_1_LED_9_MODE_SHIFT                   2
#define BCHP_LED_PER_LED_MODE_1_LED_9_MODE_DEFAULT                 0x00000000
#define BCHP_LED_PER_LED_MODE_1_LED_9_MODE_OFF                     0
#define BCHP_LED_PER_LED_MODE_1_LED_9_MODE_BLINK                   1
#define BCHP_LED_PER_LED_MODE_1_LED_9_MODE_FLASH                   2
#define BCHP_LED_PER_LED_MODE_1_LED_9_MODE_ON                      3

/* LED_PER :: LED_MODE_1 :: LED_8_MODE [01:00] */
#define BCHP_LED_PER_LED_MODE_1_LED_8_MODE_MASK                    0x00000003
#define BCHP_LED_PER_LED_MODE_1_LED_8_MODE_SHIFT                   0
#define BCHP_LED_PER_LED_MODE_1_LED_8_MODE_DEFAULT                 0x00000000
#define BCHP_LED_PER_LED_MODE_1_LED_8_MODE_OFF                     0
#define BCHP_LED_PER_LED_MODE_1_LED_8_MODE_BLINK                   1
#define BCHP_LED_PER_LED_MODE_1_LED_8_MODE_FLASH                   2
#define BCHP_LED_PER_LED_MODE_1_LED_8_MODE_ON                      3

/***************************************************************************
 *LED_MODE_2 - LED Controller Mode 2 Register
 ***************************************************************************/
/* LED_PER :: LED_MODE_2 :: LED_39_MODE [31:30] */
#define BCHP_LED_PER_LED_MODE_2_LED_39_MODE_MASK                   0xc0000000
#define BCHP_LED_PER_LED_MODE_2_LED_39_MODE_SHIFT                  30
#define BCHP_LED_PER_LED_MODE_2_LED_39_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_2_LED_39_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_2_LED_39_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_2_LED_39_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_2_LED_39_MODE_ON                     3

/* LED_PER :: LED_MODE_2 :: LED_38_MODE [29:28] */
#define BCHP_LED_PER_LED_MODE_2_LED_38_MODE_MASK                   0x30000000
#define BCHP_LED_PER_LED_MODE_2_LED_38_MODE_SHIFT                  28
#define BCHP_LED_PER_LED_MODE_2_LED_38_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_2_LED_38_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_2_LED_38_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_2_LED_38_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_2_LED_38_MODE_ON                     3

/* LED_PER :: LED_MODE_2 :: LED_37_MODE [27:26] */
#define BCHP_LED_PER_LED_MODE_2_LED_37_MODE_MASK                   0x0c000000
#define BCHP_LED_PER_LED_MODE_2_LED_37_MODE_SHIFT                  26
#define BCHP_LED_PER_LED_MODE_2_LED_37_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_2_LED_37_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_2_LED_37_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_2_LED_37_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_2_LED_37_MODE_ON                     3

/* LED_PER :: LED_MODE_2 :: LED_36_MODE [25:24] */
#define BCHP_LED_PER_LED_MODE_2_LED_36_MODE_MASK                   0x03000000
#define BCHP_LED_PER_LED_MODE_2_LED_36_MODE_SHIFT                  24
#define BCHP_LED_PER_LED_MODE_2_LED_36_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_2_LED_36_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_2_LED_36_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_2_LED_36_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_2_LED_36_MODE_ON                     3

/* LED_PER :: LED_MODE_2 :: LED_35_MODE [23:22] */
#define BCHP_LED_PER_LED_MODE_2_LED_35_MODE_MASK                   0x00c00000
#define BCHP_LED_PER_LED_MODE_2_LED_35_MODE_SHIFT                  22
#define BCHP_LED_PER_LED_MODE_2_LED_35_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_2_LED_35_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_2_LED_35_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_2_LED_35_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_2_LED_35_MODE_ON                     3

/* LED_PER :: LED_MODE_2 :: LED_34_MODE [21:20] */
#define BCHP_LED_PER_LED_MODE_2_LED_34_MODE_MASK                   0x00300000
#define BCHP_LED_PER_LED_MODE_2_LED_34_MODE_SHIFT                  20
#define BCHP_LED_PER_LED_MODE_2_LED_34_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_2_LED_34_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_2_LED_34_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_2_LED_34_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_2_LED_34_MODE_ON                     3

/* LED_PER :: LED_MODE_2 :: LED_33_MODE [19:18] */
#define BCHP_LED_PER_LED_MODE_2_LED_33_MODE_MASK                   0x000c0000
#define BCHP_LED_PER_LED_MODE_2_LED_33_MODE_SHIFT                  18
#define BCHP_LED_PER_LED_MODE_2_LED_33_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_2_LED_33_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_2_LED_33_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_2_LED_33_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_2_LED_33_MODE_ON                     3

/* LED_PER :: LED_MODE_2 :: LED_32_MODE [17:16] */
#define BCHP_LED_PER_LED_MODE_2_LED_32_MODE_MASK                   0x00030000
#define BCHP_LED_PER_LED_MODE_2_LED_32_MODE_SHIFT                  16
#define BCHP_LED_PER_LED_MODE_2_LED_32_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_2_LED_32_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_2_LED_32_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_2_LED_32_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_2_LED_32_MODE_ON                     3

/* LED_PER :: LED_MODE_2 :: LED_31_MODE [15:14] */
#define BCHP_LED_PER_LED_MODE_2_LED_31_MODE_MASK                   0x0000c000
#define BCHP_LED_PER_LED_MODE_2_LED_31_MODE_SHIFT                  14
#define BCHP_LED_PER_LED_MODE_2_LED_31_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_2_LED_31_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_2_LED_31_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_2_LED_31_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_2_LED_31_MODE_ON                     3

/* LED_PER :: LED_MODE_2 :: LED_30_MODE [13:12] */
#define BCHP_LED_PER_LED_MODE_2_LED_30_MODE_MASK                   0x00003000
#define BCHP_LED_PER_LED_MODE_2_LED_30_MODE_SHIFT                  12
#define BCHP_LED_PER_LED_MODE_2_LED_30_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_2_LED_30_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_2_LED_30_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_2_LED_30_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_2_LED_30_MODE_ON                     3

/* LED_PER :: LED_MODE_2 :: LED_29_MODE [11:10] */
#define BCHP_LED_PER_LED_MODE_2_LED_29_MODE_MASK                   0x00000c00
#define BCHP_LED_PER_LED_MODE_2_LED_29_MODE_SHIFT                  10
#define BCHP_LED_PER_LED_MODE_2_LED_29_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_2_LED_29_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_2_LED_29_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_2_LED_29_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_2_LED_29_MODE_ON                     3

/* LED_PER :: LED_MODE_2 :: LED_28_MODE [09:08] */
#define BCHP_LED_PER_LED_MODE_2_LED_28_MODE_MASK                   0x00000300
#define BCHP_LED_PER_LED_MODE_2_LED_28_MODE_SHIFT                  8
#define BCHP_LED_PER_LED_MODE_2_LED_28_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_2_LED_28_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_2_LED_28_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_2_LED_28_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_2_LED_28_MODE_ON                     3

/* LED_PER :: LED_MODE_2 :: LED_27_MODE [07:06] */
#define BCHP_LED_PER_LED_MODE_2_LED_27_MODE_MASK                   0x000000c0
#define BCHP_LED_PER_LED_MODE_2_LED_27_MODE_SHIFT                  6
#define BCHP_LED_PER_LED_MODE_2_LED_27_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_2_LED_27_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_2_LED_27_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_2_LED_27_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_2_LED_27_MODE_ON                     3

/* LED_PER :: LED_MODE_2 :: LED_26_MODE [05:04] */
#define BCHP_LED_PER_LED_MODE_2_LED_26_MODE_MASK                   0x00000030
#define BCHP_LED_PER_LED_MODE_2_LED_26_MODE_SHIFT                  4
#define BCHP_LED_PER_LED_MODE_2_LED_26_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_2_LED_26_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_2_LED_26_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_2_LED_26_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_2_LED_26_MODE_ON                     3

/* LED_PER :: LED_MODE_2 :: LED_25_MODE [03:02] */
#define BCHP_LED_PER_LED_MODE_2_LED_25_MODE_MASK                   0x0000000c
#define BCHP_LED_PER_LED_MODE_2_LED_25_MODE_SHIFT                  2
#define BCHP_LED_PER_LED_MODE_2_LED_25_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_2_LED_25_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_2_LED_25_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_2_LED_25_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_2_LED_25_MODE_ON                     3

/* LED_PER :: LED_MODE_2 :: LED_24_MODE [01:00] */
#define BCHP_LED_PER_LED_MODE_2_LED_24_MODE_MASK                   0x00000003
#define BCHP_LED_PER_LED_MODE_2_LED_24_MODE_SHIFT                  0
#define BCHP_LED_PER_LED_MODE_2_LED_24_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_2_LED_24_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_2_LED_24_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_2_LED_24_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_2_LED_24_MODE_ON                     3

/***************************************************************************
 *LED_MODE_3 - LED Controller Mode 3 Register
 ***************************************************************************/
/* LED_PER :: LED_MODE_3 :: reserved0 [31:08] */
#define BCHP_LED_PER_LED_MODE_3_reserved0_MASK                     0xffffff00
#define BCHP_LED_PER_LED_MODE_3_reserved0_SHIFT                    8

/* LED_PER :: LED_MODE_3 :: LED_43_MODE [07:06] */
#define BCHP_LED_PER_LED_MODE_3_LED_43_MODE_MASK                   0x000000c0
#define BCHP_LED_PER_LED_MODE_3_LED_43_MODE_SHIFT                  6
#define BCHP_LED_PER_LED_MODE_3_LED_43_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_3_LED_43_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_3_LED_43_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_3_LED_43_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_3_LED_43_MODE_ON                     3

/* LED_PER :: LED_MODE_3 :: LED_42_MODE [05:04] */
#define BCHP_LED_PER_LED_MODE_3_LED_42_MODE_MASK                   0x00000030
#define BCHP_LED_PER_LED_MODE_3_LED_42_MODE_SHIFT                  4
#define BCHP_LED_PER_LED_MODE_3_LED_42_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_3_LED_42_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_3_LED_42_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_3_LED_42_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_3_LED_42_MODE_ON                     3

/* LED_PER :: LED_MODE_3 :: LED_41_MODE [03:02] */
#define BCHP_LED_PER_LED_MODE_3_LED_41_MODE_MASK                   0x0000000c
#define BCHP_LED_PER_LED_MODE_3_LED_41_MODE_SHIFT                  2
#define BCHP_LED_PER_LED_MODE_3_LED_41_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_3_LED_41_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_3_LED_41_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_3_LED_41_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_3_LED_41_MODE_ON                     3

/* LED_PER :: LED_MODE_3 :: LED_40_MODE [01:00] */
#define BCHP_LED_PER_LED_MODE_3_LED_40_MODE_MASK                   0x00000003
#define BCHP_LED_PER_LED_MODE_3_LED_40_MODE_SHIFT                  0
#define BCHP_LED_PER_LED_MODE_3_LED_40_MODE_DEFAULT                0x00000000
#define BCHP_LED_PER_LED_MODE_3_LED_40_MODE_OFF                    0
#define BCHP_LED_PER_LED_MODE_3_LED_40_MODE_BLINK                  1
#define BCHP_LED_PER_LED_MODE_3_LED_40_MODE_FLASH                  2
#define BCHP_LED_PER_LED_MODE_3_LED_40_MODE_ON                     3

/***************************************************************************
 *LED_HWDIS_0 - LED Controller Hardware Disable 0 Register
 ***************************************************************************/
/* LED_PER :: LED_HWDIS_0 :: LED_31_HWDIS [31:31] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_31_HWDIS_MASK                 0x80000000
#define BCHP_LED_PER_LED_HWDIS_0_LED_31_HWDIS_SHIFT                31
#define BCHP_LED_PER_LED_HWDIS_0_LED_31_HWDIS_DEFAULT              0x00000000

/* LED_PER :: LED_HWDIS_0 :: LED_30_HWDIS [30:30] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_30_HWDIS_MASK                 0x40000000
#define BCHP_LED_PER_LED_HWDIS_0_LED_30_HWDIS_SHIFT                30

/* LED_PER :: LED_HWDIS_0 :: LED_29_HWDIS [29:29] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_29_HWDIS_MASK                 0x20000000
#define BCHP_LED_PER_LED_HWDIS_0_LED_29_HWDIS_SHIFT                29

/* LED_PER :: LED_HWDIS_0 :: LED_28_HWDIS [28:28] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_28_HWDIS_MASK                 0x10000000
#define BCHP_LED_PER_LED_HWDIS_0_LED_28_HWDIS_SHIFT                28

/* LED_PER :: LED_HWDIS_0 :: LED_27_HWDIS [27:27] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_27_HWDIS_MASK                 0x08000000
#define BCHP_LED_PER_LED_HWDIS_0_LED_27_HWDIS_SHIFT                27

/* LED_PER :: LED_HWDIS_0 :: LED_26_HWDIS [26:26] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_26_HWDIS_MASK                 0x04000000
#define BCHP_LED_PER_LED_HWDIS_0_LED_26_HWDIS_SHIFT                26

/* LED_PER :: LED_HWDIS_0 :: LED_25_HWDIS [25:25] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_25_HWDIS_MASK                 0x02000000
#define BCHP_LED_PER_LED_HWDIS_0_LED_25_HWDIS_SHIFT                25

/* LED_PER :: LED_HWDIS_0 :: LED_24_HWDIS [24:24] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_24_HWDIS_MASK                 0x01000000
#define BCHP_LED_PER_LED_HWDIS_0_LED_24_HWDIS_SHIFT                24

/* LED_PER :: LED_HWDIS_0 :: LED_23_HWDIS [23:23] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_23_HWDIS_MASK                 0x00800000
#define BCHP_LED_PER_LED_HWDIS_0_LED_23_HWDIS_SHIFT                23

/* LED_PER :: LED_HWDIS_0 :: LED_22_HWDIS [22:22] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_22_HWDIS_MASK                 0x00400000
#define BCHP_LED_PER_LED_HWDIS_0_LED_22_HWDIS_SHIFT                22

/* LED_PER :: LED_HWDIS_0 :: LED_21_HWDIS [21:21] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_21_HWDIS_MASK                 0x00200000
#define BCHP_LED_PER_LED_HWDIS_0_LED_21_HWDIS_SHIFT                21

/* LED_PER :: LED_HWDIS_0 :: LED_20_HWDIS [20:20] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_20_HWDIS_MASK                 0x00100000
#define BCHP_LED_PER_LED_HWDIS_0_LED_20_HWDIS_SHIFT                20

/* LED_PER :: LED_HWDIS_0 :: LED_19_HWDIS [19:19] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_19_HWDIS_MASK                 0x00080000
#define BCHP_LED_PER_LED_HWDIS_0_LED_19_HWDIS_SHIFT                19

/* LED_PER :: LED_HWDIS_0 :: LED_18_HWDIS [18:18] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_18_HWDIS_MASK                 0x00040000
#define BCHP_LED_PER_LED_HWDIS_0_LED_18_HWDIS_SHIFT                18

/* LED_PER :: LED_HWDIS_0 :: LED_17_HWDIS [17:17] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_17_HWDIS_MASK                 0x00020000
#define BCHP_LED_PER_LED_HWDIS_0_LED_17_HWDIS_SHIFT                17

/* LED_PER :: LED_HWDIS_0 :: LED_16_HWDIS [16:16] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_16_HWDIS_MASK                 0x00010000
#define BCHP_LED_PER_LED_HWDIS_0_LED_16_HWDIS_SHIFT                16

/* LED_PER :: LED_HWDIS_0 :: LED_15_HWDIS [15:15] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_15_HWDIS_MASK                 0x00008000
#define BCHP_LED_PER_LED_HWDIS_0_LED_15_HWDIS_SHIFT                15

/* LED_PER :: LED_HWDIS_0 :: LED_14_HWDIS [14:14] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_14_HWDIS_MASK                 0x00004000
#define BCHP_LED_PER_LED_HWDIS_0_LED_14_HWDIS_SHIFT                14

/* LED_PER :: LED_HWDIS_0 :: LED_13_HWDIS [13:13] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_13_HWDIS_MASK                 0x00002000
#define BCHP_LED_PER_LED_HWDIS_0_LED_13_HWDIS_SHIFT                13

/* LED_PER :: LED_HWDIS_0 :: LED_12_HWDIS [12:12] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_12_HWDIS_MASK                 0x00001000
#define BCHP_LED_PER_LED_HWDIS_0_LED_12_HWDIS_SHIFT                12

/* LED_PER :: LED_HWDIS_0 :: LED_11_HWDIS [11:11] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_11_HWDIS_MASK                 0x00000800
#define BCHP_LED_PER_LED_HWDIS_0_LED_11_HWDIS_SHIFT                11

/* LED_PER :: LED_HWDIS_0 :: LED_10_HWDIS [10:10] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_10_HWDIS_MASK                 0x00000400
#define BCHP_LED_PER_LED_HWDIS_0_LED_10_HWDIS_SHIFT                10

/* LED_PER :: LED_HWDIS_0 :: LED_9_HWDIS [09:09] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_9_HWDIS_MASK                  0x00000200
#define BCHP_LED_PER_LED_HWDIS_0_LED_9_HWDIS_SHIFT                 9

/* LED_PER :: LED_HWDIS_0 :: LED_8_HWDIS [08:08] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_8_HWDIS_MASK                  0x00000100
#define BCHP_LED_PER_LED_HWDIS_0_LED_8_HWDIS_SHIFT                 8

/* LED_PER :: LED_HWDIS_0 :: LED_7_HWDIS [07:07] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_7_HWDIS_MASK                  0x00000080
#define BCHP_LED_PER_LED_HWDIS_0_LED_7_HWDIS_SHIFT                 7

/* LED_PER :: LED_HWDIS_0 :: LED_6_HWDIS [06:06] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_6_HWDIS_MASK                  0x00000040
#define BCHP_LED_PER_LED_HWDIS_0_LED_6_HWDIS_SHIFT                 6

/* LED_PER :: LED_HWDIS_0 :: LED_5_HWDIS [05:05] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_5_HWDIS_MASK                  0x00000020
#define BCHP_LED_PER_LED_HWDIS_0_LED_5_HWDIS_SHIFT                 5

/* LED_PER :: LED_HWDIS_0 :: LED_4_HWDIS [04:04] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_4_HWDIS_MASK                  0x00000010
#define BCHP_LED_PER_LED_HWDIS_0_LED_4_HWDIS_SHIFT                 4

/* LED_PER :: LED_HWDIS_0 :: LED_3_HWDIS [03:03] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_3_HWDIS_MASK                  0x00000008
#define BCHP_LED_PER_LED_HWDIS_0_LED_3_HWDIS_SHIFT                 3

/* LED_PER :: LED_HWDIS_0 :: LED_2_HWDIS [02:02] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_2_HWDIS_MASK                  0x00000004
#define BCHP_LED_PER_LED_HWDIS_0_LED_2_HWDIS_SHIFT                 2

/* LED_PER :: LED_HWDIS_0 :: LED_1_HWDIS [01:01] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_1_HWDIS_MASK                  0x00000002
#define BCHP_LED_PER_LED_HWDIS_0_LED_1_HWDIS_SHIFT                 1

/* LED_PER :: LED_HWDIS_0 :: LED_0_HWDIS [00:00] */
#define BCHP_LED_PER_LED_HWDIS_0_LED_0_HWDIS_MASK                  0x00000001
#define BCHP_LED_PER_LED_HWDIS_0_LED_0_HWDIS_SHIFT                 0

/***************************************************************************
 *LED_HWDIS_1 - LED Controller Hardware Disable 1 Register
 ***************************************************************************/
/* LED_PER :: LED_HWDIS_1 :: reserved0 [31:12] */
#define BCHP_LED_PER_LED_HWDIS_1_reserved0_MASK                    0xfffff000
#define BCHP_LED_PER_LED_HWDIS_1_reserved0_SHIFT                   12

/* LED_PER :: LED_HWDIS_1 :: LED_43_HWDIS [11:11] */
#define BCHP_LED_PER_LED_HWDIS_1_LED_43_HWDIS_MASK                 0x00000800
#define BCHP_LED_PER_LED_HWDIS_1_LED_43_HWDIS_SHIFT                11
#define BCHP_LED_PER_LED_HWDIS_1_LED_43_HWDIS_DEFAULT              0x00000000

/* LED_PER :: LED_HWDIS_1 :: LED_42_HWDIS [10:10] */
#define BCHP_LED_PER_LED_HWDIS_1_LED_42_HWDIS_MASK                 0x00000400
#define BCHP_LED_PER_LED_HWDIS_1_LED_42_HWDIS_SHIFT                10

/* LED_PER :: LED_HWDIS_1 :: LED_41_HWDIS [09:09] */
#define BCHP_LED_PER_LED_HWDIS_1_LED_41_HWDIS_MASK                 0x00000200
#define BCHP_LED_PER_LED_HWDIS_1_LED_41_HWDIS_SHIFT                9

/* LED_PER :: LED_HWDIS_1 :: LED_40_HWDIS [08:08] */
#define BCHP_LED_PER_LED_HWDIS_1_LED_40_HWDIS_MASK                 0x00000100
#define BCHP_LED_PER_LED_HWDIS_1_LED_40_HWDIS_SHIFT                8

/* LED_PER :: LED_HWDIS_1 :: LED_39_HWDIS [07:07] */
#define BCHP_LED_PER_LED_HWDIS_1_LED_39_HWDIS_MASK                 0x00000080
#define BCHP_LED_PER_LED_HWDIS_1_LED_39_HWDIS_SHIFT                7

/* LED_PER :: LED_HWDIS_1 :: LED_38_HWDIS [06:06] */
#define BCHP_LED_PER_LED_HWDIS_1_LED_38_HWDIS_MASK                 0x00000040
#define BCHP_LED_PER_LED_HWDIS_1_LED_38_HWDIS_SHIFT                6

/* LED_PER :: LED_HWDIS_1 :: LED_37_HWDIS [05:05] */
#define BCHP_LED_PER_LED_HWDIS_1_LED_37_HWDIS_MASK                 0x00000020
#define BCHP_LED_PER_LED_HWDIS_1_LED_37_HWDIS_SHIFT                5

/* LED_PER :: LED_HWDIS_1 :: LED_36_HWDIS [04:04] */
#define BCHP_LED_PER_LED_HWDIS_1_LED_36_HWDIS_MASK                 0x00000010
#define BCHP_LED_PER_LED_HWDIS_1_LED_36_HWDIS_SHIFT                4

/* LED_PER :: LED_HWDIS_1 :: LED_35_HWDIS [03:03] */
#define BCHP_LED_PER_LED_HWDIS_1_LED_35_HWDIS_MASK                 0x00000008
#define BCHP_LED_PER_LED_HWDIS_1_LED_35_HWDIS_SHIFT                3

/* LED_PER :: LED_HWDIS_1 :: LED_34_HWDIS [02:02] */
#define BCHP_LED_PER_LED_HWDIS_1_LED_34_HWDIS_MASK                 0x00000004
#define BCHP_LED_PER_LED_HWDIS_1_LED_34_HWDIS_SHIFT                2

/* LED_PER :: LED_HWDIS_1 :: LED_33_HWDIS [01:01] */
#define BCHP_LED_PER_LED_HWDIS_1_LED_33_HWDIS_MASK                 0x00000002
#define BCHP_LED_PER_LED_HWDIS_1_LED_33_HWDIS_SHIFT                1

/* LED_PER :: LED_HWDIS_1 :: LED_32_HWDIS [00:00] */
#define BCHP_LED_PER_LED_HWDIS_1_LED_32_HWDIS_MASK                 0x00000001
#define BCHP_LED_PER_LED_HWDIS_1_LED_32_HWDIS_SHIFT                0

/***************************************************************************
 *LED_STROBE_0 - LED Controller Strobe 0 Register
 ***************************************************************************/
/* LED_PER :: LED_STROBE_0 :: LED_31_STROBE [31:31] */
#define BCHP_LED_PER_LED_STROBE_0_LED_31_STROBE_MASK               0x80000000
#define BCHP_LED_PER_LED_STROBE_0_LED_31_STROBE_SHIFT              31
#define BCHP_LED_PER_LED_STROBE_0_LED_31_STROBE_DEFAULT            0x00000000

/* LED_PER :: LED_STROBE_0 :: LED_30_STB [30:30] */
#define BCHP_LED_PER_LED_STROBE_0_LED_30_STB_MASK                  0x40000000
#define BCHP_LED_PER_LED_STROBE_0_LED_30_STB_SHIFT                 30

/* LED_PER :: LED_STROBE_0 :: LED_29_STB [29:29] */
#define BCHP_LED_PER_LED_STROBE_0_LED_29_STB_MASK                  0x20000000
#define BCHP_LED_PER_LED_STROBE_0_LED_29_STB_SHIFT                 29

/* LED_PER :: LED_STROBE_0 :: LED_28_STB [28:28] */
#define BCHP_LED_PER_LED_STROBE_0_LED_28_STB_MASK                  0x10000000
#define BCHP_LED_PER_LED_STROBE_0_LED_28_STB_SHIFT                 28

/* LED_PER :: LED_STROBE_0 :: LED_27_STB [27:27] */
#define BCHP_LED_PER_LED_STROBE_0_LED_27_STB_MASK                  0x08000000
#define BCHP_LED_PER_LED_STROBE_0_LED_27_STB_SHIFT                 27

/* LED_PER :: LED_STROBE_0 :: LED_26_STB [26:26] */
#define BCHP_LED_PER_LED_STROBE_0_LED_26_STB_MASK                  0x04000000
#define BCHP_LED_PER_LED_STROBE_0_LED_26_STB_SHIFT                 26

/* LED_PER :: LED_STROBE_0 :: LED_25_STB [25:25] */
#define BCHP_LED_PER_LED_STROBE_0_LED_25_STB_MASK                  0x02000000
#define BCHP_LED_PER_LED_STROBE_0_LED_25_STB_SHIFT                 25

/* LED_PER :: LED_STROBE_0 :: LED_24_STB [24:24] */
#define BCHP_LED_PER_LED_STROBE_0_LED_24_STB_MASK                  0x01000000
#define BCHP_LED_PER_LED_STROBE_0_LED_24_STB_SHIFT                 24

/* LED_PER :: LED_STROBE_0 :: LED_23_STB [23:23] */
#define BCHP_LED_PER_LED_STROBE_0_LED_23_STB_MASK                  0x00800000
#define BCHP_LED_PER_LED_STROBE_0_LED_23_STB_SHIFT                 23

/* LED_PER :: LED_STROBE_0 :: LED_22_STB [22:22] */
#define BCHP_LED_PER_LED_STROBE_0_LED_22_STB_MASK                  0x00400000
#define BCHP_LED_PER_LED_STROBE_0_LED_22_STB_SHIFT                 22

/* LED_PER :: LED_STROBE_0 :: LED_21_STB [21:21] */
#define BCHP_LED_PER_LED_STROBE_0_LED_21_STB_MASK                  0x00200000
#define BCHP_LED_PER_LED_STROBE_0_LED_21_STB_SHIFT                 21

/* LED_PER :: LED_STROBE_0 :: LED_20_STB [20:20] */
#define BCHP_LED_PER_LED_STROBE_0_LED_20_STB_MASK                  0x00100000
#define BCHP_LED_PER_LED_STROBE_0_LED_20_STB_SHIFT                 20

/* LED_PER :: LED_STROBE_0 :: LED_19_STB [19:19] */
#define BCHP_LED_PER_LED_STROBE_0_LED_19_STB_MASK                  0x00080000
#define BCHP_LED_PER_LED_STROBE_0_LED_19_STB_SHIFT                 19

/* LED_PER :: LED_STROBE_0 :: LED_18_STB [18:18] */
#define BCHP_LED_PER_LED_STROBE_0_LED_18_STB_MASK                  0x00040000
#define BCHP_LED_PER_LED_STROBE_0_LED_18_STB_SHIFT                 18

/* LED_PER :: LED_STROBE_0 :: LED_17_STB [17:17] */
#define BCHP_LED_PER_LED_STROBE_0_LED_17_STB_MASK                  0x00020000
#define BCHP_LED_PER_LED_STROBE_0_LED_17_STB_SHIFT                 17

/* LED_PER :: LED_STROBE_0 :: LED_16_STB [16:16] */
#define BCHP_LED_PER_LED_STROBE_0_LED_16_STB_MASK                  0x00010000
#define BCHP_LED_PER_LED_STROBE_0_LED_16_STB_SHIFT                 16

/* LED_PER :: LED_STROBE_0 :: LED_15_STB [15:15] */
#define BCHP_LED_PER_LED_STROBE_0_LED_15_STB_MASK                  0x00008000
#define BCHP_LED_PER_LED_STROBE_0_LED_15_STB_SHIFT                 15

/* LED_PER :: LED_STROBE_0 :: LED_14_STB [14:14] */
#define BCHP_LED_PER_LED_STROBE_0_LED_14_STB_MASK                  0x00004000
#define BCHP_LED_PER_LED_STROBE_0_LED_14_STB_SHIFT                 14

/* LED_PER :: LED_STROBE_0 :: LED_13_STB [13:13] */
#define BCHP_LED_PER_LED_STROBE_0_LED_13_STB_MASK                  0x00002000
#define BCHP_LED_PER_LED_STROBE_0_LED_13_STB_SHIFT                 13

/* LED_PER :: LED_STROBE_0 :: LED_12_STB [12:12] */
#define BCHP_LED_PER_LED_STROBE_0_LED_12_STB_MASK                  0x00001000
#define BCHP_LED_PER_LED_STROBE_0_LED_12_STB_SHIFT                 12

/* LED_PER :: LED_STROBE_0 :: LED_11_STB [11:11] */
#define BCHP_LED_PER_LED_STROBE_0_LED_11_STB_MASK                  0x00000800
#define BCHP_LED_PER_LED_STROBE_0_LED_11_STB_SHIFT                 11

/* LED_PER :: LED_STROBE_0 :: LED_10_STB [10:10] */
#define BCHP_LED_PER_LED_STROBE_0_LED_10_STB_MASK                  0x00000400
#define BCHP_LED_PER_LED_STROBE_0_LED_10_STB_SHIFT                 10

/* LED_PER :: LED_STROBE_0 :: LED_9_STB [09:09] */
#define BCHP_LED_PER_LED_STROBE_0_LED_9_STB_MASK                   0x00000200
#define BCHP_LED_PER_LED_STROBE_0_LED_9_STB_SHIFT                  9

/* LED_PER :: LED_STROBE_0 :: LED_8_STB [08:08] */
#define BCHP_LED_PER_LED_STROBE_0_LED_8_STB_MASK                   0x00000100
#define BCHP_LED_PER_LED_STROBE_0_LED_8_STB_SHIFT                  8

/* LED_PER :: LED_STROBE_0 :: LED_7_STB [07:07] */
#define BCHP_LED_PER_LED_STROBE_0_LED_7_STB_MASK                   0x00000080
#define BCHP_LED_PER_LED_STROBE_0_LED_7_STB_SHIFT                  7

/* LED_PER :: LED_STROBE_0 :: LED_6_STB [06:06] */
#define BCHP_LED_PER_LED_STROBE_0_LED_6_STB_MASK                   0x00000040
#define BCHP_LED_PER_LED_STROBE_0_LED_6_STB_SHIFT                  6

/* LED_PER :: LED_STROBE_0 :: LED_5_STB [05:05] */
#define BCHP_LED_PER_LED_STROBE_0_LED_5_STB_MASK                   0x00000020
#define BCHP_LED_PER_LED_STROBE_0_LED_5_STB_SHIFT                  5

/* LED_PER :: LED_STROBE_0 :: LED_4_STB [04:04] */
#define BCHP_LED_PER_LED_STROBE_0_LED_4_STB_MASK                   0x00000010
#define BCHP_LED_PER_LED_STROBE_0_LED_4_STB_SHIFT                  4

/* LED_PER :: LED_STROBE_0 :: LED_3_STB [03:03] */
#define BCHP_LED_PER_LED_STROBE_0_LED_3_STB_MASK                   0x00000008
#define BCHP_LED_PER_LED_STROBE_0_LED_3_STB_SHIFT                  3

/* LED_PER :: LED_STROBE_0 :: LED_2_STB [02:02] */
#define BCHP_LED_PER_LED_STROBE_0_LED_2_STB_MASK                   0x00000004
#define BCHP_LED_PER_LED_STROBE_0_LED_2_STB_SHIFT                  2

/* LED_PER :: LED_STROBE_0 :: LED_1_STB [01:01] */
#define BCHP_LED_PER_LED_STROBE_0_LED_1_STB_MASK                   0x00000002
#define BCHP_LED_PER_LED_STROBE_0_LED_1_STB_SHIFT                  1

/* LED_PER :: LED_STROBE_0 :: LED_0_STB [00:00] */
#define BCHP_LED_PER_LED_STROBE_0_LED_0_STB_MASK                   0x00000001
#define BCHP_LED_PER_LED_STROBE_0_LED_0_STB_SHIFT                  0

/***************************************************************************
 *LED_STROBE_1 - LED Controller Strobe 1 Register
 ***************************************************************************/
/* LED_PER :: LED_STROBE_1 :: reserved0 [31:12] */
#define BCHP_LED_PER_LED_STROBE_1_reserved0_MASK                   0xfffff000
#define BCHP_LED_PER_LED_STROBE_1_reserved0_SHIFT                  12

/* LED_PER :: LED_STROBE_1 :: LED_43_STROBE [11:11] */
#define BCHP_LED_PER_LED_STROBE_1_LED_43_STROBE_MASK               0x00000800
#define BCHP_LED_PER_LED_STROBE_1_LED_43_STROBE_SHIFT              11
#define BCHP_LED_PER_LED_STROBE_1_LED_43_STROBE_DEFAULT            0x00000000

/* LED_PER :: LED_STROBE_1 :: LED_42_STB [10:10] */
#define BCHP_LED_PER_LED_STROBE_1_LED_42_STB_MASK                  0x00000400
#define BCHP_LED_PER_LED_STROBE_1_LED_42_STB_SHIFT                 10

/* LED_PER :: LED_STROBE_1 :: LED_41_STB [09:09] */
#define BCHP_LED_PER_LED_STROBE_1_LED_41_STB_MASK                  0x00000200
#define BCHP_LED_PER_LED_STROBE_1_LED_41_STB_SHIFT                 9

/* LED_PER :: LED_STROBE_1 :: LED_40_STB [08:08] */
#define BCHP_LED_PER_LED_STROBE_1_LED_40_STB_MASK                  0x00000100
#define BCHP_LED_PER_LED_STROBE_1_LED_40_STB_SHIFT                 8

/* LED_PER :: LED_STROBE_1 :: LED_39_STB [07:07] */
#define BCHP_LED_PER_LED_STROBE_1_LED_39_STB_MASK                  0x00000080
#define BCHP_LED_PER_LED_STROBE_1_LED_39_STB_SHIFT                 7

/* LED_PER :: LED_STROBE_1 :: LED_38_STB [06:06] */
#define BCHP_LED_PER_LED_STROBE_1_LED_38_STB_MASK                  0x00000040
#define BCHP_LED_PER_LED_STROBE_1_LED_38_STB_SHIFT                 6

/* LED_PER :: LED_STROBE_1 :: LED_37_STB [05:05] */
#define BCHP_LED_PER_LED_STROBE_1_LED_37_STB_MASK                  0x00000020
#define BCHP_LED_PER_LED_STROBE_1_LED_37_STB_SHIFT                 5

/* LED_PER :: LED_STROBE_1 :: LED_36_STB [04:04] */
#define BCHP_LED_PER_LED_STROBE_1_LED_36_STB_MASK                  0x00000010
#define BCHP_LED_PER_LED_STROBE_1_LED_36_STB_SHIFT                 4

/* LED_PER :: LED_STROBE_1 :: LED_35_STB [03:03] */
#define BCHP_LED_PER_LED_STROBE_1_LED_35_STB_MASK                  0x00000008
#define BCHP_LED_PER_LED_STROBE_1_LED_35_STB_SHIFT                 3

/* LED_PER :: LED_STROBE_1 :: LED_34_STB [02:02] */
#define BCHP_LED_PER_LED_STROBE_1_LED_34_STB_MASK                  0x00000004
#define BCHP_LED_PER_LED_STROBE_1_LED_34_STB_SHIFT                 2

/* LED_PER :: LED_STROBE_1 :: LED_33_STB [01:01] */
#define BCHP_LED_PER_LED_STROBE_1_LED_33_STB_MASK                  0x00000002
#define BCHP_LED_PER_LED_STROBE_1_LED_33_STB_SHIFT                 1

/* LED_PER :: LED_STROBE_1 :: LED_32_STB [00:00] */
#define BCHP_LED_PER_LED_STROBE_1_LED_32_STB_MASK                  0x00000001
#define BCHP_LED_PER_LED_STROBE_1_LED_32_STB_SHIFT                 0

/***************************************************************************
 *LED_MASK - LED Controller HW Activity Mask Register
 ***************************************************************************/
/* LED_PER :: LED_MASK :: LED_7_LINK_MASK [31:28] */
#define BCHP_LED_PER_LED_MASK_LED_7_LINK_MASK_MASK                 0xf0000000
#define BCHP_LED_PER_LED_MASK_LED_7_LINK_MASK_SHIFT                28
#define BCHP_LED_PER_LED_MASK_LED_7_LINK_MASK_DEFAULT              0x00000000
#define BCHP_LED_PER_LED_MASK_LED_7_LINK_MASK_RSVD1                8
#define BCHP_LED_PER_LED_MASK_LED_7_LINK_MASK_EPHY1_LNK            4
#define BCHP_LED_PER_LED_MASK_LED_7_LINK_MASK_EPHY0_LNK1           2
#define BCHP_LED_PER_LED_MASK_LED_7_LINK_MASK_EPHY0_LNK0           1

/* LED_PER :: LED_MASK :: LED_6_LINK_MASK [27:24] */
#define BCHP_LED_PER_LED_MASK_LED_6_LINK_MASK_MASK                 0x0f000000
#define BCHP_LED_PER_LED_MASK_LED_6_LINK_MASK_SHIFT                24
#define BCHP_LED_PER_LED_MASK_LED_6_LINK_MASK_DEFAULT              0x00000000
#define BCHP_LED_PER_LED_MASK_LED_6_LINK_MASK_RSVD1                8
#define BCHP_LED_PER_LED_MASK_LED_6_LINK_MASK_EPHY1_LNK            4
#define BCHP_LED_PER_LED_MASK_LED_6_LINK_MASK_EPHY0_LNK1           2
#define BCHP_LED_PER_LED_MASK_LED_6_LINK_MASK_EPHY0_LNK0           1

/* LED_PER :: LED_MASK :: LED_5_LINK_MASK [23:20] */
#define BCHP_LED_PER_LED_MASK_LED_5_LINK_MASK_MASK                 0x00f00000
#define BCHP_LED_PER_LED_MASK_LED_5_LINK_MASK_SHIFT                20
#define BCHP_LED_PER_LED_MASK_LED_5_LINK_MASK_DEFAULT              0x00000000
#define BCHP_LED_PER_LED_MASK_LED_5_LINK_MASK_RSVD1                8
#define BCHP_LED_PER_LED_MASK_LED_5_LINK_MASK_EPHY1_LNK            4
#define BCHP_LED_PER_LED_MASK_LED_5_LINK_MASK_EPHY0_LNK1           2
#define BCHP_LED_PER_LED_MASK_LED_5_LINK_MASK_EPHY0_LNK0           1

/* LED_PER :: LED_MASK :: LED_4_LINK_MASK [19:16] */
#define BCHP_LED_PER_LED_MASK_LED_4_LINK_MASK_MASK                 0x000f0000
#define BCHP_LED_PER_LED_MASK_LED_4_LINK_MASK_SHIFT                16
#define BCHP_LED_PER_LED_MASK_LED_4_LINK_MASK_DEFAULT              0x00000000
#define BCHP_LED_PER_LED_MASK_LED_4_LINK_MASK_RSVD1                8
#define BCHP_LED_PER_LED_MASK_LED_4_LINK_MASK_EPHY1_LNK            4
#define BCHP_LED_PER_LED_MASK_LED_4_LINK_MASK_EPHY0_LNK1           2
#define BCHP_LED_PER_LED_MASK_LED_4_LINK_MASK_EPHY0_LNK0           1

/* LED_PER :: LED_MASK :: LED_7_ACT_MASK [15:12] */
#define BCHP_LED_PER_LED_MASK_LED_7_ACT_MASK_MASK                  0x0000f000
#define BCHP_LED_PER_LED_MASK_LED_7_ACT_MASK_SHIFT                 12
#define BCHP_LED_PER_LED_MASK_LED_7_ACT_MASK_DEFAULT               0x00000000
#define BCHP_LED_PER_LED_MASK_LED_7_ACT_MASK_RSVD1                 8
#define BCHP_LED_PER_LED_MASK_LED_7_ACT_MASK_RSVD0                 4
#define BCHP_LED_PER_LED_MASK_LED_7_ACT_MASK_EPHY1_ACT             2
#define BCHP_LED_PER_LED_MASK_LED_7_ACT_MASK_EPHY0_ACT             1

/* LED_PER :: LED_MASK :: LED_6_ACT_MASK [11:08] */
#define BCHP_LED_PER_LED_MASK_LED_6_ACT_MASK_MASK                  0x00000f00
#define BCHP_LED_PER_LED_MASK_LED_6_ACT_MASK_SHIFT                 8
#define BCHP_LED_PER_LED_MASK_LED_6_ACT_MASK_DEFAULT               0x00000000
#define BCHP_LED_PER_LED_MASK_LED_6_ACT_MASK_RSVD1                 8
#define BCHP_LED_PER_LED_MASK_LED_6_ACT_MASK_RSVD0                 4
#define BCHP_LED_PER_LED_MASK_LED_6_ACT_MASK_EPHY1_ACT             2
#define BCHP_LED_PER_LED_MASK_LED_6_ACT_MASK_EPHY0_ACT             1

/* LED_PER :: LED_MASK :: LED_5_ACT_MASK [07:04] */
#define BCHP_LED_PER_LED_MASK_LED_5_ACT_MASK_MASK                  0x000000f0
#define BCHP_LED_PER_LED_MASK_LED_5_ACT_MASK_SHIFT                 4
#define BCHP_LED_PER_LED_MASK_LED_5_ACT_MASK_DEFAULT               0x00000000
#define BCHP_LED_PER_LED_MASK_LED_5_ACT_MASK_RSVD1                 8
#define BCHP_LED_PER_LED_MASK_LED_5_ACT_MASK_RSVD0                 4
#define BCHP_LED_PER_LED_MASK_LED_5_ACT_MASK_EPHY1_ACT             2
#define BCHP_LED_PER_LED_MASK_LED_5_ACT_MASK_EPHY0_ACT             1

/* LED_PER :: LED_MASK :: LED_4_ACT_MASK [03:00] */
#define BCHP_LED_PER_LED_MASK_LED_4_ACT_MASK_MASK                  0x0000000f
#define BCHP_LED_PER_LED_MASK_LED_4_ACT_MASK_SHIFT                 0
#define BCHP_LED_PER_LED_MASK_LED_4_ACT_MASK_DEFAULT               0x00000000
#define BCHP_LED_PER_LED_MASK_LED_4_ACT_MASK_RSVD1                 8
#define BCHP_LED_PER_LED_MASK_LED_4_ACT_MASK_RSVD0                 4
#define BCHP_LED_PER_LED_MASK_LED_4_ACT_MASK_EPHY1_ACT             2
#define BCHP_LED_PER_LED_MASK_LED_4_ACT_MASK_EPHY0_ACT             1

/***************************************************************************
 *LED_READBACK_0 - LED Controller Read Back 0 Register
 ***************************************************************************/
/* LED_PER :: LED_READBACK_0 :: LED_31_IN [31:31] */
#define BCHP_LED_PER_LED_READBACK_0_LED_31_IN_MASK                 0x80000000
#define BCHP_LED_PER_LED_READBACK_0_LED_31_IN_SHIFT                31

/* LED_PER :: LED_READBACK_0 :: LED_30_IN [30:30] */
#define BCHP_LED_PER_LED_READBACK_0_LED_30_IN_MASK                 0x40000000
#define BCHP_LED_PER_LED_READBACK_0_LED_30_IN_SHIFT                30

/* LED_PER :: LED_READBACK_0 :: LED_29_IN [29:29] */
#define BCHP_LED_PER_LED_READBACK_0_LED_29_IN_MASK                 0x20000000
#define BCHP_LED_PER_LED_READBACK_0_LED_29_IN_SHIFT                29

/* LED_PER :: LED_READBACK_0 :: LED_28_IN [28:28] */
#define BCHP_LED_PER_LED_READBACK_0_LED_28_IN_MASK                 0x10000000
#define BCHP_LED_PER_LED_READBACK_0_LED_28_IN_SHIFT                28

/* LED_PER :: LED_READBACK_0 :: LED_27_IN [27:27] */
#define BCHP_LED_PER_LED_READBACK_0_LED_27_IN_MASK                 0x08000000
#define BCHP_LED_PER_LED_READBACK_0_LED_27_IN_SHIFT                27

/* LED_PER :: LED_READBACK_0 :: LED_26_IN [26:26] */
#define BCHP_LED_PER_LED_READBACK_0_LED_26_IN_MASK                 0x04000000
#define BCHP_LED_PER_LED_READBACK_0_LED_26_IN_SHIFT                26

/* LED_PER :: LED_READBACK_0 :: LED_25_IN [25:25] */
#define BCHP_LED_PER_LED_READBACK_0_LED_25_IN_MASK                 0x02000000
#define BCHP_LED_PER_LED_READBACK_0_LED_25_IN_SHIFT                25

/* LED_PER :: LED_READBACK_0 :: LED_24_IN [24:24] */
#define BCHP_LED_PER_LED_READBACK_0_LED_24_IN_MASK                 0x01000000
#define BCHP_LED_PER_LED_READBACK_0_LED_24_IN_SHIFT                24

/* LED_PER :: LED_READBACK_0 :: LED_23_IN [23:23] */
#define BCHP_LED_PER_LED_READBACK_0_LED_23_IN_MASK                 0x00800000
#define BCHP_LED_PER_LED_READBACK_0_LED_23_IN_SHIFT                23

/* LED_PER :: LED_READBACK_0 :: LED_22_IN [22:22] */
#define BCHP_LED_PER_LED_READBACK_0_LED_22_IN_MASK                 0x00400000
#define BCHP_LED_PER_LED_READBACK_0_LED_22_IN_SHIFT                22

/* LED_PER :: LED_READBACK_0 :: LED_21_IN [21:21] */
#define BCHP_LED_PER_LED_READBACK_0_LED_21_IN_MASK                 0x00200000
#define BCHP_LED_PER_LED_READBACK_0_LED_21_IN_SHIFT                21

/* LED_PER :: LED_READBACK_0 :: LED_20_IN [20:20] */
#define BCHP_LED_PER_LED_READBACK_0_LED_20_IN_MASK                 0x00100000
#define BCHP_LED_PER_LED_READBACK_0_LED_20_IN_SHIFT                20

/* LED_PER :: LED_READBACK_0 :: LED_19_IN [19:19] */
#define BCHP_LED_PER_LED_READBACK_0_LED_19_IN_MASK                 0x00080000
#define BCHP_LED_PER_LED_READBACK_0_LED_19_IN_SHIFT                19

/* LED_PER :: LED_READBACK_0 :: LED_18_IN [18:18] */
#define BCHP_LED_PER_LED_READBACK_0_LED_18_IN_MASK                 0x00040000
#define BCHP_LED_PER_LED_READBACK_0_LED_18_IN_SHIFT                18

/* LED_PER :: LED_READBACK_0 :: LED_17_IN [17:17] */
#define BCHP_LED_PER_LED_READBACK_0_LED_17_IN_MASK                 0x00020000
#define BCHP_LED_PER_LED_READBACK_0_LED_17_IN_SHIFT                17

/* LED_PER :: LED_READBACK_0 :: LED_16_IN [16:16] */
#define BCHP_LED_PER_LED_READBACK_0_LED_16_IN_MASK                 0x00010000
#define BCHP_LED_PER_LED_READBACK_0_LED_16_IN_SHIFT                16

/* LED_PER :: LED_READBACK_0 :: LED_15_IN [15:15] */
#define BCHP_LED_PER_LED_READBACK_0_LED_15_IN_MASK                 0x00008000
#define BCHP_LED_PER_LED_READBACK_0_LED_15_IN_SHIFT                15

/* LED_PER :: LED_READBACK_0 :: LED_14_IN [14:14] */
#define BCHP_LED_PER_LED_READBACK_0_LED_14_IN_MASK                 0x00004000
#define BCHP_LED_PER_LED_READBACK_0_LED_14_IN_SHIFT                14

/* LED_PER :: LED_READBACK_0 :: LED_13_IN [13:13] */
#define BCHP_LED_PER_LED_READBACK_0_LED_13_IN_MASK                 0x00002000
#define BCHP_LED_PER_LED_READBACK_0_LED_13_IN_SHIFT                13

/* LED_PER :: LED_READBACK_0 :: LED_12_IN [12:12] */
#define BCHP_LED_PER_LED_READBACK_0_LED_12_IN_MASK                 0x00001000
#define BCHP_LED_PER_LED_READBACK_0_LED_12_IN_SHIFT                12

/* LED_PER :: LED_READBACK_0 :: LED_11_IN [11:11] */
#define BCHP_LED_PER_LED_READBACK_0_LED_11_IN_MASK                 0x00000800
#define BCHP_LED_PER_LED_READBACK_0_LED_11_IN_SHIFT                11

/* LED_PER :: LED_READBACK_0 :: LED_10_IN [10:10] */
#define BCHP_LED_PER_LED_READBACK_0_LED_10_IN_MASK                 0x00000400
#define BCHP_LED_PER_LED_READBACK_0_LED_10_IN_SHIFT                10

/* LED_PER :: LED_READBACK_0 :: LED_9_IN [09:09] */
#define BCHP_LED_PER_LED_READBACK_0_LED_9_IN_MASK                  0x00000200
#define BCHP_LED_PER_LED_READBACK_0_LED_9_IN_SHIFT                 9

/* LED_PER :: LED_READBACK_0 :: LED_8_IN [08:08] */
#define BCHP_LED_PER_LED_READBACK_0_LED_8_IN_MASK                  0x00000100
#define BCHP_LED_PER_LED_READBACK_0_LED_8_IN_SHIFT                 8

/* LED_PER :: LED_READBACK_0 :: LED_7_IN [07:07] */
#define BCHP_LED_PER_LED_READBACK_0_LED_7_IN_MASK                  0x00000080
#define BCHP_LED_PER_LED_READBACK_0_LED_7_IN_SHIFT                 7

/* LED_PER :: LED_READBACK_0 :: LED_6_IN [06:06] */
#define BCHP_LED_PER_LED_READBACK_0_LED_6_IN_MASK                  0x00000040
#define BCHP_LED_PER_LED_READBACK_0_LED_6_IN_SHIFT                 6

/* LED_PER :: LED_READBACK_0 :: LED_5_IN [05:05] */
#define BCHP_LED_PER_LED_READBACK_0_LED_5_IN_MASK                  0x00000020
#define BCHP_LED_PER_LED_READBACK_0_LED_5_IN_SHIFT                 5

/* LED_PER :: LED_READBACK_0 :: LED_4_IN [04:04] */
#define BCHP_LED_PER_LED_READBACK_0_LED_4_IN_MASK                  0x00000010
#define BCHP_LED_PER_LED_READBACK_0_LED_4_IN_SHIFT                 4

/* LED_PER :: LED_READBACK_0 :: LED_3_IN [03:03] */
#define BCHP_LED_PER_LED_READBACK_0_LED_3_IN_MASK                  0x00000008
#define BCHP_LED_PER_LED_READBACK_0_LED_3_IN_SHIFT                 3

/* LED_PER :: LED_READBACK_0 :: LED_2_IN [02:02] */
#define BCHP_LED_PER_LED_READBACK_0_LED_2_IN_MASK                  0x00000004
#define BCHP_LED_PER_LED_READBACK_0_LED_2_IN_SHIFT                 2

/* LED_PER :: LED_READBACK_0 :: LED_1_IN [01:01] */
#define BCHP_LED_PER_LED_READBACK_0_LED_1_IN_MASK                  0x00000002
#define BCHP_LED_PER_LED_READBACK_0_LED_1_IN_SHIFT                 1

/* LED_PER :: LED_READBACK_0 :: LED_0_IN [00:00] */
#define BCHP_LED_PER_LED_READBACK_0_LED_0_IN_MASK                  0x00000001
#define BCHP_LED_PER_LED_READBACK_0_LED_0_IN_SHIFT                 0

/***************************************************************************
 *LED_READBACK_1 - LED Controller Read Back 1 Register
 ***************************************************************************/
/* LED_PER :: LED_READBACK_1 :: reserved0 [31:12] */
#define BCHP_LED_PER_LED_READBACK_1_reserved0_MASK                 0xfffff000
#define BCHP_LED_PER_LED_READBACK_1_reserved0_SHIFT                12

/* LED_PER :: LED_READBACK_1 :: LED_43_IN [11:11] */
#define BCHP_LED_PER_LED_READBACK_1_LED_43_IN_MASK                 0x00000800
#define BCHP_LED_PER_LED_READBACK_1_LED_43_IN_SHIFT                11

/* LED_PER :: LED_READBACK_1 :: LED_42_IN [10:10] */
#define BCHP_LED_PER_LED_READBACK_1_LED_42_IN_MASK                 0x00000400
#define BCHP_LED_PER_LED_READBACK_1_LED_42_IN_SHIFT                10

/* LED_PER :: LED_READBACK_1 :: LED_41_IN [09:09] */
#define BCHP_LED_PER_LED_READBACK_1_LED_41_IN_MASK                 0x00000200
#define BCHP_LED_PER_LED_READBACK_1_LED_41_IN_SHIFT                9

/* LED_PER :: LED_READBACK_1 :: LED_40_IN [08:08] */
#define BCHP_LED_PER_LED_READBACK_1_LED_40_IN_MASK                 0x00000100
#define BCHP_LED_PER_LED_READBACK_1_LED_40_IN_SHIFT                8

/* LED_PER :: LED_READBACK_1 :: LED_39_IN [07:07] */
#define BCHP_LED_PER_LED_READBACK_1_LED_39_IN_MASK                 0x00000080
#define BCHP_LED_PER_LED_READBACK_1_LED_39_IN_SHIFT                7

/* LED_PER :: LED_READBACK_1 :: LED_38_IN [06:06] */
#define BCHP_LED_PER_LED_READBACK_1_LED_38_IN_MASK                 0x00000040
#define BCHP_LED_PER_LED_READBACK_1_LED_38_IN_SHIFT                6

/* LED_PER :: LED_READBACK_1 :: LED_37_IN [05:05] */
#define BCHP_LED_PER_LED_READBACK_1_LED_37_IN_MASK                 0x00000020
#define BCHP_LED_PER_LED_READBACK_1_LED_37_IN_SHIFT                5

/* LED_PER :: LED_READBACK_1 :: LED_36_IN [04:04] */
#define BCHP_LED_PER_LED_READBACK_1_LED_36_IN_MASK                 0x00000010
#define BCHP_LED_PER_LED_READBACK_1_LED_36_IN_SHIFT                4

/* LED_PER :: LED_READBACK_1 :: LED_35_IN [03:03] */
#define BCHP_LED_PER_LED_READBACK_1_LED_35_IN_MASK                 0x00000008
#define BCHP_LED_PER_LED_READBACK_1_LED_35_IN_SHIFT                3

/* LED_PER :: LED_READBACK_1 :: LED_34_IN [02:02] */
#define BCHP_LED_PER_LED_READBACK_1_LED_34_IN_MASK                 0x00000004
#define BCHP_LED_PER_LED_READBACK_1_LED_34_IN_SHIFT                2

/* LED_PER :: LED_READBACK_1 :: LED_33_IN [01:01] */
#define BCHP_LED_PER_LED_READBACK_1_LED_33_IN_MASK                 0x00000002
#define BCHP_LED_PER_LED_READBACK_1_LED_33_IN_SHIFT                1

/* LED_PER :: LED_READBACK_1 :: LED_32_IN [00:00] */
#define BCHP_LED_PER_LED_READBACK_1_LED_32_IN_MASK                 0x00000001
#define BCHP_LED_PER_LED_READBACK_1_LED_32_IN_SHIFT                0

#endif /* #ifndef BCHP_LED_PER_H__ */

/* End of File */
