/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Nov 14 03:20:40 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_DQMQMIB_GB_H__
#define BCHP_DQMQMIB_GB_H__

/***************************************************************************
 *DQMQMIB_GB
 ***************************************************************************/

/***************************************************************************
 *num_full%i - Queue Num Full Register
 ***************************************************************************/
#define BCHP_DQMQMIB_GB_num_fulli_ARRAY_BASE                       0x104b0c00
#define BCHP_DQMQMIB_GB_num_fulli_ARRAY_START                      0
#define BCHP_DQMQMIB_GB_num_fulli_ARRAY_END                        31
#define BCHP_DQMQMIB_GB_num_fulli_ARRAY_ELEMENT_SIZE               32

/***************************************************************************
 *num_full%i - Queue Num Full Register
 ***************************************************************************/
/* DQMQMIB_GB :: num_fulli :: Q_NUM_FULL [31:00] */
#define BCHP_DQMQMIB_GB_num_fulli_Q_NUM_FULL_MASK                  0xffffffff
#define BCHP_DQMQMIB_GB_num_fulli_Q_NUM_FULL_SHIFT                 0
#define BCHP_DQMQMIB_GB_num_fulli_Q_NUM_FULL_DEFAULT               0x00000000


/***************************************************************************
 *num_empty%i - Queue Num Empty Register
 ***************************************************************************/
#define BCHP_DQMQMIB_GB_num_emptyi_ARRAY_BASE                      0x104b0c80
#define BCHP_DQMQMIB_GB_num_emptyi_ARRAY_START                     0
#define BCHP_DQMQMIB_GB_num_emptyi_ARRAY_END                       31
#define BCHP_DQMQMIB_GB_num_emptyi_ARRAY_ELEMENT_SIZE              32

/***************************************************************************
 *num_empty%i - Queue Num Empty Register
 ***************************************************************************/
/* DQMQMIB_GB :: num_emptyi :: Q_NUM_EMPTY [31:00] */
#define BCHP_DQMQMIB_GB_num_emptyi_Q_NUM_EMPTY_MASK                0xffffffff
#define BCHP_DQMQMIB_GB_num_emptyi_Q_NUM_EMPTY_SHIFT               0
#define BCHP_DQMQMIB_GB_num_emptyi_Q_NUM_EMPTY_DEFAULT             0x00000000


/***************************************************************************
 *num_pushed%i - Queue Num Pushed Register
 ***************************************************************************/
#define BCHP_DQMQMIB_GB_num_pushedi_ARRAY_BASE                     0x104b0d00
#define BCHP_DQMQMIB_GB_num_pushedi_ARRAY_START                    0
#define BCHP_DQMQMIB_GB_num_pushedi_ARRAY_END                      31
#define BCHP_DQMQMIB_GB_num_pushedi_ARRAY_ELEMENT_SIZE             32

/***************************************************************************
 *num_pushed%i - Queue Num Pushed Register
 ***************************************************************************/
/* DQMQMIB_GB :: num_pushedi :: Q_NUM_TOKENS_PUSHED [31:00] */
#define BCHP_DQMQMIB_GB_num_pushedi_Q_NUM_TOKENS_PUSHED_MASK       0xffffffff
#define BCHP_DQMQMIB_GB_num_pushedi_Q_NUM_TOKENS_PUSHED_SHIFT      0
#define BCHP_DQMQMIB_GB_num_pushedi_Q_NUM_TOKENS_PUSHED_DEFAULT    0x00000000


#endif /* #ifndef BCHP_DQMQMIB_GB_H__ */

/* End of File */
