/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Nov 14 03:20:39 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_MBOX_GB_H__
#define BCHP_MBOX_GB_H__

/***************************************************************************
 *MBOX_GB
 ***************************************************************************/
#define BCHP_MBOX_GB_DATA0                       0x104b0080 /* MBOX0 Register */
#define BCHP_MBOX_GB_DATA1                       0x104b0084 /* MBOX1 Register */
#define BCHP_MBOX_GB_DATA2                       0x104b0088 /* MBOX2 Register */
#define BCHP_MBOX_GB_DATA3                       0x104b008c /* MBOX3 Register */
#define BCHP_MBOX_GB_DATA4                       0x104b0090 /* MBOX4 Register */
#define BCHP_MBOX_GB_DATA5                       0x104b0094 /* MBOX5 Register */
#define BCHP_MBOX_GB_DATA6                       0x104b0098 /* MBOX6 Register */
#define BCHP_MBOX_GB_DATA7                       0x104b009c /* MBOX7 Register */
#define BCHP_MBOX_GB_DATA8                       0x104b00a0 /* MBOX8 Register */
#define BCHP_MBOX_GB_DATA9                       0x104b00a4 /* MBOX9 Register */
#define BCHP_MBOX_GB_DATA10                      0x104b00a8 /* MBOX10 Register */
#define BCHP_MBOX_GB_DATA11                      0x104b00ac /* MBOX11 Register */
#define BCHP_MBOX_GB_DATA12                      0x104b00b0 /* MBOX12 Register */
#define BCHP_MBOX_GB_DATA13                      0x104b00b4 /* MBOX13 Register */
#define BCHP_MBOX_GB_DATA14                      0x104b00b8 /* MBOX14 Register */
#define BCHP_MBOX_GB_DATA15                      0x104b00bc /* MBOX15 Register */
#define BCHP_MBOX_GB_CFG0                        0x104b00c0 /* MBOX0 Configuration Register */
#define BCHP_MBOX_GB_CFG1                        0x104b00c4 /* MBOX1 Configuration Register */
#define BCHP_MBOX_GB_CFG2                        0x104b00c8 /* MBOX2 Configuration Register */
#define BCHP_MBOX_GB_CFG3                        0x104b00cc /* MBOX3 Configuration Register */
#define BCHP_MBOX_GB_CFG4                        0x104b00d0 /* MBOX4 Configuration Register */
#define BCHP_MBOX_GB_CFG5                        0x104b00d4 /* MBOX5 Configuration Register */
#define BCHP_MBOX_GB_CFG6                        0x104b00d8 /* MBOX6 Configuration Register */
#define BCHP_MBOX_GB_CFG7                        0x104b00dc /* MBOX7 Configuration Register */
#define BCHP_MBOX_GB_CFG8                        0x104b00e0 /* MBOX8 Configuration Register */
#define BCHP_MBOX_GB_CFG9                        0x104b00e4 /* MBOX9 Configuration Register */
#define BCHP_MBOX_GB_CFG10                       0x104b00e8 /* MBOX10 Configuration Register */
#define BCHP_MBOX_GB_CFG11                       0x104b00ec /* MBOX11 Configuration Register */
#define BCHP_MBOX_GB_CFG12                       0x104b00f0 /* MBOX12 Configuration Register */
#define BCHP_MBOX_GB_CFG13                       0x104b00f4 /* MBOX13 Configuration Register */
#define BCHP_MBOX_GB_CFG14                       0x104b00f8 /* MBOX14 Configuration Register */
#define BCHP_MBOX_GB_CFG15                       0x104b00fc /* MBOX15 Configuration Register */

/***************************************************************************
 *DATA0 - MBOX0 Register
 ***************************************************************************/
/* MBOX_GB :: DATA0 :: MBOX_IN [31:00] */
#define BCHP_MBOX_GB_DATA0_MBOX_IN_MASK                            0xffffffff
#define BCHP_MBOX_GB_DATA0_MBOX_IN_SHIFT                           0
#define BCHP_MBOX_GB_DATA0_MBOX_IN_DEFAULT                         0x00000000

/***************************************************************************
 *DATA1 - MBOX1 Register
 ***************************************************************************/
/* MBOX_GB :: DATA1 :: MBOX_IN [31:00] */
#define BCHP_MBOX_GB_DATA1_MBOX_IN_MASK                            0xffffffff
#define BCHP_MBOX_GB_DATA1_MBOX_IN_SHIFT                           0
#define BCHP_MBOX_GB_DATA1_MBOX_IN_DEFAULT                         0x00000000

/***************************************************************************
 *DATA2 - MBOX2 Register
 ***************************************************************************/
/* MBOX_GB :: DATA2 :: MBOX_IN [31:00] */
#define BCHP_MBOX_GB_DATA2_MBOX_IN_MASK                            0xffffffff
#define BCHP_MBOX_GB_DATA2_MBOX_IN_SHIFT                           0
#define BCHP_MBOX_GB_DATA2_MBOX_IN_DEFAULT                         0x00000000

/***************************************************************************
 *DATA3 - MBOX3 Register
 ***************************************************************************/
/* MBOX_GB :: DATA3 :: MBOX_IN [31:00] */
#define BCHP_MBOX_GB_DATA3_MBOX_IN_MASK                            0xffffffff
#define BCHP_MBOX_GB_DATA3_MBOX_IN_SHIFT                           0
#define BCHP_MBOX_GB_DATA3_MBOX_IN_DEFAULT                         0x00000000

/***************************************************************************
 *DATA4 - MBOX4 Register
 ***************************************************************************/
/* MBOX_GB :: DATA4 :: MBOX_IN [31:00] */
#define BCHP_MBOX_GB_DATA4_MBOX_IN_MASK                            0xffffffff
#define BCHP_MBOX_GB_DATA4_MBOX_IN_SHIFT                           0
#define BCHP_MBOX_GB_DATA4_MBOX_IN_DEFAULT                         0x00000000

/***************************************************************************
 *DATA5 - MBOX5 Register
 ***************************************************************************/
/* MBOX_GB :: DATA5 :: MBOX_IN [31:00] */
#define BCHP_MBOX_GB_DATA5_MBOX_IN_MASK                            0xffffffff
#define BCHP_MBOX_GB_DATA5_MBOX_IN_SHIFT                           0
#define BCHP_MBOX_GB_DATA5_MBOX_IN_DEFAULT                         0x00000000

/***************************************************************************
 *DATA6 - MBOX6 Register
 ***************************************************************************/
/* MBOX_GB :: DATA6 :: MBOX_IN [31:00] */
#define BCHP_MBOX_GB_DATA6_MBOX_IN_MASK                            0xffffffff
#define BCHP_MBOX_GB_DATA6_MBOX_IN_SHIFT                           0
#define BCHP_MBOX_GB_DATA6_MBOX_IN_DEFAULT                         0x00000000

/***************************************************************************
 *DATA7 - MBOX7 Register
 ***************************************************************************/
/* MBOX_GB :: DATA7 :: MBOX_IN [31:00] */
#define BCHP_MBOX_GB_DATA7_MBOX_IN_MASK                            0xffffffff
#define BCHP_MBOX_GB_DATA7_MBOX_IN_SHIFT                           0
#define BCHP_MBOX_GB_DATA7_MBOX_IN_DEFAULT                         0x00000000

/***************************************************************************
 *DATA8 - MBOX8 Register
 ***************************************************************************/
/* MBOX_GB :: DATA8 :: MBOX_IN [31:00] */
#define BCHP_MBOX_GB_DATA8_MBOX_IN_MASK                            0xffffffff
#define BCHP_MBOX_GB_DATA8_MBOX_IN_SHIFT                           0
#define BCHP_MBOX_GB_DATA8_MBOX_IN_DEFAULT                         0x00000000

/***************************************************************************
 *DATA9 - MBOX9 Register
 ***************************************************************************/
/* MBOX_GB :: DATA9 :: MBOX_IN [31:00] */
#define BCHP_MBOX_GB_DATA9_MBOX_IN_MASK                            0xffffffff
#define BCHP_MBOX_GB_DATA9_MBOX_IN_SHIFT                           0
#define BCHP_MBOX_GB_DATA9_MBOX_IN_DEFAULT                         0x00000000

/***************************************************************************
 *DATA10 - MBOX10 Register
 ***************************************************************************/
/* MBOX_GB :: DATA10 :: MBOX_IN [31:00] */
#define BCHP_MBOX_GB_DATA10_MBOX_IN_MASK                           0xffffffff
#define BCHP_MBOX_GB_DATA10_MBOX_IN_SHIFT                          0
#define BCHP_MBOX_GB_DATA10_MBOX_IN_DEFAULT                        0x00000000

/***************************************************************************
 *DATA11 - MBOX11 Register
 ***************************************************************************/
/* MBOX_GB :: DATA11 :: MBOX_IN [31:00] */
#define BCHP_MBOX_GB_DATA11_MBOX_IN_MASK                           0xffffffff
#define BCHP_MBOX_GB_DATA11_MBOX_IN_SHIFT                          0
#define BCHP_MBOX_GB_DATA11_MBOX_IN_DEFAULT                        0x00000000

/***************************************************************************
 *DATA12 - MBOX12 Register
 ***************************************************************************/
/* MBOX_GB :: DATA12 :: MBOX_IN [31:00] */
#define BCHP_MBOX_GB_DATA12_MBOX_IN_MASK                           0xffffffff
#define BCHP_MBOX_GB_DATA12_MBOX_IN_SHIFT                          0
#define BCHP_MBOX_GB_DATA12_MBOX_IN_DEFAULT                        0x00000000

/***************************************************************************
 *DATA13 - MBOX13 Register
 ***************************************************************************/
/* MBOX_GB :: DATA13 :: MBOX_IN [31:00] */
#define BCHP_MBOX_GB_DATA13_MBOX_IN_MASK                           0xffffffff
#define BCHP_MBOX_GB_DATA13_MBOX_IN_SHIFT                          0
#define BCHP_MBOX_GB_DATA13_MBOX_IN_DEFAULT                        0x00000000

/***************************************************************************
 *DATA14 - MBOX14 Register
 ***************************************************************************/
/* MBOX_GB :: DATA14 :: MBOX_IN [31:00] */
#define BCHP_MBOX_GB_DATA14_MBOX_IN_MASK                           0xffffffff
#define BCHP_MBOX_GB_DATA14_MBOX_IN_SHIFT                          0
#define BCHP_MBOX_GB_DATA14_MBOX_IN_DEFAULT                        0x00000000

/***************************************************************************
 *DATA15 - MBOX15 Register
 ***************************************************************************/
/* MBOX_GB :: DATA15 :: MBOX_IN [31:00] */
#define BCHP_MBOX_GB_DATA15_MBOX_IN_MASK                           0xffffffff
#define BCHP_MBOX_GB_DATA15_MBOX_IN_SHIFT                          0
#define BCHP_MBOX_GB_DATA15_MBOX_IN_DEFAULT                        0x00000000

/***************************************************************************
 *CFG0 - MBOX0 Configuration Register
 ***************************************************************************/
/* MBOX_GB :: CFG0 :: reserved0 [31:08] */
#define BCHP_MBOX_GB_CFG0_reserved0_MASK                           0xffffff00
#define BCHP_MBOX_GB_CFG0_reserved0_SHIFT                          8

/* MBOX_GB :: CFG0 :: MBOX_LOCK [07:07] */
#define BCHP_MBOX_GB_CFG0_MBOX_LOCK_MASK                           0x00000080
#define BCHP_MBOX_GB_CFG0_MBOX_LOCK_SHIFT                          7
#define BCHP_MBOX_GB_CFG0_MBOX_LOCK_DEFAULT                        0x00000000

/* MBOX_GB :: CFG0 :: MBOX_CLR_ON_READ [06:06] */
#define BCHP_MBOX_GB_CFG0_MBOX_CLR_ON_READ_MASK                    0x00000040
#define BCHP_MBOX_GB_CFG0_MBOX_CLR_ON_READ_SHIFT                   6
#define BCHP_MBOX_GB_CFG0_MBOX_CLR_ON_READ_DEFAULT                 0x00000000

/* MBOX_GB :: CFG0 :: MBOX_LOCK_SRC [05:00] */
#define BCHP_MBOX_GB_CFG0_MBOX_LOCK_SRC_MASK                       0x0000003f
#define BCHP_MBOX_GB_CFG0_MBOX_LOCK_SRC_SHIFT                      0
#define BCHP_MBOX_GB_CFG0_MBOX_LOCK_SRC_DEFAULT                    0x00000000

/***************************************************************************
 *CFG1 - MBOX1 Configuration Register
 ***************************************************************************/
/* MBOX_GB :: CFG1 :: reserved0 [31:08] */
#define BCHP_MBOX_GB_CFG1_reserved0_MASK                           0xffffff00
#define BCHP_MBOX_GB_CFG1_reserved0_SHIFT                          8

/* MBOX_GB :: CFG1 :: MBOX_LOCK [07:07] */
#define BCHP_MBOX_GB_CFG1_MBOX_LOCK_MASK                           0x00000080
#define BCHP_MBOX_GB_CFG1_MBOX_LOCK_SHIFT                          7
#define BCHP_MBOX_GB_CFG1_MBOX_LOCK_DEFAULT                        0x00000000

/* MBOX_GB :: CFG1 :: MBOX_CLR_ON_READ [06:06] */
#define BCHP_MBOX_GB_CFG1_MBOX_CLR_ON_READ_MASK                    0x00000040
#define BCHP_MBOX_GB_CFG1_MBOX_CLR_ON_READ_SHIFT                   6
#define BCHP_MBOX_GB_CFG1_MBOX_CLR_ON_READ_DEFAULT                 0x00000000

/* MBOX_GB :: CFG1 :: MBOX_LOCK_SRC [05:00] */
#define BCHP_MBOX_GB_CFG1_MBOX_LOCK_SRC_MASK                       0x0000003f
#define BCHP_MBOX_GB_CFG1_MBOX_LOCK_SRC_SHIFT                      0
#define BCHP_MBOX_GB_CFG1_MBOX_LOCK_SRC_DEFAULT                    0x00000000

/***************************************************************************
 *CFG2 - MBOX2 Configuration Register
 ***************************************************************************/
/* MBOX_GB :: CFG2 :: reserved0 [31:08] */
#define BCHP_MBOX_GB_CFG2_reserved0_MASK                           0xffffff00
#define BCHP_MBOX_GB_CFG2_reserved0_SHIFT                          8

/* MBOX_GB :: CFG2 :: MBOX_LOCK [07:07] */
#define BCHP_MBOX_GB_CFG2_MBOX_LOCK_MASK                           0x00000080
#define BCHP_MBOX_GB_CFG2_MBOX_LOCK_SHIFT                          7
#define BCHP_MBOX_GB_CFG2_MBOX_LOCK_DEFAULT                        0x00000000

/* MBOX_GB :: CFG2 :: MBOX_CLR_ON_READ [06:06] */
#define BCHP_MBOX_GB_CFG2_MBOX_CLR_ON_READ_MASK                    0x00000040
#define BCHP_MBOX_GB_CFG2_MBOX_CLR_ON_READ_SHIFT                   6
#define BCHP_MBOX_GB_CFG2_MBOX_CLR_ON_READ_DEFAULT                 0x00000000

/* MBOX_GB :: CFG2 :: MBOX_LOCK_SRC [05:00] */
#define BCHP_MBOX_GB_CFG2_MBOX_LOCK_SRC_MASK                       0x0000003f
#define BCHP_MBOX_GB_CFG2_MBOX_LOCK_SRC_SHIFT                      0
#define BCHP_MBOX_GB_CFG2_MBOX_LOCK_SRC_DEFAULT                    0x00000000

/***************************************************************************
 *CFG3 - MBOX3 Configuration Register
 ***************************************************************************/
/* MBOX_GB :: CFG3 :: reserved0 [31:08] */
#define BCHP_MBOX_GB_CFG3_reserved0_MASK                           0xffffff00
#define BCHP_MBOX_GB_CFG3_reserved0_SHIFT                          8

/* MBOX_GB :: CFG3 :: MBOX_LOCK [07:07] */
#define BCHP_MBOX_GB_CFG3_MBOX_LOCK_MASK                           0x00000080
#define BCHP_MBOX_GB_CFG3_MBOX_LOCK_SHIFT                          7
#define BCHP_MBOX_GB_CFG3_MBOX_LOCK_DEFAULT                        0x00000000

/* MBOX_GB :: CFG3 :: MBOX_CLR_ON_READ [06:06] */
#define BCHP_MBOX_GB_CFG3_MBOX_CLR_ON_READ_MASK                    0x00000040
#define BCHP_MBOX_GB_CFG3_MBOX_CLR_ON_READ_SHIFT                   6
#define BCHP_MBOX_GB_CFG3_MBOX_CLR_ON_READ_DEFAULT                 0x00000000

/* MBOX_GB :: CFG3 :: MBOX_LOCK_SRC [05:00] */
#define BCHP_MBOX_GB_CFG3_MBOX_LOCK_SRC_MASK                       0x0000003f
#define BCHP_MBOX_GB_CFG3_MBOX_LOCK_SRC_SHIFT                      0
#define BCHP_MBOX_GB_CFG3_MBOX_LOCK_SRC_DEFAULT                    0x00000000

/***************************************************************************
 *CFG4 - MBOX4 Configuration Register
 ***************************************************************************/
/* MBOX_GB :: CFG4 :: reserved0 [31:08] */
#define BCHP_MBOX_GB_CFG4_reserved0_MASK                           0xffffff00
#define BCHP_MBOX_GB_CFG4_reserved0_SHIFT                          8

/* MBOX_GB :: CFG4 :: MBOX_LOCK [07:07] */
#define BCHP_MBOX_GB_CFG4_MBOX_LOCK_MASK                           0x00000080
#define BCHP_MBOX_GB_CFG4_MBOX_LOCK_SHIFT                          7
#define BCHP_MBOX_GB_CFG4_MBOX_LOCK_DEFAULT                        0x00000000

/* MBOX_GB :: CFG4 :: MBOX_CLR_ON_READ [06:06] */
#define BCHP_MBOX_GB_CFG4_MBOX_CLR_ON_READ_MASK                    0x00000040
#define BCHP_MBOX_GB_CFG4_MBOX_CLR_ON_READ_SHIFT                   6
#define BCHP_MBOX_GB_CFG4_MBOX_CLR_ON_READ_DEFAULT                 0x00000000

/* MBOX_GB :: CFG4 :: MBOX_LOCK_SRC [05:00] */
#define BCHP_MBOX_GB_CFG4_MBOX_LOCK_SRC_MASK                       0x0000003f
#define BCHP_MBOX_GB_CFG4_MBOX_LOCK_SRC_SHIFT                      0
#define BCHP_MBOX_GB_CFG4_MBOX_LOCK_SRC_DEFAULT                    0x00000000

/***************************************************************************
 *CFG5 - MBOX5 Configuration Register
 ***************************************************************************/
/* MBOX_GB :: CFG5 :: reserved0 [31:08] */
#define BCHP_MBOX_GB_CFG5_reserved0_MASK                           0xffffff00
#define BCHP_MBOX_GB_CFG5_reserved0_SHIFT                          8

/* MBOX_GB :: CFG5 :: MBOX_LOCK [07:07] */
#define BCHP_MBOX_GB_CFG5_MBOX_LOCK_MASK                           0x00000080
#define BCHP_MBOX_GB_CFG5_MBOX_LOCK_SHIFT                          7
#define BCHP_MBOX_GB_CFG5_MBOX_LOCK_DEFAULT                        0x00000000

/* MBOX_GB :: CFG5 :: MBOX_CLR_ON_READ [06:06] */
#define BCHP_MBOX_GB_CFG5_MBOX_CLR_ON_READ_MASK                    0x00000040
#define BCHP_MBOX_GB_CFG5_MBOX_CLR_ON_READ_SHIFT                   6
#define BCHP_MBOX_GB_CFG5_MBOX_CLR_ON_READ_DEFAULT                 0x00000000

/* MBOX_GB :: CFG5 :: MBOX_LOCK_SRC [05:00] */
#define BCHP_MBOX_GB_CFG5_MBOX_LOCK_SRC_MASK                       0x0000003f
#define BCHP_MBOX_GB_CFG5_MBOX_LOCK_SRC_SHIFT                      0
#define BCHP_MBOX_GB_CFG5_MBOX_LOCK_SRC_DEFAULT                    0x00000000

/***************************************************************************
 *CFG6 - MBOX6 Configuration Register
 ***************************************************************************/
/* MBOX_GB :: CFG6 :: reserved0 [31:08] */
#define BCHP_MBOX_GB_CFG6_reserved0_MASK                           0xffffff00
#define BCHP_MBOX_GB_CFG6_reserved0_SHIFT                          8

/* MBOX_GB :: CFG6 :: MBOX_LOCK [07:07] */
#define BCHP_MBOX_GB_CFG6_MBOX_LOCK_MASK                           0x00000080
#define BCHP_MBOX_GB_CFG6_MBOX_LOCK_SHIFT                          7
#define BCHP_MBOX_GB_CFG6_MBOX_LOCK_DEFAULT                        0x00000000

/* MBOX_GB :: CFG6 :: MBOX_CLR_ON_READ [06:06] */
#define BCHP_MBOX_GB_CFG6_MBOX_CLR_ON_READ_MASK                    0x00000040
#define BCHP_MBOX_GB_CFG6_MBOX_CLR_ON_READ_SHIFT                   6
#define BCHP_MBOX_GB_CFG6_MBOX_CLR_ON_READ_DEFAULT                 0x00000000

/* MBOX_GB :: CFG6 :: MBOX_LOCK_SRC [05:00] */
#define BCHP_MBOX_GB_CFG6_MBOX_LOCK_SRC_MASK                       0x0000003f
#define BCHP_MBOX_GB_CFG6_MBOX_LOCK_SRC_SHIFT                      0
#define BCHP_MBOX_GB_CFG6_MBOX_LOCK_SRC_DEFAULT                    0x00000000

/***************************************************************************
 *CFG7 - MBOX7 Configuration Register
 ***************************************************************************/
/* MBOX_GB :: CFG7 :: reserved0 [31:08] */
#define BCHP_MBOX_GB_CFG7_reserved0_MASK                           0xffffff00
#define BCHP_MBOX_GB_CFG7_reserved0_SHIFT                          8

/* MBOX_GB :: CFG7 :: MBOX_LOCK [07:07] */
#define BCHP_MBOX_GB_CFG7_MBOX_LOCK_MASK                           0x00000080
#define BCHP_MBOX_GB_CFG7_MBOX_LOCK_SHIFT                          7
#define BCHP_MBOX_GB_CFG7_MBOX_LOCK_DEFAULT                        0x00000000

/* MBOX_GB :: CFG7 :: MBOX_CLR_ON_READ [06:06] */
#define BCHP_MBOX_GB_CFG7_MBOX_CLR_ON_READ_MASK                    0x00000040
#define BCHP_MBOX_GB_CFG7_MBOX_CLR_ON_READ_SHIFT                   6
#define BCHP_MBOX_GB_CFG7_MBOX_CLR_ON_READ_DEFAULT                 0x00000000

/* MBOX_GB :: CFG7 :: MBOX_LOCK_SRC [05:00] */
#define BCHP_MBOX_GB_CFG7_MBOX_LOCK_SRC_MASK                       0x0000003f
#define BCHP_MBOX_GB_CFG7_MBOX_LOCK_SRC_SHIFT                      0
#define BCHP_MBOX_GB_CFG7_MBOX_LOCK_SRC_DEFAULT                    0x00000000

/***************************************************************************
 *CFG8 - MBOX8 Configuration Register
 ***************************************************************************/
/* MBOX_GB :: CFG8 :: reserved0 [31:08] */
#define BCHP_MBOX_GB_CFG8_reserved0_MASK                           0xffffff00
#define BCHP_MBOX_GB_CFG8_reserved0_SHIFT                          8

/* MBOX_GB :: CFG8 :: MBOX_LOCK [07:07] */
#define BCHP_MBOX_GB_CFG8_MBOX_LOCK_MASK                           0x00000080
#define BCHP_MBOX_GB_CFG8_MBOX_LOCK_SHIFT                          7
#define BCHP_MBOX_GB_CFG8_MBOX_LOCK_DEFAULT                        0x00000000

/* MBOX_GB :: CFG8 :: MBOX_CLR_ON_READ [06:06] */
#define BCHP_MBOX_GB_CFG8_MBOX_CLR_ON_READ_MASK                    0x00000040
#define BCHP_MBOX_GB_CFG8_MBOX_CLR_ON_READ_SHIFT                   6
#define BCHP_MBOX_GB_CFG8_MBOX_CLR_ON_READ_DEFAULT                 0x00000000

/* MBOX_GB :: CFG8 :: MBOX_LOCK_SRC [05:00] */
#define BCHP_MBOX_GB_CFG8_MBOX_LOCK_SRC_MASK                       0x0000003f
#define BCHP_MBOX_GB_CFG8_MBOX_LOCK_SRC_SHIFT                      0
#define BCHP_MBOX_GB_CFG8_MBOX_LOCK_SRC_DEFAULT                    0x00000000

/***************************************************************************
 *CFG9 - MBOX9 Configuration Register
 ***************************************************************************/
/* MBOX_GB :: CFG9 :: reserved0 [31:08] */
#define BCHP_MBOX_GB_CFG9_reserved0_MASK                           0xffffff00
#define BCHP_MBOX_GB_CFG9_reserved0_SHIFT                          8

/* MBOX_GB :: CFG9 :: MBOX_LOCK [07:07] */
#define BCHP_MBOX_GB_CFG9_MBOX_LOCK_MASK                           0x00000080
#define BCHP_MBOX_GB_CFG9_MBOX_LOCK_SHIFT                          7
#define BCHP_MBOX_GB_CFG9_MBOX_LOCK_DEFAULT                        0x00000000

/* MBOX_GB :: CFG9 :: MBOX_CLR_ON_READ [06:06] */
#define BCHP_MBOX_GB_CFG9_MBOX_CLR_ON_READ_MASK                    0x00000040
#define BCHP_MBOX_GB_CFG9_MBOX_CLR_ON_READ_SHIFT                   6
#define BCHP_MBOX_GB_CFG9_MBOX_CLR_ON_READ_DEFAULT                 0x00000000

/* MBOX_GB :: CFG9 :: MBOX_LOCK_SRC [05:00] */
#define BCHP_MBOX_GB_CFG9_MBOX_LOCK_SRC_MASK                       0x0000003f
#define BCHP_MBOX_GB_CFG9_MBOX_LOCK_SRC_SHIFT                      0
#define BCHP_MBOX_GB_CFG9_MBOX_LOCK_SRC_DEFAULT                    0x00000000

/***************************************************************************
 *CFG10 - MBOX10 Configuration Register
 ***************************************************************************/
/* MBOX_GB :: CFG10 :: reserved0 [31:08] */
#define BCHP_MBOX_GB_CFG10_reserved0_MASK                          0xffffff00
#define BCHP_MBOX_GB_CFG10_reserved0_SHIFT                         8

/* MBOX_GB :: CFG10 :: MBOX_LOCK [07:07] */
#define BCHP_MBOX_GB_CFG10_MBOX_LOCK_MASK                          0x00000080
#define BCHP_MBOX_GB_CFG10_MBOX_LOCK_SHIFT                         7
#define BCHP_MBOX_GB_CFG10_MBOX_LOCK_DEFAULT                       0x00000000

/* MBOX_GB :: CFG10 :: MBOX_CLR_ON_READ [06:06] */
#define BCHP_MBOX_GB_CFG10_MBOX_CLR_ON_READ_MASK                   0x00000040
#define BCHP_MBOX_GB_CFG10_MBOX_CLR_ON_READ_SHIFT                  6
#define BCHP_MBOX_GB_CFG10_MBOX_CLR_ON_READ_DEFAULT                0x00000000

/* MBOX_GB :: CFG10 :: MBOX_LOCK_SRC [05:00] */
#define BCHP_MBOX_GB_CFG10_MBOX_LOCK_SRC_MASK                      0x0000003f
#define BCHP_MBOX_GB_CFG10_MBOX_LOCK_SRC_SHIFT                     0
#define BCHP_MBOX_GB_CFG10_MBOX_LOCK_SRC_DEFAULT                   0x00000000

/***************************************************************************
 *CFG11 - MBOX11 Configuration Register
 ***************************************************************************/
/* MBOX_GB :: CFG11 :: reserved0 [31:08] */
#define BCHP_MBOX_GB_CFG11_reserved0_MASK                          0xffffff00
#define BCHP_MBOX_GB_CFG11_reserved0_SHIFT                         8

/* MBOX_GB :: CFG11 :: MBOX_LOCK [07:07] */
#define BCHP_MBOX_GB_CFG11_MBOX_LOCK_MASK                          0x00000080
#define BCHP_MBOX_GB_CFG11_MBOX_LOCK_SHIFT                         7
#define BCHP_MBOX_GB_CFG11_MBOX_LOCK_DEFAULT                       0x00000000

/* MBOX_GB :: CFG11 :: MBOX_CLR_ON_READ [06:06] */
#define BCHP_MBOX_GB_CFG11_MBOX_CLR_ON_READ_MASK                   0x00000040
#define BCHP_MBOX_GB_CFG11_MBOX_CLR_ON_READ_SHIFT                  6
#define BCHP_MBOX_GB_CFG11_MBOX_CLR_ON_READ_DEFAULT                0x00000000

/* MBOX_GB :: CFG11 :: MBOX_LOCK_SRC [05:00] */
#define BCHP_MBOX_GB_CFG11_MBOX_LOCK_SRC_MASK                      0x0000003f
#define BCHP_MBOX_GB_CFG11_MBOX_LOCK_SRC_SHIFT                     0
#define BCHP_MBOX_GB_CFG11_MBOX_LOCK_SRC_DEFAULT                   0x00000000

/***************************************************************************
 *CFG12 - MBOX12 Configuration Register
 ***************************************************************************/
/* MBOX_GB :: CFG12 :: reserved0 [31:08] */
#define BCHP_MBOX_GB_CFG12_reserved0_MASK                          0xffffff00
#define BCHP_MBOX_GB_CFG12_reserved0_SHIFT                         8

/* MBOX_GB :: CFG12 :: MBOX_LOCK [07:07] */
#define BCHP_MBOX_GB_CFG12_MBOX_LOCK_MASK                          0x00000080
#define BCHP_MBOX_GB_CFG12_MBOX_LOCK_SHIFT                         7
#define BCHP_MBOX_GB_CFG12_MBOX_LOCK_DEFAULT                       0x00000000

/* MBOX_GB :: CFG12 :: MBOX_CLR_ON_READ [06:06] */
#define BCHP_MBOX_GB_CFG12_MBOX_CLR_ON_READ_MASK                   0x00000040
#define BCHP_MBOX_GB_CFG12_MBOX_CLR_ON_READ_SHIFT                  6
#define BCHP_MBOX_GB_CFG12_MBOX_CLR_ON_READ_DEFAULT                0x00000000

/* MBOX_GB :: CFG12 :: MBOX_LOCK_SRC [05:00] */
#define BCHP_MBOX_GB_CFG12_MBOX_LOCK_SRC_MASK                      0x0000003f
#define BCHP_MBOX_GB_CFG12_MBOX_LOCK_SRC_SHIFT                     0
#define BCHP_MBOX_GB_CFG12_MBOX_LOCK_SRC_DEFAULT                   0x00000000

/***************************************************************************
 *CFG13 - MBOX13 Configuration Register
 ***************************************************************************/
/* MBOX_GB :: CFG13 :: reserved0 [31:08] */
#define BCHP_MBOX_GB_CFG13_reserved0_MASK                          0xffffff00
#define BCHP_MBOX_GB_CFG13_reserved0_SHIFT                         8

/* MBOX_GB :: CFG13 :: MBOX_LOCK [07:07] */
#define BCHP_MBOX_GB_CFG13_MBOX_LOCK_MASK                          0x00000080
#define BCHP_MBOX_GB_CFG13_MBOX_LOCK_SHIFT                         7
#define BCHP_MBOX_GB_CFG13_MBOX_LOCK_DEFAULT                       0x00000000

/* MBOX_GB :: CFG13 :: MBOX_CLR_ON_READ [06:06] */
#define BCHP_MBOX_GB_CFG13_MBOX_CLR_ON_READ_MASK                   0x00000040
#define BCHP_MBOX_GB_CFG13_MBOX_CLR_ON_READ_SHIFT                  6
#define BCHP_MBOX_GB_CFG13_MBOX_CLR_ON_READ_DEFAULT                0x00000000

/* MBOX_GB :: CFG13 :: MBOX_LOCK_SRC [05:00] */
#define BCHP_MBOX_GB_CFG13_MBOX_LOCK_SRC_MASK                      0x0000003f
#define BCHP_MBOX_GB_CFG13_MBOX_LOCK_SRC_SHIFT                     0
#define BCHP_MBOX_GB_CFG13_MBOX_LOCK_SRC_DEFAULT                   0x00000000

/***************************************************************************
 *CFG14 - MBOX14 Configuration Register
 ***************************************************************************/
/* MBOX_GB :: CFG14 :: reserved0 [31:08] */
#define BCHP_MBOX_GB_CFG14_reserved0_MASK                          0xffffff00
#define BCHP_MBOX_GB_CFG14_reserved0_SHIFT                         8

/* MBOX_GB :: CFG14 :: MBOX_LOCK [07:07] */
#define BCHP_MBOX_GB_CFG14_MBOX_LOCK_MASK                          0x00000080
#define BCHP_MBOX_GB_CFG14_MBOX_LOCK_SHIFT                         7
#define BCHP_MBOX_GB_CFG14_MBOX_LOCK_DEFAULT                       0x00000000

/* MBOX_GB :: CFG14 :: MBOX_CLR_ON_READ [06:06] */
#define BCHP_MBOX_GB_CFG14_MBOX_CLR_ON_READ_MASK                   0x00000040
#define BCHP_MBOX_GB_CFG14_MBOX_CLR_ON_READ_SHIFT                  6
#define BCHP_MBOX_GB_CFG14_MBOX_CLR_ON_READ_DEFAULT                0x00000000

/* MBOX_GB :: CFG14 :: MBOX_LOCK_SRC [05:00] */
#define BCHP_MBOX_GB_CFG14_MBOX_LOCK_SRC_MASK                      0x0000003f
#define BCHP_MBOX_GB_CFG14_MBOX_LOCK_SRC_SHIFT                     0
#define BCHP_MBOX_GB_CFG14_MBOX_LOCK_SRC_DEFAULT                   0x00000000

/***************************************************************************
 *CFG15 - MBOX15 Configuration Register
 ***************************************************************************/
/* MBOX_GB :: CFG15 :: reserved0 [31:08] */
#define BCHP_MBOX_GB_CFG15_reserved0_MASK                          0xffffff00
#define BCHP_MBOX_GB_CFG15_reserved0_SHIFT                         8

/* MBOX_GB :: CFG15 :: MBOX_LOCK [07:07] */
#define BCHP_MBOX_GB_CFG15_MBOX_LOCK_MASK                          0x00000080
#define BCHP_MBOX_GB_CFG15_MBOX_LOCK_SHIFT                         7
#define BCHP_MBOX_GB_CFG15_MBOX_LOCK_DEFAULT                       0x00000000

/* MBOX_GB :: CFG15 :: MBOX_CLR_ON_READ [06:06] */
#define BCHP_MBOX_GB_CFG15_MBOX_CLR_ON_READ_MASK                   0x00000040
#define BCHP_MBOX_GB_CFG15_MBOX_CLR_ON_READ_SHIFT                  6
#define BCHP_MBOX_GB_CFG15_MBOX_CLR_ON_READ_DEFAULT                0x00000000

/* MBOX_GB :: CFG15 :: MBOX_LOCK_SRC [05:00] */
#define BCHP_MBOX_GB_CFG15_MBOX_LOCK_SRC_MASK                      0x0000003f
#define BCHP_MBOX_GB_CFG15_MBOX_LOCK_SRC_SHIFT                     0
#define BCHP_MBOX_GB_CFG15_MBOX_LOCK_SRC_DEFAULT                   0x00000000

#endif /* #ifndef BCHP_MBOX_GB_H__ */

/* End of File */
