/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Nov 14 03:20:37 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_TIMER_PER_H__
#define BCHP_TIMER_PER_H__

/***************************************************************************
 *TIMER_PER - Timer Registers PER
 ***************************************************************************/
#define BCHP_TIMER_PER_TIMRIRQSTAT               0x14e000c0 /* Timer Interrupt Status Register */
#define BCHP_TIMER_PER_TIMERCTL0                 0x14e000c4 /* Timer Control Word  0  Register */
#define BCHP_TIMER_PER_TIMERCTL1                 0x14e000c8 /* Timer Control Word  1  Register */
#define BCHP_TIMER_PER_TIMERCTL2                 0x14e000cc /* Timer Control Word  2  Register */
#define BCHP_TIMER_PER_TIMERCNT0                 0x14e000d0 /* Timer Count 0 Register */
#define BCHP_TIMER_PER_TIMERCNT1                 0x14e000d4 /* Timer Count 1 Register */
#define BCHP_TIMER_PER_TIMERCNT2                 0x14e000d8 /* Timer Count 2 Register */
#define BCHP_TIMER_PER_MEM_TM                    0x14e000e8 /* Memory TM Register */
#define BCHP_TIMER_PER_EPHY_TESTCNTRL            0x14e000ec /* EPHY Test Control */

/***************************************************************************
 *TIMRIRQSTAT - Timer Interrupt Status Register
 ***************************************************************************/
/* TIMER_PER :: TIMRIRQSTAT :: reserved0 [31:11] */
#define BCHP_TIMER_PER_TIMRIRQSTAT_reserved0_MASK                  0xfffff800
#define BCHP_TIMER_PER_TIMRIRQSTAT_reserved0_SHIFT                 11

/* TIMER_PER :: TIMRIRQSTAT :: Tim2Msk [10:10] */
#define BCHP_TIMER_PER_TIMRIRQSTAT_Tim2Msk_MASK                    0x00000400
#define BCHP_TIMER_PER_TIMRIRQSTAT_Tim2Msk_SHIFT                   10
#define BCHP_TIMER_PER_TIMRIRQSTAT_Tim2Msk_DEFAULT                 0x00000000

/* TIMER_PER :: TIMRIRQSTAT :: Tim1Msk [09:09] */
#define BCHP_TIMER_PER_TIMRIRQSTAT_Tim1Msk_MASK                    0x00000200
#define BCHP_TIMER_PER_TIMRIRQSTAT_Tim1Msk_SHIFT                   9
#define BCHP_TIMER_PER_TIMRIRQSTAT_Tim1Msk_DEFAULT                 0x00000000

/* TIMER_PER :: TIMRIRQSTAT :: Tim0Msk [08:08] */
#define BCHP_TIMER_PER_TIMRIRQSTAT_Tim0Msk_MASK                    0x00000100
#define BCHP_TIMER_PER_TIMRIRQSTAT_Tim0Msk_SHIFT                   8
#define BCHP_TIMER_PER_TIMRIRQSTAT_Tim0Msk_DEFAULT                 0x00000000

/* TIMER_PER :: TIMRIRQSTAT :: reserved1 [07:03] */
#define BCHP_TIMER_PER_TIMRIRQSTAT_reserved1_MASK                  0x000000f8
#define BCHP_TIMER_PER_TIMRIRQSTAT_reserved1_SHIFT                 3

/* TIMER_PER :: TIMRIRQSTAT :: Tim2Int [02:02] */
#define BCHP_TIMER_PER_TIMRIRQSTAT_Tim2Int_MASK                    0x00000004
#define BCHP_TIMER_PER_TIMRIRQSTAT_Tim2Int_SHIFT                   2

/* TIMER_PER :: TIMRIRQSTAT :: Tim1Int [01:01] */
#define BCHP_TIMER_PER_TIMRIRQSTAT_Tim1Int_MASK                    0x00000002
#define BCHP_TIMER_PER_TIMRIRQSTAT_Tim1Int_SHIFT                   1

/* TIMER_PER :: TIMRIRQSTAT :: Tim0Int [00:00] */
#define BCHP_TIMER_PER_TIMRIRQSTAT_Tim0Int_MASK                    0x00000001
#define BCHP_TIMER_PER_TIMRIRQSTAT_Tim0Int_SHIFT                   0

/***************************************************************************
 *TIMERCTL0 - Timer Control Word  0  Register
 ***************************************************************************/
/* TIMER_PER :: TIMERCTL0 :: TimrEn [31:31] */
#define BCHP_TIMER_PER_TIMERCTL0_TimrEn_MASK                       0x80000000
#define BCHP_TIMER_PER_TIMERCTL0_TimrEn_SHIFT                      31
#define BCHP_TIMER_PER_TIMERCTL0_TimrEn_DEFAULT                    0x00000000

/* TIMER_PER :: TIMERCTL0 :: CntMode [30:30] */
#define BCHP_TIMER_PER_TIMERCTL0_CntMode_MASK                      0x40000000
#define BCHP_TIMER_PER_TIMERCTL0_CntMode_SHIFT                     30
#define BCHP_TIMER_PER_TIMERCTL0_CntMode_DEFAULT                   0x00000000

/* TIMER_PER :: TIMERCTL0 :: TimerCount [29:00] */
#define BCHP_TIMER_PER_TIMERCTL0_TimerCount_MASK                   0x3fffffff
#define BCHP_TIMER_PER_TIMERCTL0_TimerCount_SHIFT                  0
#define BCHP_TIMER_PER_TIMERCTL0_TimerCount_DEFAULT                0x00000000

/***************************************************************************
 *TIMERCTL1 - Timer Control Word  1  Register
 ***************************************************************************/
/* TIMER_PER :: TIMERCTL1 :: TimrEn [31:31] */
#define BCHP_TIMER_PER_TIMERCTL1_TimrEn_MASK                       0x80000000
#define BCHP_TIMER_PER_TIMERCTL1_TimrEn_SHIFT                      31
#define BCHP_TIMER_PER_TIMERCTL1_TimrEn_DEFAULT                    0x00000000

/* TIMER_PER :: TIMERCTL1 :: CntMode [30:30] */
#define BCHP_TIMER_PER_TIMERCTL1_CntMode_MASK                      0x40000000
#define BCHP_TIMER_PER_TIMERCTL1_CntMode_SHIFT                     30
#define BCHP_TIMER_PER_TIMERCTL1_CntMode_DEFAULT                   0x00000000

/* TIMER_PER :: TIMERCTL1 :: TimerCount [29:00] */
#define BCHP_TIMER_PER_TIMERCTL1_TimerCount_MASK                   0x3fffffff
#define BCHP_TIMER_PER_TIMERCTL1_TimerCount_SHIFT                  0
#define BCHP_TIMER_PER_TIMERCTL1_TimerCount_DEFAULT                0x00000000

/***************************************************************************
 *TIMERCTL2 - Timer Control Word  2  Register
 ***************************************************************************/
/* TIMER_PER :: TIMERCTL2 :: TimrEn [31:31] */
#define BCHP_TIMER_PER_TIMERCTL2_TimrEn_MASK                       0x80000000
#define BCHP_TIMER_PER_TIMERCTL2_TimrEn_SHIFT                      31
#define BCHP_TIMER_PER_TIMERCTL2_TimrEn_DEFAULT                    0x00000000

/* TIMER_PER :: TIMERCTL2 :: CntMode [30:30] */
#define BCHP_TIMER_PER_TIMERCTL2_CntMode_MASK                      0x40000000
#define BCHP_TIMER_PER_TIMERCTL2_CntMode_SHIFT                     30
#define BCHP_TIMER_PER_TIMERCTL2_CntMode_DEFAULT                   0x00000000

/* TIMER_PER :: TIMERCTL2 :: TimerCount [29:00] */
#define BCHP_TIMER_PER_TIMERCTL2_TimerCount_MASK                   0x3fffffff
#define BCHP_TIMER_PER_TIMERCTL2_TimerCount_SHIFT                  0
#define BCHP_TIMER_PER_TIMERCTL2_TimerCount_DEFAULT                0x00000000

/***************************************************************************
 *TIMERCNT0 - Timer Count 0 Register
 ***************************************************************************/
/* TIMER_PER :: TIMERCNT0 :: reserved0 [31:31] */
#define BCHP_TIMER_PER_TIMERCNT0_reserved0_MASK                    0x80000000
#define BCHP_TIMER_PER_TIMERCNT0_reserved0_SHIFT                   31

/* TIMER_PER :: TIMERCNT0 :: Interrupt [30:30] */
#define BCHP_TIMER_PER_TIMERCNT0_Interrupt_MASK                    0x40000000
#define BCHP_TIMER_PER_TIMERCNT0_Interrupt_SHIFT                   30
#define BCHP_TIMER_PER_TIMERCNT0_Interrupt_DEFAULT                 0x00000000

/* TIMER_PER :: TIMERCNT0 :: TimerCount [29:00] */
#define BCHP_TIMER_PER_TIMERCNT0_TimerCount_MASK                   0x3fffffff
#define BCHP_TIMER_PER_TIMERCNT0_TimerCount_SHIFT                  0
#define BCHP_TIMER_PER_TIMERCNT0_TimerCount_DEFAULT                0x00000000

/***************************************************************************
 *TIMERCNT1 - Timer Count 1 Register
 ***************************************************************************/
/* TIMER_PER :: TIMERCNT1 :: reserved0 [31:31] */
#define BCHP_TIMER_PER_TIMERCNT1_reserved0_MASK                    0x80000000
#define BCHP_TIMER_PER_TIMERCNT1_reserved0_SHIFT                   31

/* TIMER_PER :: TIMERCNT1 :: Interrupt [30:30] */
#define BCHP_TIMER_PER_TIMERCNT1_Interrupt_MASK                    0x40000000
#define BCHP_TIMER_PER_TIMERCNT1_Interrupt_SHIFT                   30
#define BCHP_TIMER_PER_TIMERCNT1_Interrupt_DEFAULT                 0x00000000

/* TIMER_PER :: TIMERCNT1 :: TimerCount [29:00] */
#define BCHP_TIMER_PER_TIMERCNT1_TimerCount_MASK                   0x3fffffff
#define BCHP_TIMER_PER_TIMERCNT1_TimerCount_SHIFT                  0
#define BCHP_TIMER_PER_TIMERCNT1_TimerCount_DEFAULT                0x00000000

/***************************************************************************
 *TIMERCNT2 - Timer Count 2 Register
 ***************************************************************************/
/* TIMER_PER :: TIMERCNT2 :: reserved0 [31:31] */
#define BCHP_TIMER_PER_TIMERCNT2_reserved0_MASK                    0x80000000
#define BCHP_TIMER_PER_TIMERCNT2_reserved0_SHIFT                   31

/* TIMER_PER :: TIMERCNT2 :: Interrupt [30:30] */
#define BCHP_TIMER_PER_TIMERCNT2_Interrupt_MASK                    0x40000000
#define BCHP_TIMER_PER_TIMERCNT2_Interrupt_SHIFT                   30
#define BCHP_TIMER_PER_TIMERCNT2_Interrupt_DEFAULT                 0x00000000

/* TIMER_PER :: TIMERCNT2 :: TimerCount [29:00] */
#define BCHP_TIMER_PER_TIMERCNT2_TimerCount_MASK                   0x3fffffff
#define BCHP_TIMER_PER_TIMERCNT2_TimerCount_SHIFT                  0
#define BCHP_TIMER_PER_TIMERCNT2_TimerCount_DEFAULT                0x00000000

/***************************************************************************
 *MEM_TM - Memory TM Register
 ***************************************************************************/
/* TIMER_PER :: MEM_TM :: reserved0 [31:07] */
#define BCHP_TIMER_PER_MEM_TM_reserved0_MASK                       0xffffff80
#define BCHP_TIMER_PER_MEM_TM_reserved0_SHIFT                      7

/* TIMER_PER :: MEM_TM :: MIPS_REGFILE_TM [06:05] */
#define BCHP_TIMER_PER_MEM_TM_MIPS_REGFILE_TM_MASK                 0x00000060
#define BCHP_TIMER_PER_MEM_TM_MIPS_REGFILE_TM_SHIFT                5
#define BCHP_TIMER_PER_MEM_TM_MIPS_REGFILE_TM_DEFAULT              0x00000000

/* TIMER_PER :: MEM_TM :: BOOTROM_TM [04:00] */
#define BCHP_TIMER_PER_MEM_TM_BOOTROM_TM_MASK                      0x0000001f
#define BCHP_TIMER_PER_MEM_TM_BOOTROM_TM_SHIFT                     0
#define BCHP_TIMER_PER_MEM_TM_BOOTROM_TM_DEFAULT                   0x00000000

/***************************************************************************
 *EPHY_TESTCNTRL - EPHY Test Control
 ***************************************************************************/
/* TIMER_PER :: EPHY_TESTCNTRL :: EPHY_TESTCNTRL [31:00] */
#define BCHP_TIMER_PER_EPHY_TESTCNTRL_EPHY_TESTCNTRL_MASK          0xffffffff
#define BCHP_TIMER_PER_EPHY_TESTCNTRL_EPHY_TESTCNTRL_SHIFT         0
#define BCHP_TIMER_PER_EPHY_TESTCNTRL_EPHY_TESTCNTRL_DEFAULT       0x00000000

#endif /* #ifndef BCHP_TIMER_PER_H__ */

/* End of File */
