#!/bin/sh
# settings.cgi
#
echo "Content-type: text/html"
echo
echo "<html>"
echo "<head>"
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"main.css\" />"
echo "<title>"
echo "Setting - Universal Services Gateway"
echo "</title>"
echo "<script language=\"javascript\">"
echo "<!-- hide me"

echo "function DocLoad()"
echo "{"
echo "    var $(./service-status.sh Zeroconf);"
echo "    var $(./service-status.sh Firefly);"
echo "    var $(./service-status.sh Msc);"
echo "    var $(./service-status.sh PrintServer);"
echo 
echo "    if (Zeroconf==true) {"
echo "        window.document.UsgSettings.Zeroconf[0].checked = true;"
echo "        window.document.UsgSettings.Zeroconf[1].checked = false;"
echo "    } else {"
echo "        window.document.UsgSettings.Zeroconf[0].checked = false;"
echo "        window.document.UsgSettings.Zeroconf[1].checked = true; "
echo "    }"
echo "    if (Firefly==true) {"
echo "        window.document.UsgSettings.Firefly[0].checked  = true; "
echo "        window.document.UsgSettings.Firefly[1].checked  = false;"
echo "    } else {"
echo "        window.document.UsgSettings.Firefly[0].checked  = false;"
echo "        window.document.UsgSettings.Firefly[1].checked  = true; "
echo "    }"
echo "    if (PrintServer==true) {"
echo "        window.document.UsgSettings.PrintServer[0].checked    = true;"
echo "        window.document.UsgSettings.PrintServer[1].checked    = false;"
echo "    } else {"
echo "        window.document.UsgSettings.PrintServer[0].checked    = false;"
echo "        window.document.UsgSettings.PrintServer[1].checked    = true; "
echo "    }"
echo "}"
echo 
echo "function ApplyButton()"
echo "{"
echo "    window.document.UsgSettings.ApplyAction.value = 1;"
echo "}"
echo 
echo "// show me -->"
echo "</script>"
echo 
echo "</head>"
echo "<body onload=\"DocLoad()\"> "
echo 
echo "</div>"
echo "<div id=\"main_page\">"
echo "  <div class=\"description\">"
echo "    <h3>Basic Settings</h3>"
echo "    This page allows basic control of the"
echo "	  services shared over the network."
echo "  <br>"
echo "  </div>"
echo "<form action=settings-post.cgi method=GET name=\"UsgSettings\">"
echo "<table width=\"100%\">"
echo "  <tr valign >"
echo "    <td width=\"40%\" >Enable Zeroconf</td>"
echo "    <td width=\"10%\"><input type=\"radio\" name=\"Zeroconf\" value=\"yes\" >Yes</td>"
echo "    <td width=\"10%\"><input type=\"radio\" name=\"Zeroconf\" value=\"no\"  >No</td> "
echo "  </tr>"
echo "  <tr valign >"
echo "    <td  >Enable FireFly</td>"
echo "    <td><input type=\"radio\" name=\"Firefly\" value=\"yes\" >Yes</td>"
echo "    <td><input type=\"radio\" name=\"Firefly\" value=\"no\"   >No</td>"
echo "  </tr>"
echo "  <tr valign  ></tr>"
echo "  <tr valign >"
echo "    <td  >Enable the Print Server</td>"
echo "    <td><input type=\"radio\" name=\"PrintServer\" value=\"yes\" >Yes</td>"
echo "    <td><input type=\"radio\" name=\"PrintServer\" value=\"no\"  >No</td>"
echo "  </tr>"
echo "  <tr><td>&nbsp</td></tr>"
echo "  <tr>"
echo "    <td colspan=3 align=left><input type=\"Submit\" value=\"Apply\" align=\"MIDDLE\" onClick=\"ApplyButton();\">"
echo "        <input type=\"hidden\" name=\"ApplyAction\" ></td>"
echo "  </tr>"
echo "</table"
echo "</form>"
echo "</body>"
echo "</html>"
exit 0

