/***************************************************************************
 *     Copyright (c) 2008-2010, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 *  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 *  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *
 * Revision History:
 *
 * 4/4/08	1.0	First drop of code		tinn@broadcom.com
 *
 **************************************************************************/
#ifndef __BMIPS_5xxx_H__
#define __BMIPS_5xxx_H__


/* CP0 Register Definitions */

#define	CP0_CORE_BASE_CBA_MASK		_MM_MAKEMASK(14,18)
#define	CP0_CORE_BASE_CBA_SHIFT		(18)

#define	CP0_CORE_BASE_MSK_MASK		_MM_MAKEMASK(4,2)
#define	CP0_CORE_BASE_MSK_SHIFT		(2)

#define	CP0_CONFIG1_M_MASK              _MM_MAKEMASK1(31)
#define	CP0_CONFIG1_M_SHIFT             (31)

#define	CP0_CONFIG1_TLBSZ_MASK          _MM_MAKEMASK(6,25)
#define	CP0_CONFIG1_TLBSZ_SHIFT         (25)

#define	CP0_CONFIG1_IS_MASK             _MM_MAKEMASK(3,22)
#define	CP0_CONFIG1_IS_SHIFT            (22)

#define	CP0_CONFIG1_IL_MASK             _MM_MAKEMASK(3,19)
#define	CP0_CONFIG1_IL_SHIFT            (19)

#define	CP0_CONFIG1_IA_MASK             _MM_MAKEMASK(3,16)
#define	CP0_CONFIG1_IA_SHIFT            (16)

#define	CP0_CONFIG1_DS_MASK             _MM_MAKEMASK(3,13)
#define	CP0_CONFIG1_DS_SHIFT            (13)

#define	CP0_CONFIG1_DL_MASK             _MM_MAKEMASK(3,10)
#define	CP0_CONFIG1_DL_SHIFT            (10)

#define	CP0_CONFIG1_DA_MASK             _MM_MAKEMASK(3,7)
#define	CP0_CONFIG1_DA_SHIFT            (7)

#define	CP0_CONFIG1_C2_MASK             _MM_MAKEMASK1(6)
#define	CP0_CONFIG1_C2_SHIFT            (6)

#define	CP0_CONFIG1_MD_MASK             _MM_MAKEMASK1(5)
#define	CP0_CONFIG1_MD_SHIFT            (5)

#define	CP0_CONFIG1_PC_MASK             _MM_MAKEMASK1(4)
#define	CP0_CONFIG1_PC_SHIFT            (4)

#define	CP0_CONFIG1_WR_MASK             _MM_MAKEMASK1(3)
#define	CP0_CONFIG1_WR_SHIFT            (3)

#define	CP0_CONFIG1_CA_MASK             _MM_MAKEMASK1(2)
#define	CP0_CONFIG1_CA_SHIFT            (2)

#define	CP0_CONFIG1_EP_MASK             _MM_MAKEMASK1(1)
#define	CP0_CONFIG1_EP_SHIFT            (1)

#define	CP0_CONFIG1_FP_MASK		_MM_MAKEMASK1(0)
#define	CP0_CONFIG1_FP_SHIFT		(0)

#define	CP0_CONFIG2_L2B_MASK		_MM_MAKEMASK1(12)
#define	CP0_CONFIG2_L2B_SHIFT		(12)

#define	CP0_CACHE_ERROR1_PT_MASK	_MM_MAKEMASK1(1)
#define	CP0_CACHE_ERROR1_PT_SHIFT	(1)

#define	CP0_CACHE_ERROR1_PC_MASK	_MM_MAKEMASK1(0)
#define	CP0_CACHE_ERROR1_PC_SHIFT	(0)

#define	CP0_INDEX_Index_MASK		_MM_MAKEMASK(5,0)
#define	CP0_INDEX_Index_SHIFT		(0)

#define	CP0_RANDOM_P_MASK		_MM_MAKEMASK1(31)
#define	CP0_RANDOM_P_SHIFT		(31)

#define	CP0_RANDOM_RANDOM_MASK		_MM_MAKEMASK(5,0)
#define	CP0_RANDOM_RANDOM_SHIFT		(0)
 
#define	CP0_ENTRY_LO_0_G_MASK		_MM_MAKEMASK1(0)
#define	CP0_ENTRY_LO_0_G_SHIFT		(0)

#define	CP0_ENTRY_LO_0_V_MASK		_MM_MAKEMASK1(1)
#define	CP0_ENTRY_LO_0_V_SHIFT		(1)

#define	CP0_ENTRY_LO_0_D_MASK		_MM_MAKEMASK1(2)
#define	CP0_ENTRY_LO_0_D_SHIFT		(2)

#define	CP0_ENTRY_LO_0_CA_MASK		_MM_MAKEMASK(3,3)
#define	CP0_ENTRY_LO_0_CA_SHIFT		(3)

#define	CP0_ENTRY_LO_0_PFN_MASK		_MM_MAKEMASK(20,6)
#define	CP0_ENTRY_LO_0_PFN_SHIFT	(6)

#define	CP0_ENTRY_LO_1_G_MASK		_MM_MAKEMASK1(0)
#define	CP0_ENTRY_LO_1_G_SHIFT		(0)

#define	CP0_ENTRY_LO_1_V_MASK		_MM_MAKEMASK1(1)
#define	CP0_ENTRY_LO_1_V_SHIFT		(1)

#define	CP0_ENTRY_LO_1_D_MASK		_MM_MAKEMASK1(2)
#define	CP0_ENTRY_LO_1_D_SHIFT		(2)

#define	CP0_ENTRY_LO_1_CA_MASK		_MM_MAKEMASK(3,3)
#define	CP0_ENTRY_LO_1_CA_SHIFT		(3)

#define	CP0_ENTRY_LO_1_PFN_MASK		_MM_MAKEMASK(20,6)
#define	CP0_ENTRY_LO_1_PFN_SHIFT	(6)

#define	CP0_CONTEXT_BadVPN2_MASK	_MM_MAKEMASK(19,4)
#define	CP0_CONTEXT_BadVPN2_SHIFT	(4)

#define	CP0_CONTEXT_PTEBASE_MASK	_MM_MAKEMASK(9,23)
#define	CP0_CONTEXT_PTEBASE_SHIFT	(23)

#define	CP0_PAGE_MASK_MASK_MASK		_MM_MAKEMASK(16,13)
#define	CP0_PAGE_MASK_MASK_SHIFT	(13)

#define	CP0_WIRED_WIRED_MASK		_MM_MAKEMASK(5,0)
#define	CP0_WIRED_WIRED_SHIFT		(0)

#define	CP0_BAD_VADDR_BadVAddr_MASK	_MM_MAKEMASK(32,0)
#define	CP0_BAD_VADDR_BadVAddr_SHIFT	(0)

#define	CP0_COUNT_COUNT_MASK		_MM_MAKEMASK(32,0)
#define	CP0_COUNT_COUNT_SHIFT		(0)

#define	CP0_ENTRY_HI_ASID_MASK		_MM_MAKEMASK(8,0)
#define	CP0_ENTRY_HI_ASID_SHIFT		(0)

#define	CP0_ENTRY_HI_VPN2_MASK		_MM_MAKEMASK(19,13)
#define	CP0_ENTRY_HI_VPN2_SHIFT		(13)

#define	CP0_COMPARE_COMPARE_MASK	_MM_MAKEMASK(32,0)
#define	CP0_COMPARE_COMPARE_SHIFT	(0)

#define	CP0_STATUS_CU1_MASK             _MM_MAKEMASK1(29)
#define	CP0_STATUS_CU1_SHIFT            (28)

#define	CP0_STATUS_CU0_MASK		_MM_MAKEMASK1(28)
#define	CP0_STATUS_CU0_SHIFT		(28)

#define	CP0_STATUS_CU2_MASK	        _MM_MAKEMASK1(30)
#define	CP0_STATUS_CU2_SHIFT		(28)

#define	CP0_STATUS_CU3_MASK		_MM_MAKEMASK1(31)
#define	CP0_STATUS_CU3_SHIFT		(28)

#define	CP0_STATUS_FR_MASK		_MM_MAKEMASK1(26)
#define	CP0_STATUS_FR_SHIFT		(26)

#define	CP0_STATUS_RE_MASK		_MM_MAKEMASK1(25)
#define	CP0_STATUS_RE_SHIFT		(25)

#define	CP0_STATUS_BEV_MASK		_MM_MAKEMASK1(22)
#define	CP0_STATUS_BEV_SHIFT		(22)

#define	CP0_STATUS_TS_MASK		_MM_MAKEMASK1(21)
#define	CP0_STATUS_TS_SHIFT		(21)

#define	CP0_STATUS_SR_MASK		_MM_MAKEMASK1(20)
#define	CP0_STATUS_SR_SHIFT		(20)

#define	CP0_STATUS_NMI_MASK		_MM_MAKEMASK1(19)
#define	CP0_STATUS_NMI_SHIFT		(19)

#define	CP0_STATUS_IM_MASK		_MM_MAKEMASK(8,8)
#define	CP0_STATUS_IM_SHIFT		(8)

#define	CP0_STATUS_KSU_MASK		_MM_MAKEMASK(2,3)
#define	CP0_STATUS_KSU_SHIFT		(3)

#define	CP0_STATUS_ERL_MASK		_MM_MAKEMASK1(2)
#define	CP0_STATUS_ERL_SHIFT		(2)

#define	CP0_STATUS_EXL_MASK		_MM_MAKEMASK1(1)
#define	CP0_STATUS_EXL_SHIFT		(1)

#define	CP0_STATUS_IE_MASK		_MM_MAKEMASK1(0)
#define	CP0_STATUS_IE_SHIFT		(0)

#define	CP0_CAUSE_BD_MASK		_MM_MAKEMASK1(31)
#define	CP0_CAUSE_BD_SHIFT		(31)

#define	CP0_CAUSE_CE_MASK		_MM_MAKEMASK(2,28)
#define	CP0_CAUSE_CE_SHIFT		(28)

#define	CP0_CAUSE_IV_MASK		_MM_MAKEMASK1(23)
#define	CP0_CAUSE_IV_SHIFT		(23)

#define	CP0_CAUSE_IP_7_MASK		_MM_MAKEMASK1(15)
#define	CP0_CAUSE_IP_7_SHIFT		(15)

#define	CP0_CAUSE_IP_6_MASK		_MM_MAKEMASK1(14)
#define	CP0_CAUSE_IP_6_SHIFT		(14)

#define	CP0_CAUSE_IP_5_MASK		_MM_MAKEMASK1(13)
#define	CP0_CAUSE_IP_5_SHIFT		(13)

#define	CP0_CAUSE_IP_4_MASK		_MM_MAKEMASK1(12)
#define	CP0_CAUSE_IP_4_SHIFT		(12)

#define	CP0_CAUSE_IP_3_MASK		_MM_MAKEMASK1(11)
#define	CP0_CAUSE_IP_3_SHIFT		(11)

#define	CP0_CAUSE_IP_2_MASK		_MM_MAKEMASK1(10)
#define	CP0_CAUSE_IP_2_SHIFT		(10)

#define	CP0_CAUSE_IP_1_MASK		_MM_MAKEMASK1(9)
#define	CP0_CAUSE_IP_1_SHIFT		(9)

#define	CP0_CAUSE_IP_0_MASK		_MM_MAKEMASK1(8)
#define	CP0_CAUSE_IP_0_SHIFT		(8)

#define	CP0_CAUSE_IP_MASK		_MM_MAKEMASK(6,10)
#define	CP0_CAUSE_IP_SHIFT		(10)

#define	CP0_CAUSE_SW_MASK		_MM_MAKEMASK(2,8)
#define	CP0_CAUSE_SW_SHIFT		(8)

#define	CP0_CAUSE_EXCCODE_MASK		_MM_MAKEMASK(5,2)
#define	CP0_CAUSE_EXCCODE_SHIFT		(2)

#define	CP0_EPC_EPC_MASK		_MM_MAKEMASK(32,0)
#define	CP0_EPC_EPC_SHIFT		(0)

#define	CPO_PROC_ID_COMPANYOPTIONS_MASK	 _MM_MAKEMASK(8,24)
#define	CPO_PROC_ID_COMPANYOPTIONS_SHIFT (24)

#define	CPO_PROC_ID_COMPANYID_MASK	_MM_MAKEMASK(8,16)
#define	CPO_PROC_ID_COMPANYID_SHIFT	(16)

#define	CPO_PROC_ID_PROCESSORID_MASK	_MM_MAKEMASK(8,8)
#define	CPO_PROC_ID_PROCESSORID_SHIFT	(8) 

#define	CPO_PROC_ID_REVISION_MASK	_MM_MAKEMASK(8,0)
#define	CPO_PROC_ID_REVISION_SHIFT	(0)

#define	CP0_CONFIG_M_MASK		_MM_MAKEMASK1(31)
#define	CP0_CONFIG_M_SHIFT		(31)

#define	CP0_CONFIG_U_MASK		_MM_MAKEMASK(15,16)
#define	CP0_CONFIG_U_SHIFT		(16)

#define	CP0_CONFIG_BE_MASK		_MM_MAKEMASK1(15)
#define	CP0_CONFIG_BE_SHIFT		(15)

#define	CP0_CONFIG_AT_MASK		_MM_MAKEMASK(2,13)
#define	CP0_CONFIG_AT_SHIFT		(13)

#define	CP0_CONFIG_AR_MASK		_MM_MAKEMASK(3,10)
#define	CP0_CONFIG_AR_SHIFT		(10)

#define	CP0_CONFIG_MT_MASK		_MM_MAKEMASK(3,7)
#define	CP0_CONFIG_MT_SHIFT		(7)

#define	CP0_CONFIG_K0_MASK              _MM_MAKEMASK(3,0)
#define	CP0_CONFIG_K0_SHIFT             (0)

#define	CP0_LLADDR_PADDR_MASK		_MM_MAKEMASK(28,0)
#define	CP0_LLADDR_PADDR_SHIFT		(0)


/* BRCM Configuration Register */

#define	CP0_BRCM_CONFIG0_ICE_MASK       _MM_MAKEMASK1(31)
#define	CP0_BRCM_CONFIG0_ICE_SHIFT      (31)

#define	CP0_BRCM_CONFIG0_DCE_MASK       _MM_MAKEMASK1(30)
#define	CP0_BRCM_CONFIG0_DCE_SHIFT      (30)

#define	CP0_BRCM_CONFIG0_HP_MASK	_MM_MAKEMASK1(29)
#define	CP0_BRCM_CONFIG0_HP_SHIFT	(29)

#define	CP0_BRCM_CONFIG0_CORE_MASK	_MM_MAKEMASK(2,25)
#define	CP0_BRCM_CONFIG0_CORE_SHIFT	(25)

#define	CP0_BRCM_CONFIG0_THREAD_MASK	_MM_MAKEMASK1(24)
#define	CP0_BRCM_CONFIG0_THREAD_SHIFT	(24)

#define	CP0_BRCM_CONFIG0_ASI_MASK	_MM_MAKEMASK(2,22)
#define	CP0_BRCM_CONFIG0_ASI_SHIFT	(22)

#define	CP0_BRCM_CONFIG0_HW_MASK	_MM_MAKEMASK1(21)
#define	CP0_BRCM_CONFIG0_HW_SHIFT	(21)

#define	CP0_BRCM_CONFIG0_CWF_MASK	_MM_MAKEMASK1(20)
#define	CP0_BRCM_CONFIG0_CWF_SHIFT	(20)

#define	CP0_BRCM_CONFIG0_TSE_MASK	_MM_MAKEMASK1(19)
#define	CP0_BRCM_CONFIG0_TSE_SHIFT	(19)

#define	CP0_BRCM_CONFIG0_MT_MASK	_MM_MAKEMASK1(18)
#define	CP0_BRCM_CONFIG0_MT_SHIFT	(18)

#define	CP0_BRCM_CONFIG0_CM_MASK	_MM_MAKEMASK1(16)
#define	CP0_BRCM_CONFIG0_CM_SHIFT	(16)

#define	CP0_BRCM_CONFIG0_L2_MASK        _MM_MAKEMASK1(13)
#define	CP0_BRCM_CONFIG0_L2_SHIFT       (13)

#define	CP0_BRCM_CONFIG0_ICS_MASK	_MM_MAKEMASK1(12)
#define	CP0_BRCM_CONFIG0_ICS_SHIFT	(12)

#define	CP0_BRCM_CONFIG0_nHILO_MASK	_MM_MAKEMASK(2,2)
#define	CP0_BRCM_CONFIG0_nHILO_SHIFT	(2)

#define	CP0_BRCM_CONFIG0_eDSP_MASK	_MM_MAKEMASK1(1)
#define	CP0_BRCM_CONFIG0_eDSP_SHIFT	(1)

#define	CP0_BRCM_BOOT_VEC_EN1_MASK	_MM_MAKEMASK1(19)
#define	CP0_BRCM_BOOT_VEC_EN1_SHIFT	(19)

#define	CP0_BRCM_BOOT_VEC_EN0_MASK	_MM_MAKEMASK1(3)
#define	CP0_BRCM_BOOT_VEC_EN0_SHIFT	(3)

#define	CP0_BRCM_MODE_XIR_MASK		_MM_MAKEMASK(5,27)
#define	CP0_BRCM_MODE_XIR_SHIFT		(27)

#define	CP0_BRCM_MODE_BrPRED_MASK	_MM_MAKEMASK(2,24)
#define	CP0_BRCM_MODE_BrPRED_SHIFT	(24)

#define	CP0_BRCM_MODE_BrHIST_MASK	_MM_MAKEMASK(4,20)
#define	CP0_BRCM_MODE_BrHIST_SHIFT	(20)

#define	CP0_BRCM_MODE_TIMEOUT_MASK	_MM_MAKEMASK(4,16)
#define	CP0_BRCM_MODE_TIMEOUT_SHIFT	(16)

#define	CP0_BRCM_MODE_Luc_MASK		_MM_MAKEMASK1(11)
#define	CP0_BRCM_MODE_Luc_SHIFT		(11)

#define	CP0_BRCM_MODE_Lsc_MASK		_MM_MAKEMASK1(10)
#define	CP0_BRCM_MODE_Lsc_SHIFT		(10)

#define	CP0_BRCM_MODE_SET_MASK		_MM_MAKEMASK1(7)
#define	CP0_BRCM_MODE_SET_SHIFT		(7)

#define	CP0_BRCM_MODE_ClkRATIO_MASK	_MM_MAKEMASK(3,4)
#define	CP0_BRCM_MODE_Clk_RATIO_SHIFT	(4)

#define	CP0_BRCM_MODE_DisCNT_MASK	_MM_MAKEMASK1(3)
#define	CP0_BRCM_MODE_DisCNT_SHIFT	(3)

#define	CP0_BRCM_MODE_NMIR_MASK		_MM_MAKEMASK(2,0)
#define	CP0_BRCM_MODE_NMIR_SHIFT	(0)


/* ZSC L2 Configuration Register */

#define BRCM_ZSC_CONFIG_BypassEn_MASK		_MM_MAKEMASK1(31)
#define BRCM_ZSC_CONFIG_BypassEn_SHIFT		(31)
#define BRCM_ZSC_CONFIG_BypassEn		1 << (31)

#define BRCM_ZSC_CONFIG_ECCEna_MASK		_MM_MAKEMASK1(30)
#define BRCM_ZSC_CONFIG_ECCEna_SHIFT		(30)
#define BRCM_ZSC_CONFIG_ECCEna			1 << (30)

/* TPS + */
#define BRCM_ZSC_CONFIG_LMBRspBypEn_MASK	_MM_MAKEMASK1(28)
#define BRCM_ZSC_CONFIG_LMBRspBypEn_SHIFT	(28)
#define BRCM_ZSC_CONFIG_LMBRspBypEn		1 << (28)
/* TPS */

#define BRCM_ZSC_CONFIG_PFDblEna_MASK		_MM_MAKEMASK1(27)
#define BRCM_ZSC_CONFIG_PFDblEna_SHIFT		(27)
#define BRCM_ZSC_CONFIG_PFDblEna		1 << (27)

#define BRCM_ZSC_CONFIG_InstPrefetchEn_MASK	_MM_MAKEMASK1(26)
#define BRCM_ZSC_CONFIG_InstPrefetchEn_SHIFT	(26)
#define BRCM_ZSC_CONFIG_InstPrefetchEn		1 << (26)

#define BRCM_ZSC_CONFIG_ISDShort_MASK		_MM_MAKEMASK1(25)
#define BRCM_ZSC_CONFIG_ISDShort_SHIFT		(25)
#define BRCM_ZSC_CONFIG_ISDShort		1 << (25)

#define BRCM_ZSC_CONFIG_IPFMRULimitEn_MASK	_MM_MAKEMASK1(24)
#define BRCM_ZSC_CONFIG_IPFMRULimitEn_SHIFT	(24)
#define BRCM_ZSC_CONFIG_IPFMRULimitEn		1 << (24)

#define BRCM_ZSC_CONFIG_DataPrefetchEn_MASK	_MM_MAKEMASK1(22)
#define BRCM_ZSC_CONFIG_DataPrefetchEn_SHIFT	(22)
#define BRCM_ZSC_CONFIG_DataPrefetchEn		1 << (22)

#define BRCM_ZSC_CONFIG_DSDShort_MASK		_MM_MAKEMASK1(21)
#define BRCM_ZSC_CONFIG_DSDShort_SHIFT		(21)
#define BRCM_ZSC_CONFIG_DSDShort		1 << (21)

#define BRCM_ZSC_CONFIG_DPFMRULimitEn_MASK	_MM_MAKEMASK1(20)
#define BRCM_ZSC_CONFIG_DPFMRULimitEn_SHIFT	(20)
#define BRCM_ZSC_CONFIG_DPFMRULimitEn		1 << (20)

#define BRCM_ZSC_CONFIG_CRBBypassEn_MASK	_MM_MAKEMASK1(19)
#define BRCM_ZSC_CONFIG_CRBBypassEn_SHIFT	(19)
#define BRCM_ZSC_CONFIG_CRBBypassEn		1 << (19)

#define BRCM_ZSC_CONFIG_SleepMode_en_MASK	_MM_MAKEMASK1(18)
#define BRCM_ZSC_CONFIG_SleepMode_en_SHIFT	(18)
#define BRCM_ZSC_CONFIG_SleepMode_en		1 << (18)

#define BRCM_ZSC_CONFIG_RelaxOrderEn_MASK	_MM_MAKEMASK1(17)
#define BRCM_ZSC_CONFIG_RelaxOrderEn_SHIFT	(17)
#define BRCM_ZSC_CONFIG_RelaxOrderEn		1 << (17)

#define BRCM_ZSC_CONFIG_LMB1En_MASK		_MM_MAKEMASK1(15)
#define BRCM_ZSC_CONFIG_LMB1En_SHIFT		(15)
#define BRCM_ZSC_CONFIG_LMB1En			1 << (15)

#define BRCM_ZSC_CONFIG_LMB0En_MASK		_MM_MAKEMASK1(14)
#define BRCM_ZSC_CONFIG_LMB0En_SHIFT		(14)
#define BRCM_ZSC_CONFIG_LMB0En			1 << (14)

/* TPS + */
#define BRCM_ZSC_CONFIG_ECCCorrection_MASK	_MM_MAKEMASK1(13)
#define BRCM_ZSC_CONFIG_ECCCorrection_SHIFT	(13)
#define BRCM_ZSC_CONFIG_ECCCorrection		1 << (13)
/* TPS */

#define BRCM_ZSC_CONFIG_ECCPresent_MASK		_MM_MAKEMASK1(12)
#define BRCM_ZSC_CONFIG_ECCPresent_SHIFT	(12)
#define BRCM_ZSC_CONFIG_ECCPresent		1 << (12)

#define BRCM_ZSC_CONFIG_LineSize_MASK		_MM_MAKEMASK(4,8)
#define BRCM_ZSC_CONFIG_LineSize_SHIFT		(8)

#define BRCM_ZSC_CONFIG_Sets_MASK		_MM_MAKEMASK(4,4)
#define BRCM_ZSC_CONFIG_Sets_SHIFT		(4)

#define BRCM_ZSC_CONFIG_Assoc_MASK		_MM_MAKEMASK(4,0)
#define BRCM_ZSC_CONFIG_Assoc_SHIFT		(0)


/* ZSC L2 System Request Buffer Credit Register */

#define BRCM_ZSC_SRBC_LMB0_ReqBuf_MASK		_MM_MAKEMASK(4,28)
#define BRCM_ZSC_SRBC_LMB0_ReqBuf_SHIFT		(28)

#define BRCM_ZSC_SRBC_LMB1_ReqBuf_MASK		_MM_MAKEMASK(4,24)
#define BRCM_ZSC_SRBC_LMB1_ReqBuf_SHIFT		(24)

#define BRCM_ZSC_SRBC_SWB_MASK			_MM_MAKEMASK(4,20)
#define BRCM_ZSC_SRBC_SWB_SHIFT			(20)

#define BRCM_ZSC_SRBC_SRB1_MASK			_MM_MAKEMASK(4,12)
#define BRCM_ZSC_SRBC_SRB1_SHIFT		(12)

#define BRCM_ZSC_SRBC_SRB0_MASK			_MM_MAKEMASK(4,8)
#define BRCM_ZSC_SRBC_SRB0_SHIFT		(8)

#define BRCM_ZSC_SRBC_SRD1_MASK			_MM_MAKEMASK(2,4)
#define BRCM_ZSC_SRBC_SRD1_SHIFT		(4)

#define BRCM_ZSC_SRBC_SRD0_MASK			_MM_MAKEMASK(2,0)
#define BRCM_ZSC_SRBC_SRD0_SHIFT		(0)


/* ZSC L2 Cache Register Access Register Definitions */

#define BRCM_ZSC_ALL_REGS_SELECT		0x7 << 24

#define BRCM_ZSC_CONFIG_REG			0 << 3
#define BRCM_ZSC_REQ_BUFFER_REG			2 << 3
#define BRCM_ZSC_RBUS_ADDR_MAPPING_REG0		4 << 3
#define BRCM_ZSC_RBUS_ADDR_MAPPING_REG1		6 << 3
#define BRCM_ZSC_RBUS_ADDR_MAPPING_REG2		8 << 3

#define BRCM_ZSC_SCB0_ADDR_MAPPING_REG0		0xa << 3
#define BRCM_ZSC_SCB0_ADDR_MAPPING_REG1		0xc << 3

#define BRCM_ZSC_SCB1_ADDR_MAPPING_REG0		0xe << 3
#define BRCM_ZSC_SCB1_ADDR_MAPPING_REG1		0x10 << 3

#define BRCM_ZSC_MIPS_REVISION_REG1		0x12 << 3
#define BRCM_ZSC_TEST_MODE_REG1_ACCESS		0x20 << 3
#define BRCM_ZSC_TEST_MODE_REG2_ACCESS		0x22 << 3
#define BRCM_ZSC_TEST_MODE_REG3_ACCESS		0x28 << 3
#define BRCM_ZSC_TEST_MODE_REG4_ACCESS		0x2c << 3

#define BRCM_ZSC_MIPS_TEST_PORT_CONTROL		0x30 << 3
#define BRCM_ZSC_MIPS_TEST_CRC_REG		0x32 << 3
#define BRCM_ZSC_MIPS_TEST_POINT_TOP_SEL0	0x34 << 3
#define BRCM_ZSC_MIPS_TEST_POINT_TOP_SEL1	0x36 << 3
#define BRCM_ZSC_MIPS_TEST_POINT_MID_SEL0	0x38 << 3
#define BRCM_ZSC_MIPS_TEST_POINT_LOW_SEL0	0x3a << 3
#define BRCM_ZSC_MIPS_TEST_POINT_LOW_SEL1	0x3c << 3


/* ZSC L2 System Request Buffer Credit Register Default Values */

#define BRCM_ZSC_SRBC_LMB0_ReqBuf_DEFAULT	7 << (28)
#define BRCM_ZSC_SRBC_LMB1_ReqBuf_DEFAULT	7 << (24)
#define BRCM_ZSC_SRBC_SWB_DEFAULT		7 << (20)
#define BRCM_ZSC_SRBC_SRB1_DEFAULT		7 << (12)
#define BRCM_ZSC_SRBC_SRB0_DEFAULT		7 << (8)
#define BRCM_ZSC_SRBC_SRD1_DEFAULT		1 << (4)
#define BRCM_ZSC_SRBC_SRD0_DEFAULT		1 << (0)


/* data and instruction and secondary cache data and tag registers */

#define CP0_ZSC_STG_SEL_MASK		0x07000000
#define CP0_ZSC_STG_SEL_TAG_STATE	0x00000000
#define CP0_ZSC_STG_SEL_LRU		0x01000000
#define CP0_ZSC_STG_SEL_DIR		0x02000000
#define CP0_ZSC_STG_SEL_DATA		0x04000000
#define CP0_ZSC_STG_SEL_DATA_ECC	0x05000000
#define CP0_ZSC_STG_SEL_ECC		0x06000000
#define CP0_ZSC_STG_SEL_CTRL		0x07000000

#define	CP0_ZSC_MAX_ADDR		0x00040000
#define	CP0_ZSC_MAX_ADDR_BY_INDEX	0x00008000

/* branch predition values */

#define BRCM_BrPRED_ALL_TAKEN		(0x0)
#define BRCM_BrPRED_ALL_NOT_TAKEN	(0x1)
#define BRCM_BrPRED_BHT_ENABLE		(0x2)
#define BRCM_BrPRED_PREDICT_BACKWARD	(0x3)

/* timeout value */

#define BRCM_TIMEOUT_OFF		(0x0)
#define BRCM_TIMEOUT_ON			(0x1)

/* clock set and ratio values */

#define	BRCM_SET_CLOCK_ON		(0x1)
#define	BRCM_SET_CLOCK_OFF		(0x0)

#define BRCM_ClkRATIO_FULL_SPEED	(0x0)
#define BRCM_ClkRATIO_HALF_SPEED	(0x1)
#define BRCM_ClkRATIO_QUARTER_SPEED	(0x2)
#define BRCM_ClkRATIO_EIGHT_SPEED	(0x3)
#define BRCM_ClkRATIO_SIXTEENTH_SPEED	(0x4)

/* disable counting  values */

#define BRCM_DisCNT_ON			(0x0)
#define BRCM_DisCNT_OFF			(0x1)

/* NMI values */

#define	BRCM_NMIR_RESET_TP0		(0x1)
#define	BRCM_NMIR_RESET_TP1		(0x2)

#define		INPUT_CLK_CYCLES_PER_COUNT_REG_INCR 8			/* For BMIPS-5000 */

#define	NUM_TLB_ENTRIES			(64)

#endif

